const pool = require('../Pool_DB');

let esquemaMensajesListo = null;

async function crearEsquemaMensajes() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS public.conversations (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      direct_key text NOT NULL UNIQUE,
      created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
      updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public.conversation_members (
      conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
      user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
      joined_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
      CONSTRAINT conversation_members_pkey PRIMARY KEY (conversation_id, user_id)
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS public.messages (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
      sender_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
      body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
      read_at timestamptz,
      created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
    )
  `);

  await pool.query('CREATE INDEX IF NOT EXISTS conversation_members_user_idx ON public.conversation_members(user_id, conversation_id)');
  await pool.query('CREATE INDEX IF NOT EXISTS conversations_updated_idx ON public.conversations(updated_at DESC)');
  await pool.query('CREATE INDEX IF NOT EXISTS messages_conversation_created_idx ON public.messages(conversation_id, created_at, id)');
  await pool.query('CREATE INDEX IF NOT EXISTS messages_unread_idx ON public.messages(conversation_id, sender_id) WHERE read_at IS NULL');
}

async function asegurarEsquemaMensajes() {
  if (!esquemaMensajesListo) {
    esquemaMensajesListo = crearEsquemaMensajes().catch((error) => {
      esquemaMensajesListo = null;
      throw error;
    });
  }
  return esquemaMensajesListo;
}

module.exports = { asegurarEsquemaMensajes };
