const pool = require('../Pool_DB');
const TIPOS_CONTENIDO_DENUNCIABLE = ['reel', 'evento', 'perfil', 'community_post', 'community_comment'];

let esquemaModeracionListo = null;

async function asegurarEsquemaModeracion() {
  if (!esquemaModeracionListo) {
    esquemaModeracionListo = (async () => {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS user_blocks (
          blocker_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          blocked_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
          CONSTRAINT user_blocks_pkey PRIMARY KEY (blocker_id, blocked_id),
          CONSTRAINT user_blocks_different_users CHECK (blocker_id <> blocked_id)
        )
      `);
      await pool.query('CREATE INDEX IF NOT EXISTS idx_user_blocks_blocked_id ON user_blocks(blocked_id)');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS content_reports (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          reporter_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          reported_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
          content_type text NOT NULL CHECK (content_type IN ('reel', 'evento', 'perfil', 'community_post', 'community_comment')),
          content_id text NOT NULL,
          reason text NOT NULL DEFAULT 'contenido_inapropiado',
          details text NOT NULL DEFAULT '',
          status text NOT NULL DEFAULT 'pendiente',
          created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
          CONSTRAINT content_reports_unique UNIQUE (reporter_id, content_type, content_id)
        )
      `);
      await pool.query("ALTER TABLE content_reports ADD COLUMN IF NOT EXISTS details text NOT NULL DEFAULT ''");
      await pool.query('ALTER TABLE content_reports DROP CONSTRAINT IF EXISTS content_reports_content_type_check');
      await pool.query(`
        ALTER TABLE content_reports
        ADD CONSTRAINT content_reports_content_type_check
        CHECK (content_type IN ('reel', 'evento', 'perfil', 'community_post', 'community_comment'))
      `);
      await pool.query('CREATE INDEX IF NOT EXISTS idx_content_reports_status ON content_reports(status, created_at DESC)');
    })().catch((error) => {
      esquemaModeracionListo = null;
      throw error;
    });
  }
  return esquemaModeracionListo;
}

async function registrarDenuncia({ reporterId, reportedUserId, contentType, contentId, reason, details }) {
  await asegurarEsquemaModeracion();
  if (!TIPOS_CONTENIDO_DENUNCIABLE.includes(contentType)) {
    const error = new Error('El tipo de contenido denunciado no es valido.');
    error.status = 400;
    throw error;
  }
  if (reportedUserId === reporterId) {
    const error = new Error('No podes denunciar contenido propio.');
    error.status = 400;
    throw error;
  }
  const result = await pool.query(
    `INSERT INTO content_reports
       (reporter_id, reported_user_id, content_type, content_id, reason, details)
     VALUES ($1, $2, $3, $4, $5, $6)
     ON CONFLICT (reporter_id, content_type, content_id) DO NOTHING
     RETURNING id`,
    [
      reporterId,
      reportedUserId,
      contentType,
      String(contentId),
      reason || 'otro',
      String(details || '').trim().slice(0, 500),
    ]
  );
  return { denunciado: true, nuevaDenuncia: result.rowCount > 0 };
}

module.exports = { asegurarEsquemaModeracion, registrarDenuncia };
