const pool = require('../Pool_DB');

let esquemaNotificacionesListo = null;

const PREFERENCIA_POR_TIPO = Object.freeze({
  reel_like: 'notificar_interacciones',
  reel_comment_like: 'notificar_interacciones',
  community_like: 'notificar_interacciones',
  community_comment_like: 'notificar_interacciones',
  reel_comment: 'notificar_comentarios',
  reel_reply: 'notificar_comentarios',
  community_comment: 'notificar_comentarios',
  community_reply: 'notificar_comentarios',
  follow: 'notificar_seguidores',
  new_reel: 'notificar_publicaciones',
  new_event: 'notificar_publicaciones',
  new_community_post: 'notificar_publicaciones',
  mention: 'notificar_menciones',
  event_coorganizer: 'notificar_menciones',
});

function nombreActor(user) {
  return user?.user_metadata?.name
    || user?.user_metadata?.username
    || user?.email?.split('@')[0]
    || 'Alguien';
}

async function crearEsquemaNotificaciones(client = pool) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.user_settings (
      user_id uuid PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
      telefono text NOT NULL DEFAULT '' CHECK (length(telefono) <= 30),
      codigo_pais text NOT NULL DEFAULT '+54',
      idioma text NOT NULL DEFAULT 'es',
      actividad_cuenta boolean NOT NULL DEFAULT true,
      notificar_interacciones boolean NOT NULL DEFAULT true,
      notificar_comentarios boolean NOT NULL DEFAULT true,
      notificar_seguidores boolean NOT NULL DEFAULT true,
      notificar_publicaciones boolean NOT NULL DEFAULT true,
      notificar_menciones boolean NOT NULL DEFAULT true,
      reducir_movimiento boolean NOT NULL DEFAULT false,
      mostrar_email boolean NOT NULL DEFAULT false,
      created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
      updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
    )
  `);

  await client.query(`
    ALTER TABLE public.user_settings
      ADD COLUMN IF NOT EXISTS telefono text NOT NULL DEFAULT '',
      ADD COLUMN IF NOT EXISTS codigo_pais text NOT NULL DEFAULT '+54',
      ADD COLUMN IF NOT EXISTS idioma text NOT NULL DEFAULT 'es',
      ADD COLUMN IF NOT EXISTS actividad_cuenta boolean NOT NULL DEFAULT true,
      ADD COLUMN IF NOT EXISTS notificar_interacciones boolean NOT NULL DEFAULT true,
      ADD COLUMN IF NOT EXISTS notificar_comentarios boolean NOT NULL DEFAULT true,
      ADD COLUMN IF NOT EXISTS notificar_seguidores boolean NOT NULL DEFAULT true,
      ADD COLUMN IF NOT EXISTS notificar_publicaciones boolean NOT NULL DEFAULT true,
      ADD COLUMN IF NOT EXISTS notificar_menciones boolean NOT NULL DEFAULT true,
      ADD COLUMN IF NOT EXISTS reducir_movimiento boolean NOT NULL DEFAULT false,
      ADD COLUMN IF NOT EXISTS mostrar_email boolean NOT NULL DEFAULT false,
      ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
      ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
  `);

  await client.query(`
    CREATE TABLE IF NOT EXISTS public.notification_mutes (
      user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
      muted_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
      created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
      CONSTRAINT notification_mutes_pkey PRIMARY KEY (user_id, muted_user_id),
      CONSTRAINT notification_mutes_no_self CHECK (user_id <> muted_user_id)
    )
  `);

  await client.query(`
    CREATE TABLE IF NOT EXISTS public.notifications (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
      actor_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
      type text NOT NULL,
      title text NOT NULL,
      body text NOT NULL DEFAULT '',
      target_url text NOT NULL DEFAULT '',
      entity_type text,
      entity_id text,
      metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
      unique_key text UNIQUE,
      read_at timestamptz,
      created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
    )
  `);

  await client.query(`
    ALTER TABLE public.notifications
      ADD COLUMN IF NOT EXISTS actor_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
      ADD COLUMN IF NOT EXISTS body text NOT NULL DEFAULT '',
      ADD COLUMN IF NOT EXISTS target_url text NOT NULL DEFAULT '',
      ADD COLUMN IF NOT EXISTS entity_type text,
      ADD COLUMN IF NOT EXISTS entity_id text,
      ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
      ADD COLUMN IF NOT EXISTS unique_key text,
      ADD COLUMN IF NOT EXISTS read_at timestamptz,
      ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
  `);

  await client.query(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'notifications_unique_key_key'
          AND conrelid = 'public.notifications'::regclass
      ) THEN
        ALTER TABLE public.notifications
          ADD CONSTRAINT notifications_unique_key_key UNIQUE (unique_key);
      END IF;
    END $$
  `);

  await client.query('CREATE INDEX IF NOT EXISTS notifications_user_created_idx ON public.notifications(user_id, created_at DESC)');
  await client.query('CREATE INDEX IF NOT EXISTS notifications_user_unread_idx ON public.notifications(user_id, created_at DESC) WHERE read_at IS NULL');
  await client.query('CREATE INDEX IF NOT EXISTS notification_mutes_muted_user_idx ON public.notification_mutes(muted_user_id)');
}

async function asegurarEsquemaNotificaciones(client = pool) {
  if (client !== pool) {
    return asegurarEsquemaNotificaciones();
  }

  if (!esquemaNotificacionesListo) {
    esquemaNotificacionesListo = crearEsquemaNotificaciones().catch((error) => {
      esquemaNotificacionesListo = null;
      throw error;
    });
  }

  return esquemaNotificacionesListo;
}

async function crearNotificacion({
  userId,
  actorId,
  type,
  title,
  body = '',
  targetUrl = '',
  entityType = null,
  entityId = null,
  metadata = {},
  uniqueKey = null,
}, client = pool) {
  if (!userId || userId === actorId) return null;
  try {
    await asegurarEsquemaNotificaciones(client);
    const columnaPreferencia = PREFERENCIA_POR_TIPO[type];
    const condicionPreferencia = columnaPreferencia
      ? `AND COALESCE((SELECT ${columnaPreferencia} FROM user_settings WHERE user_id = $1), true)`
      : '';
    const result = await client.query(
    `INSERT INTO notifications (
       user_id, actor_id, type, title, body, target_url,
       entity_type, entity_id, metadata, unique_key
     )
     SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9::jsonb, $10
     WHERE COALESCE(
       (SELECT actividad_cuenta FROM user_settings WHERE user_id = $1),
       true
     )
       ${condicionPreferencia}
       AND NOT EXISTS (
         SELECT 1 FROM notification_mutes
         WHERE user_id = $1 AND muted_user_id = $2
       )
     ON CONFLICT (unique_key) DO NOTHING
     RETURNING id`,
    [
      userId,
      actorId || null,
      type,
      String(title || '').slice(0, 120),
      String(body || '').slice(0, 500),
      targetUrl,
      entityType,
      entityId === null || entityId === undefined ? null : String(entityId),
      JSON.stringify(metadata || {}),
      uniqueKey,
    ]
  );

    return result.rows[0] || null;
  } catch (error) {
    console.error('No se pudo crear una notificacion:', error);
    return null;
  }
}

async function eliminarNotificacion(uniqueKey, client = pool) {
  if (!uniqueKey) return;
  try {
    await asegurarEsquemaNotificaciones(client);
    await client.query('DELETE FROM notifications WHERE unique_key = $1', [uniqueKey]);
  } catch (error) {
    console.error('No se pudo eliminar una notificacion:', error);
  }
}

async function notificarSeguidores({
  actorId,
  type,
  title,
  body = '',
  targetUrl = '',
  entityType = null,
  entityId = null,
  uniquePrefix,
}, client = pool) {
  try {
    if (!actorId || !uniquePrefix) return 0;
    await asegurarEsquemaNotificaciones(client);

    const seguidores = await client.query(
    `SELECT f.follower_id
     FROM follows f
     WHERE f.following_id = $1
       AND f.follower_id <> $1
       AND NOT EXISTS (
         SELECT 1 FROM notification_mutes nm
         WHERE nm.user_id = f.follower_id AND nm.muted_user_id = $1
       )`,
    [actorId]
    );

    const creadas = await Promise.all(seguidores.rows.map((seguidor) => crearNotificacion({
      userId: seguidor.follower_id,
      actorId,
      type,
      title,
      body,
      targetUrl,
      entityType,
      entityId,
      uniqueKey: `${uniquePrefix}:${seguidor.follower_id}`,
    }, client)));

    return creadas.filter(Boolean).length;
  } catch (error) {
    console.error('No se pudo notificar a los seguidores:', error);
    return 0;
  }
}

async function notificarMenciones({
  texto,
  actorId,
  actorName,
  targetUrl,
  entityType,
  entityId,
}, client = pool) {
  const usernames = [...new Set(
    [...String(texto || '').matchAll(/@([a-zA-Z0-9_.-]{1,40})/g)]
      .map((coincidencia) => coincidencia[1].toLowerCase())
  )];
  if (usernames.length === 0) return;

  try {
    const usuarios = await client.query(
      'SELECT id, username FROM users WHERE lower(username) = ANY($1::text[])',
      [usernames]
    );

    await Promise.all(usuarios.rows.map((usuario) => crearNotificacion({
      userId: usuario.id,
      actorId,
      type: 'mention',
      title: `${actorName} te menciono`,
      body: 'Toca para ver la conversacion.',
      targetUrl,
      entityType,
      entityId,
      uniqueKey: `mention:${entityType}:${entityId}:${usuario.id}`,
    }, client)));
  } catch (error) {
    console.error('No se pudieron procesar las menciones:', error);
  }
}

module.exports = {
  asegurarEsquemaNotificaciones,
  crearNotificacion,
  eliminarNotificacion,
  nombreActor,
  notificarMenciones,
  notificarSeguidores,
};
