const pool = require('../Pool_DB');

let schemaReady = null;

async function ensureProfileCommunitySchema() {
  if (!schemaReady) {
    schemaReady = (async () => {
      await pool.query('ALTER TABLE eventos ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT timezone(\'utc\'::text, now())');
      await pool.query('ALTER TABLE reels ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT timezone(\'utc\'::text, now())');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS profile_community_posts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          texto text NOT NULL DEFAULT '',
          attachment_type text CHECK (attachment_type IN ('reel', 'evento')),
          reel_id bigint REFERENCES reels(id) ON DELETE CASCADE,
          event_id bigint REFERENCES eventos(id) ON DELETE CASCADE,
          created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
          CONSTRAINT profile_community_posts_attachment CHECK (
            (attachment_type IS NULL AND reel_id IS NULL AND event_id IS NULL) OR
            (attachment_type = 'reel' AND reel_id IS NOT NULL AND event_id IS NULL) OR
            (attachment_type = 'evento' AND event_id IS NOT NULL AND reel_id IS NULL)
          )
        )
      `);
      await pool.query(`
        CREATE TABLE IF NOT EXISTS profile_community_comments (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          post_id bigint NOT NULL REFERENCES profile_community_posts(id) ON DELETE CASCADE,
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          texto text NOT NULL CHECK (length(trim(texto)) > 0),
          created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
        )
      `);
      await pool.query('CREATE UNIQUE INDEX IF NOT EXISTS profile_community_posts_reel_unique ON profile_community_posts(reel_id) WHERE reel_id IS NOT NULL');
      await pool.query('CREATE UNIQUE INDEX IF NOT EXISTS profile_community_posts_event_unique ON profile_community_posts(event_id) WHERE event_id IS NOT NULL');
      await pool.query('CREATE INDEX IF NOT EXISTS profile_community_posts_user_date_idx ON profile_community_posts(user_id, created_at DESC)');
      await pool.query('CREATE INDEX IF NOT EXISTS profile_community_comments_post_date_idx ON profile_community_comments(post_id, created_at ASC)');
    })().catch((error) => {
      schemaReady = null;
      throw error;
    });
  }
  return schemaReady;
}

async function syncPublishedActivity(userId) {
  await ensureProfileCommunitySchema();
  await pool.query(
    `INSERT INTO profile_community_posts (user_id, texto, attachment_type, reel_id, created_at)
     SELECT r.creador_id, 'Publicó una nueva preview.', 'reel', r.id, r.created_at
     FROM reels r
     WHERE r.creador_id = $1
     ON CONFLICT (reel_id) WHERE reel_id IS NOT NULL DO NOTHING`,
    [userId]
  );
  await pool.query(
    `INSERT INTO profile_community_posts (user_id, texto, attachment_type, event_id, created_at)
     SELECT e.creador_id, 'Creó un nuevo evento.', 'evento', e.id, e.created_at
     FROM eventos e
     WHERE e.creador_id = $1
     ON CONFLICT (event_id) WHERE event_id IS NOT NULL DO NOTHING`,
    [userId]
  );
}

function relativeTime(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  const seconds = Math.max(0, Math.floor((Date.now() - date.getTime()) / 1000));
  if (seconds < 60) return 'ahora';
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `hace ${minutes} min`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `hace ${hours} h`;
  const days = Math.floor(hours / 24);
  return `hace ${days} día${days === 1 ? '' : 's'}`;
}

function mapComment(row) {
  return {
    id: row.id,
    userId: row.user_id,
    usuario: `@${String(row.username || row.email?.split('@')[0] || 'usuario').replace(/^@/, '')}`,
    nombre: row.artist_name || row.full_name || row.username || 'Usuario SONDAR',
    avatar: row.profile_img_url || '',
    texto: row.texto,
    tiempo: relativeTime(row.created_at),
  };
}

function mapPost(row, comments) {
  const attachment = row.attachment_type === 'reel'
    ? { tipo: 'reel', id: row.reel_id, titulo: row.reel_album || row.reel_titulo, detalle: row.reel_genero, imagen: row.reel_portada || '' }
    : row.attachment_type === 'evento'
      ? { tipo: 'evento', id: row.event_id, titulo: row.event_titulo, detalle: [row.event_genero, row.event_lugar].filter(Boolean).join(' · '), imagen: row.event_image || '' }
      : null;
  return {
    id: row.id,
    userId: row.user_id,
    usuario: `@${String(row.username || row.email?.split('@')[0] || 'usuario').replace(/^@/, '')}`,
    nombre: row.artist_name || row.full_name || row.username || 'Usuario SONDAR',
    avatar: row.profile_img_url || '',
    texto: row.texto,
    tipo: row.attachment_type || 'actualizacion',
    adjunto: attachment,
    tiempo: relativeTime(row.created_at),
    comentarios: comments,
  };
}

async function listProfileCommunity(userId) {
  await syncPublishedActivity(userId);
  const posts = await pool.query(
    `SELECT
       p.*,
       u.email,
       u.username,
       u.full_name,
       u.artist_name,
       u.profile_img_url,
       r.titulo AS reel_titulo,
       r.album AS reel_album,
       r.genero AS reel_genero,
       r.portada_url AS reel_portada,
       e.titulo AS event_titulo,
       e.genero AS event_genero,
       e.lugar AS event_lugar,
       e.img_url AS event_image
     FROM profile_community_posts p
     JOIN users u ON u.id = p.user_id
     LEFT JOIN reels r ON r.id = p.reel_id
     LEFT JOIN eventos e ON e.id = p.event_id
     WHERE p.user_id = $1
     ORDER BY p.created_at DESC, p.id DESC
     LIMIT 80`,
    [userId]
  );
  const ids = posts.rows.map(post => post.id);
  const comments = ids.length === 0 ? { rows: [] } : await pool.query(
    `SELECT c.*, u.email, u.username, u.full_name, u.artist_name, u.profile_img_url
     FROM profile_community_comments c
     JOIN users u ON u.id = c.user_id
     WHERE c.post_id = ANY($1::bigint[])
     ORDER BY c.created_at ASC, c.id ASC`,
    [ids]
  );
  const byPost = new Map();
  comments.rows.forEach(row => byPost.set(String(row.post_id), [...(byPost.get(String(row.post_id)) || []), mapComment(row)]));
  return posts.rows.map(row => mapPost(row, byPost.get(String(row.id)) || []));
}

async function createProfileCommunityPost({ userId, texto, attachmentType, attachmentId }) {
  await ensureProfileCommunitySchema();
  const cleanText = String(texto || '').trim().slice(0, 1000);
  const type = attachmentType === 'reel' || attachmentType === 'evento' ? attachmentType : null;
  const numericId = attachmentId ? Number(attachmentId) : null;
  if (!cleanText && !type) {
    const error = new Error('Escribí una actualización o adjuntá contenido.');
    error.status = 400;
    throw error;
  }
  if (type && (!Number.isInteger(numericId) || numericId <= 0)) {
    const error = new Error('El contenido adjunto no es válido.');
    error.status = 400;
    throw error;
  }
  if (type) {
    const table = type === 'reel' ? 'reels' : 'eventos';
    const owned = await pool.query(`SELECT id FROM ${table} WHERE id = $1 AND creador_id = $2`, [numericId, userId]);
    if (owned.rowCount === 0) {
      const error = new Error('Sólo podés adjuntar contenido publicado por vos.');
      error.status = 403;
      throw error;
    }
  }
  if (type === 'reel') {
    await pool.query(
      `INSERT INTO profile_community_posts (user_id, texto, attachment_type, reel_id)
       VALUES ($1, $2, 'reel', $3)
       ON CONFLICT (reel_id) WHERE reel_id IS NOT NULL
       DO UPDATE SET texto = EXCLUDED.texto, created_at = timezone('utc'::text, now())`,
      [userId, cleanText, numericId]
    );
  } else if (type === 'evento') {
    await pool.query(
      `INSERT INTO profile_community_posts (user_id, texto, attachment_type, event_id)
       VALUES ($1, $2, 'evento', $3)
       ON CONFLICT (event_id) WHERE event_id IS NOT NULL
       DO UPDATE SET texto = EXCLUDED.texto, created_at = timezone('utc'::text, now())`,
      [userId, cleanText, numericId]
    );
  } else {
    await pool.query(
      'INSERT INTO profile_community_posts (user_id, texto) VALUES ($1, $2)',
      [userId, cleanText]
    );
  }
  const posts = await listProfileCommunity(userId);
  return posts[0];
}

async function createProfileCommunityComment({ userId, postId, texto }) {
  await ensureProfileCommunitySchema();
  const cleanText = String(texto || '').trim().slice(0, 500);
  if (!cleanText) {
    const error = new Error('La respuesta no puede estar vacía.');
    error.status = 400;
    throw error;
  }
  const result = await pool.query(
    `INSERT INTO profile_community_comments (post_id, user_id, texto)
     SELECT id, $2, $3 FROM profile_community_posts WHERE id = $1
     RETURNING *`,
    [postId, userId, cleanText]
  );
  if (result.rowCount === 0) {
    const error = new Error('La publicación ya no está disponible.');
    error.status = 404;
    throw error;
  }
  const user = await pool.query('SELECT * FROM users WHERE id = $1', [userId]);
  return mapComment({ ...result.rows[0], ...user.rows[0] });
}

async function deleteProfileCommunityPost({ userId, postId }) {
  await ensureProfileCommunitySchema();
  const result = await pool.query('DELETE FROM profile_community_posts WHERE id = $1 AND user_id = $2 RETURNING id', [postId, userId]);
  if (result.rowCount === 0) {
    const error = new Error('No tenés permiso para eliminar esta publicación.');
    error.status = 404;
    throw error;
  }
  return result.rows[0];
}

async function getProfileCommunityPost(postId) {
  await ensureProfileCommunitySchema();
  const result = await pool.query('SELECT id, user_id, texto FROM profile_community_posts WHERE id = $1', [postId]);
  return result.rows[0] || null;
}

module.exports = {
  ensureProfileCommunitySchema,
  listProfileCommunity,
  createProfileCommunityPost,
  createProfileCommunityComment,
  deleteProfileCommunityPost,
  getProfileCommunityPost,
};
