const pool = require('../Pool_DB');
const supabase = require('../services/supabaseClient');
const supabaseAuth = supabase.authClient || supabase;
const {
  crearNotificacion,
  eliminarNotificacion,
  nombreActor,
  notificarMenciones,
  notificarSeguidores,
} = require('../services/notificationService');

const COMUNIDADES_GENERO = [
  {
    id: 'pop',
    nombre: '@pop',
    titulo: 'Pop',
    genero: 'pop',
    descripcion: 'Charlas, lanzamientos, preguntas y recomendaciones para la escena pop de SONDAR.',
    portada: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=80',
  },
  {
    id: 'rock',
    nombre: '@rock',
    titulo: 'Rock',
    genero: 'rock',
    descripcion: 'Guitarras, fechas, bandas nuevas, demos y conversaciones de la comunidad rock.',
    portada: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1400&q=80',
  },
  {
    id: 'edm',
    nombre: '@edm',
    titulo: 'EDM',
    genero: 'edm',
    descripcion: 'Sets, drops, produccion, festivales y novedades de la comunidad EDM.',
    portada: 'https://images.unsplash.com/photo-1571266028243-d220c9c3b8ef?auto=format&fit=crop&w=1400&q=80',
  },
  {
    id: 'jazz',
    nombre: '@jazz',
    titulo: 'Jazz',
    genero: 'jazz',
    descripcion: 'Improvisacion, standards, jams, discos y encuentros para oyentes y musicos de jazz.',
    portada: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1400&q=80',
  },
  {
    id: 'blues',
    nombre: '@blues',
    titulo: 'Blues',
    genero: 'blues',
    descripcion: 'Riffs, armonicas, zapadas, fechas y recomendaciones para quienes siguen el blues.',
    portada: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80',
  },
  {
    id: 'cumbia',
    nombre: '@cumbia',
    titulo: 'Cumbia',
    genero: 'cumbia',
    descripcion: 'Bandas, bailes, estrenos, eventos y charla abierta para la comunidad cumbiera.',
    portada: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=80',
  },
  {
    id: 'trap',
    nombre: '@trap',
    titulo: 'Trap',
    genero: 'trap',
    descripcion: 'Beats, barras, productores, lanzamientos y debates de la escena trap.',
    portada: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1400&q=80',
  },
  {
    id: 'metal',
    nombre: '@metal',
    titulo: 'Metal',
    genero: 'metal',
    descripcion: 'Riffs pesados, fechas, discos, bandas emergentes y comunidad metalera.',
    portada: 'https://images.unsplash.com/photo-1508252592163-5d3c3c5599ab?auto=format&fit=crop&w=1400&q=80',
  },
  {
    id: 'folklore',
    nombre: '@folklore',
    titulo: 'Folklore',
    genero: 'folklore',
    descripcion: 'Peñas, canciones, instrumentos, festivales y relatos de la escena folklorica.',
    portada: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1400&q=80',
  },
];

let esquemaComunidadesListo = null;

async function obtenerViewerId(req) {
  const authorization = req.headers.authorization || '';
  const token = authorization.startsWith('Bearer ')
    ? authorization.slice('Bearer '.length)
    : '';

  if (!token) return null;

  const { data, error } = await supabaseAuth.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user.id;
}

async function asegurarUsuarioPublico(user) {
  const email = user.email || `${user.id}@sin-email.local`;
  const baseUsername =
    user.user_metadata?.username ||
    user.user_metadata?.name ||
    email.split('@')[0] ||
    'usuario';
  const username = `${baseUsername}`.trim().toLowerCase().replace(/^@+/, '').replace(/[^a-z0-9._-]/g, '').slice(0, 21) || 'usuario';
  const usernameSeguro = `${username}_${user.id.slice(0, 8)}`;

  await pool.query(
    `INSERT INTO users (id, email, username, user_type)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (id) DO UPDATE
     SET email = EXCLUDED.email
     RETURNING id`,
    [user.id, email, usernameSeguro, process.env.DEFAULT_USER_TYPE || 'musico']
  );
}

async function asegurarEsquemaComunidades() {
  if (!esquemaComunidadesListo) {
    esquemaComunidadesListo = (async () => {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS comunidades (
          id text PRIMARY KEY,
          nombre text NOT NULL UNIQUE,
          titulo text NOT NULL,
          genero text NOT NULL UNIQUE,
          descripcion text NOT NULL,
          portada_url text,
          activa boolean NOT NULL DEFAULT true,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
        )
      `);

      await pool.query(`
        CREATE TABLE IF NOT EXISTS comunidad_publicaciones (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          comunidad_id text NOT NULL REFERENCES comunidades(id) ON DELETE CASCADE,
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          tipo text NOT NULL DEFAULT 'reciente'
            CHECK (tipo IN ('destacado', 'reciente', 'popular', 'preguntas')),
          titulo text NOT NULL CHECK (length(trim(titulo)) > 0),
          texto text NOT NULL CHECK (length(trim(texto)) > 0),
          etiqueta text,
          likes integer NOT NULL DEFAULT 0,
          guardados integer NOT NULL DEFAULT 0,
          fijada boolean NOT NULL DEFAULT false,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
        )
      `);
      await pool.query('ALTER TABLE comunidad_publicaciones ADD COLUMN IF NOT EXISTS likes integer NOT NULL DEFAULT 0');
      await pool.query('ALTER TABLE comunidad_publicaciones ADD COLUMN IF NOT EXISTS guardados integer NOT NULL DEFAULT 0');
      await pool.query('ALTER TABLE comunidad_publicaciones ADD COLUMN IF NOT EXISTS fijada boolean NOT NULL DEFAULT false');
      await pool.query("ALTER TABLE comunidad_publicaciones ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())");

      await pool.query(`
        CREATE TABLE IF NOT EXISTS comunidad_publicacion_likes (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          publicacion_id bigint NOT NULL REFERENCES comunidad_publicaciones(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT comunidad_publicacion_likes_pkey PRIMARY KEY (user_id, publicacion_id)
        )
      `);

      await pool.query(`
        CREATE TABLE IF NOT EXISTS comunidad_publicacion_guardados (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          publicacion_id bigint NOT NULL REFERENCES comunidad_publicaciones(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT comunidad_publicacion_guardados_pkey PRIMARY KEY (user_id, publicacion_id)
        )
      `);

      await pool.query(`
        CREATE TABLE IF NOT EXISTS comunidad_comentarios (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          publicacion_id bigint NOT NULL REFERENCES comunidad_publicaciones(id) ON DELETE CASCADE,
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          parent_id bigint REFERENCES comunidad_comentarios(id) ON DELETE CASCADE,
          texto text NOT NULL CHECK (length(trim(texto)) > 0),
          likes integer NOT NULL DEFAULT 0,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
        )
      `);
      await pool.query('ALTER TABLE comunidad_comentarios ADD COLUMN IF NOT EXISTS likes integer NOT NULL DEFAULT 0');
      await pool.query('ALTER TABLE comunidad_comentarios ADD COLUMN IF NOT EXISTS responde_a text');

      await pool.query(`
        CREATE TABLE IF NOT EXISTS comunidad_comentario_likes (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          comentario_id bigint NOT NULL REFERENCES comunidad_comentarios(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT comunidad_comentario_likes_pkey PRIMARY KEY (user_id, comentario_id)
        )
      `);

      await pool.query('CREATE INDEX IF NOT EXISTS idx_comunidad_publicaciones_comunidad ON comunidad_publicaciones(comunidad_id, created_at DESC)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_comunidad_publicaciones_user ON comunidad_publicaciones(user_id)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_comunidad_publicacion_likes_publicacion ON comunidad_publicacion_likes(publicacion_id)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_comunidad_publicacion_guardados_publicacion ON comunidad_publicacion_guardados(publicacion_id)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_comunidad_comentarios_publicacion ON comunidad_comentarios(publicacion_id, created_at ASC)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_comunidad_comentarios_parent ON comunidad_comentarios(parent_id)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_comunidad_comentario_likes_comentario ON comunidad_comentario_likes(comentario_id)');

      for (const comunidad of COMUNIDADES_GENERO) {
        await pool.query(
          `INSERT INTO comunidades (id, nombre, titulo, genero, descripcion, portada_url)
           VALUES ($1, $2, $3, $4, $5, $6)
           ON CONFLICT (id) DO UPDATE
           SET nombre = EXCLUDED.nombre,
               titulo = EXCLUDED.titulo,
               genero = EXCLUDED.genero,
               descripcion = EXCLUDED.descripcion,
               portada_url = EXCLUDED.portada_url,
               activa = true`,
          [
            comunidad.id,
            comunidad.nombre,
            comunidad.titulo,
            comunidad.genero,
            comunidad.descripcion,
            comunidad.portada,
          ]
        );
      }
    })().catch((error) => {
      esquemaComunidadesListo = null;
      throw error;
    });
  }

  return esquemaComunidadesListo;
}

function tiempoRelativo(fecha) {
  const valor = new Date(fecha);
  if (Number.isNaN(valor.getTime())) return '';

  const segundos = Math.max(0, Math.floor((Date.now() - valor.getTime()) / 1000));
  if (segundos < 60) return 'ahora';
  const minutos = Math.floor(segundos / 60);
  if (minutos < 60) return `hace ${minutos} min`;
  const horas = Math.floor(minutos / 60);
  if (horas < 24) return `hace ${horas} h`;
  const dias = Math.floor(horas / 24);
  return `hace ${dias} d`;
}

function usuarioVisible(row) {
  const username = row.username || row.email?.split('@')[0] || 'usuario';
  return `@${String(username).replace(/^@/, '')}`;
}

function mapearComunidad(row) {
  return {
    id: row.id,
    nombre: row.nombre,
    titulo: row.titulo,
    genero: row.genero,
    descripcion: row.descripcion,
    categoria: row.genero,
    miembros: Number(row.miembros || 0),
    publicaciones: Number(row.publicaciones || 0),
    actividad: Number(row.publicaciones || 0) > 0
      ? `${Number(row.publicaciones)} publicaciones`
      : 'Sin publicaciones todavia',
    portada: row.portada_url,
  };
}

function mapearComentario(row) {
  return {
    id: Number(row.id),
    publicacionId: Number(row.publicacion_id),
    userId: row.user_id,
    autor: row.username || row.email?.split('@')[0] || 'Usuario SONDAR',
    usuario: usuarioVisible(row),
    texto: row.texto,
    votos: Number(row.likes || 0),
    likes: Number(row.likes || 0),
    liked: Boolean(row.liked),
    parentId: row.parent_id ? Number(row.parent_id) : null,
    respondeA: row.responde_a || '',
    tiempo: tiempoRelativo(row.created_at),
    respuestas: [],
  };
}

function anidarComentarios(rows) {
  const porId = new Map();
  const principales = [];

  rows.forEach((row) => {
    const comentario = mapearComentario(row);
    porId.set(String(comentario.id), comentario);
  });

  porId.forEach((comentario) => {
    if (comentario.parentId) {
      const padre = porId.get(String(comentario.parentId));
      if (padre) {
        padre.respuestas.push(comentario);
        return;
      }
    }

    principales.push(comentario);
  });

  return principales;
}

function mapearPublicacion(row, comentarios = []) {
  return {
    id: Number(row.id),
    comunidadId: row.comunidad_id,
    userId: row.user_id,
    op: row.username || row.email?.split('@')[0] || 'Usuario SONDAR',
    usuario: usuarioVisible(row),
    tipo: row.tipo,
    titulo: row.titulo,
    texto: row.texto,
    etiqueta: row.etiqueta || row.genero,
    votos: Number(row.likes || 0),
    likes: Number(row.likes || 0),
    liked: Boolean(row.liked),
    guardado: Boolean(row.guardado),
    comentarios,
    comentariosTotal: Number(row.comentarios_total || comentarios.length),
    tiempo: tiempoRelativo(row.created_at),
  };
}

async function listarComentariosPublicaciones(publicacionIds, viewerId) {
  if (publicacionIds.length === 0) return new Map();

  const result = await pool.query(
    `SELECT
       cc.*,
       u.username,
       u.email,
       EXISTS (
         SELECT 1
         FROM comunidad_comentario_likes ccl
         WHERE ccl.comentario_id = cc.id
           AND ccl.user_id = $2
       ) AS liked
     FROM comunidad_comentarios cc
     LEFT JOIN users u ON u.id = cc.user_id
     WHERE cc.publicacion_id = ANY($1::bigint[])
     ORDER BY cc.created_at ASC, cc.id ASC`,
    [publicacionIds, viewerId]
  );

  const porPublicacion = new Map();
  publicacionIds.forEach((id) => porPublicacion.set(String(id), []));

  result.rows.forEach((row) => {
    const key = String(row.publicacion_id);
    porPublicacion.set(key, [...(porPublicacion.get(key) || []), row]);
  });

  const anidados = new Map();
  porPublicacion.forEach((rows, key) => {
    anidados.set(key, anidarComentarios(rows));
  });

  return anidados;
}

const comunidadController = {
  listarComunidades: async (req, res) => {
    try {
      await asegurarEsquemaComunidades();

      const result = await pool.query(`
        SELECT
          c.*,
          COUNT(DISTINCT cp.id) AS publicaciones,
          COUNT(DISTINCT cp.user_id) AS miembros
        FROM comunidades c
        LEFT JOIN comunidad_publicaciones cp ON cp.comunidad_id = c.id
        WHERE c.activa = true
        GROUP BY c.id
        ORDER BY array_position($1::text[], c.id)
      `, [COMUNIDADES_GENERO.map((comunidad) => comunidad.id)]);

      res.json(result.rows.map(mapearComunidad));
    } catch (error) {
      console.error('Error al listar comunidades:', error);
      res.status(500).json({ error: 'No se pudieron cargar las comunidades.' });
    }
  },

  listarPublicaciones: async (req, res) => {
    const { comunidadId } = req.params;
    const filtro = req.query.filtro || 'destacado';
    const busqueda = `${req.query.q || ''}`.trim().toLowerCase();

    try {
      await asegurarEsquemaComunidades();
      const viewerId = await obtenerViewerId(req);
      const params = [comunidadId, viewerId];
      const condiciones = ['cp.comunidad_id = $1'];

      if (filtro !== 'destacado') {
        params.push(filtro);
        condiciones.push(`cp.tipo = $${params.length}`);
      }

      if (busqueda) {
        params.push(`%${busqueda}%`);
        condiciones.push(`(
          lower(cp.titulo) LIKE $${params.length}
          OR lower(cp.texto) LIKE $${params.length}
          OR lower(COALESCE(cp.etiqueta, '')) LIKE $${params.length}
          OR lower(COALESCE(u.username, '')) LIKE $${params.length}
        )`);
      }

      const orderBy = filtro === 'popular'
        ? 'cp.likes DESC, cp.created_at DESC, cp.id DESC'
        : 'cp.fijada DESC, cp.created_at DESC, cp.id DESC';

      const result = await pool.query(
        `SELECT
           cp.*,
           c.genero,
           u.username,
           u.email,
           EXISTS (
             SELECT 1
             FROM comunidad_publicacion_likes cpl
             WHERE cpl.publicacion_id = cp.id
               AND cpl.user_id = $2
           ) AS liked,
           EXISTS (
             SELECT 1
             FROM comunidad_publicacion_guardados cpg
             WHERE cpg.publicacion_id = cp.id
               AND cpg.user_id = $2
           ) AS guardado,
           (
             SELECT COUNT(*)::int
             FROM comunidad_comentarios cc
             WHERE cc.publicacion_id = cp.id
           ) AS comentarios_total
         FROM comunidad_publicaciones cp
         JOIN comunidades c ON c.id = cp.comunidad_id
         LEFT JOIN users u ON u.id = cp.user_id
         WHERE ${condiciones.join(' AND ')}
         ORDER BY ${orderBy}`,
        params
      );

      const ids = result.rows.map((row) => row.id);
      const comentariosPorPublicacion = await listarComentariosPublicaciones(ids, viewerId);

      res.json(result.rows.map((row) => mapearPublicacion(
        row,
        comentariosPorPublicacion.get(String(row.id)) || []
      )));
    } catch (error) {
      console.error('Error al listar publicaciones de comunidad:', error);
      res.status(500).json({ error: 'No se pudieron cargar las publicaciones.' });
    }
  },

  crearPublicacion: async (req, res) => {
    const { comunidadId } = req.params;
    const titulo = req.body.titulo?.trim();
    const texto = req.body.texto?.trim();
    const tipo = req.body.tipo || 'reciente';
    const etiqueta = req.body.etiqueta?.trim() || null;

    if (!titulo || !texto) {
      return res.status(400).json({ error: 'Completa titulo y texto para publicar.' });
    }

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComunidades();

      const comunidad = await pool.query('SELECT id, genero FROM comunidades WHERE id = $1 AND activa = true', [comunidadId]);
      if (comunidad.rowCount === 0) {
        return res.status(404).json({ error: 'Comunidad no encontrada.' });
      }

      const tipoSeguro = ['destacado', 'reciente', 'popular', 'preguntas'].includes(tipo) ? tipo : 'reciente';
      const result = await pool.query(
        `INSERT INTO comunidad_publicaciones (comunidad_id, user_id, tipo, titulo, texto, etiqueta)
         VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING *`,
        [comunidadId, req.user.id, tipoSeguro, titulo, texto, etiqueta || comunidad.rows[0].genero]
      );

      const usuarioResult = await pool.query(
        `SELECT u.username, u.email
         FROM users u
         WHERE u.id = $1`,
        [req.user.id]
      );

      const actorName = nombreActor(req.user);
      await notificarSeguidores({
        actorId: req.user.id,
        type: 'new_community_post',
        title: `${actorName} publico en una comunidad`,
        body: titulo,
        targetUrl: `/comunidad?comunidad=${comunidadId}&publicacion=${result.rows[0].id}`,
        entityType: 'community_post',
        entityId: result.rows[0].id,
        uniquePrefix: `new-community-post:${result.rows[0].id}`,
      });
      await notificarMenciones({
        texto,
        actorId: req.user.id,
        actorName,
        targetUrl: `/comunidad?comunidad=${comunidadId}&publicacion=${result.rows[0].id}`,
        entityType: 'community_post',
        entityId: result.rows[0].id,
      });

      res.status(201).json(mapearPublicacion({
        ...result.rows[0],
        genero: comunidad.rows[0].genero,
        username: usuarioResult.rows[0]?.username,
        email: usuarioResult.rows[0]?.email || req.user.email,
        liked: false,
        guardado: false,
        comentarios_total: 0,
      }, []));
    } catch (error) {
      console.error('Error al crear publicacion de comunidad:', error);
      res.status(500).json({ error: 'No se pudo publicar en la comunidad.' });
    }
  },

  crearComentario: async (req, res) => {
    const { publicacionId } = req.params;
    const texto = req.body.texto?.trim();
    const parentId = req.body.parentId || null;
    const respondeA = req.body.respondeA?.trim() || null;

    if (!texto) {
      return res.status(400).json({ error: 'El comentario no puede estar vacio.' });
    }

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComunidades();

      const publicacion = await pool.query(
        'SELECT id, user_id, titulo, comunidad_id FROM comunidad_publicaciones WHERE id = $1',
        [publicacionId]
      );
      if (publicacion.rowCount === 0) {
        return res.status(404).json({ error: 'Publicacion no encontrada.' });
      }

      const result = await pool.query(
        `INSERT INTO comunidad_comentarios (publicacion_id, user_id, parent_id, texto, responde_a)
         VALUES ($1, $2, $3, $4, $5)
         RETURNING *`,
        [publicacionId, req.user.id, parentId, texto, parentId ? respondeA : null]
      );

      const usuarioResult = await pool.query(
        `SELECT u.username, u.email
         FROM users u
         WHERE u.id = $1`,
        [req.user.id]
      );

      const parentResult = parentId
        ? await pool.query('SELECT user_id FROM comunidad_comentarios WHERE id = $1', [parentId])
        : { rows: [] };
      const receptorId = parentId
        ? parentResult.rows[0]?.user_id
        : publicacion.rows[0].user_id;
      const actorName = nombreActor(req.user);
      const targetUrl = `/comunidad?comunidad=${publicacion.rows[0].comunidad_id}&publicacion=${publicacionId}`;
      await crearNotificacion({
        userId: receptorId,
        actorId: req.user.id,
        type: parentId ? 'community_reply' : 'community_comment',
        title: parentId ? `${actorName} respondio tu comentario` : `${actorName} comento tu publicacion`,
        body: texto,
        targetUrl,
        entityType: 'community_comment',
        entityId: result.rows[0].id,
        uniqueKey: `community-comment:${result.rows[0].id}:${receptorId}`,
      });
      await notificarMenciones({
        texto,
        actorId: req.user.id,
        actorName,
        targetUrl,
        entityType: 'community_comment',
        entityId: result.rows[0].id,
      });

      res.status(201).json(mapearComentario({
        ...result.rows[0],
        username: usuarioResult.rows[0]?.username,
        email: usuarioResult.rows[0]?.email || req.user.email,
        liked: false,
      }));
    } catch (error) {
      console.error('Error al comentar publicacion de comunidad:', error);
      res.status(500).json({ error: 'No se pudo guardar el comentario.' });
    }
  },

  eliminarComentario: async (req, res) => {
    const { comentarioId } = req.params;

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComunidades();

      const result = await pool.query(
        `DELETE FROM comunidad_comentarios
         WHERE id = $1 AND user_id = $2
         RETURNING id, publicacion_id, parent_id`,
        [comentarioId, req.user.id]
      );

      if (result.rowCount === 0) {
        return res.status(404).json({ error: 'Comentario no encontrado o sin permiso para eliminarlo.' });
      }

      res.json({
        ok: true,
        id: Number(result.rows[0].id),
        publicacionId: Number(result.rows[0].publicacion_id),
        parentId: result.rows[0].parent_id ? Number(result.rows[0].parent_id) : null,
      });
    } catch (error) {
      console.error('Error al eliminar comentario de comunidad:', error);
      res.status(500).json({ error: 'No se pudo eliminar el comentario.' });
    }
  },

  alternarLikePublicacion: async (req, res) => {
    const { publicacionId } = req.params;
    const client = await pool.connect();

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComunidades();
      await client.query('BEGIN');

      const publicacion = await client.query(
        'SELECT id, user_id, titulo, comunidad_id FROM comunidad_publicaciones WHERE id = $1',
        [publicacionId]
      );
      if (publicacion.rowCount === 0) {
        await client.query('ROLLBACK');
        return res.status(404).json({ error: 'Publicacion no encontrada.' });
      }

      const existe = await client.query(
        'SELECT 1 FROM comunidad_publicacion_likes WHERE user_id = $1 AND publicacion_id = $2',
        [req.user.id, publicacionId]
      );

      let liked = false;
      if (existe.rowCount > 0) {
        await client.query(
          'DELETE FROM comunidad_publicacion_likes WHERE user_id = $1 AND publicacion_id = $2',
          [req.user.id, publicacionId]
        );
        await client.query('UPDATE comunidad_publicaciones SET likes = GREATEST(0, likes - 1) WHERE id = $1', [publicacionId]);
      } else {
        await client.query(
          'INSERT INTO comunidad_publicacion_likes (user_id, publicacion_id) VALUES ($1, $2)',
          [req.user.id, publicacionId]
        );
        await client.query('UPDATE comunidad_publicaciones SET likes = likes + 1 WHERE id = $1', [publicacionId]);
        liked = true;
        await crearNotificacion({
          userId: publicacion.rows[0].user_id,
          actorId: req.user.id,
          type: 'community_like',
          title: `${nombreActor(req.user)} indico que le gusta tu publicacion`,
          body: publicacion.rows[0].titulo || '',
          targetUrl: `/comunidad?comunidad=${publicacion.rows[0].comunidad_id}&publicacion=${publicacionId}`,
          entityType: 'community_post',
          entityId: publicacionId,
          uniqueKey: `community-like:${req.user.id}:${publicacionId}`,
        }, client);
      }

      if (!liked) {
        await eliminarNotificacion(`community-like:${req.user.id}:${publicacionId}`, client);
      }

      const counts = await client.query('SELECT likes FROM comunidad_publicaciones WHERE id = $1', [publicacionId]);
      await client.query('COMMIT');

      res.json({
        id: Number(publicacionId),
        liked,
        likes: Number(counts.rows[0]?.likes || 0),
        votos: Number(counts.rows[0]?.likes || 0),
      });
    } catch (error) {
      await client.query('ROLLBACK').catch(() => null);
      console.error('Error al alternar like de publicacion:', error);
      res.status(500).json({ error: 'No se pudo actualizar el me gusta.' });
    } finally {
      client.release();
    }
  },

  alternarGuardadoPublicacion: async (req, res) => {
    const { publicacionId } = req.params;
    const client = await pool.connect();

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComunidades();
      await client.query('BEGIN');

      const publicacion = await client.query('SELECT id FROM comunidad_publicaciones WHERE id = $1', [publicacionId]);
      if (publicacion.rowCount === 0) {
        await client.query('ROLLBACK');
        return res.status(404).json({ error: 'Publicacion no encontrada.' });
      }

      const existe = await client.query(
        'SELECT 1 FROM comunidad_publicacion_guardados WHERE user_id = $1 AND publicacion_id = $2',
        [req.user.id, publicacionId]
      );

      let guardado = false;
      if (existe.rowCount > 0) {
        await client.query(
          'DELETE FROM comunidad_publicacion_guardados WHERE user_id = $1 AND publicacion_id = $2',
          [req.user.id, publicacionId]
        );
        await client.query('UPDATE comunidad_publicaciones SET guardados = GREATEST(0, guardados - 1) WHERE id = $1', [publicacionId]);
      } else {
        await client.query(
          'INSERT INTO comunidad_publicacion_guardados (user_id, publicacion_id) VALUES ($1, $2)',
          [req.user.id, publicacionId]
        );
        await client.query('UPDATE comunidad_publicaciones SET guardados = guardados + 1 WHERE id = $1', [publicacionId]);
        guardado = true;
      }

      const counts = await client.query('SELECT guardados FROM comunidad_publicaciones WHERE id = $1', [publicacionId]);
      await client.query('COMMIT');

      res.json({
        id: Number(publicacionId),
        guardado,
        guardados: Number(counts.rows[0]?.guardados || 0),
      });
    } catch (error) {
      await client.query('ROLLBACK').catch(() => null);
      console.error('Error al alternar guardado de publicacion:', error);
      res.status(500).json({ error: 'No se pudo actualizar el guardado.' });
    } finally {
      client.release();
    }
  },

  alternarLikeComentario: async (req, res) => {
    const { comentarioId } = req.params;
    const client = await pool.connect();

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComunidades();
      await client.query('BEGIN');

      const comentario = await client.query(
        `SELECT cc.id, cc.user_id, cc.texto, cc.publicacion_id, cp.comunidad_id
         FROM comunidad_comentarios cc
         JOIN comunidad_publicaciones cp ON cp.id = cc.publicacion_id
         WHERE cc.id = $1`,
        [comentarioId]
      );
      if (comentario.rowCount === 0) {
        await client.query('ROLLBACK');
        return res.status(404).json({ error: 'Comentario no encontrado.' });
      }

      const existe = await client.query(
        'SELECT 1 FROM comunidad_comentario_likes WHERE user_id = $1 AND comentario_id = $2',
        [req.user.id, comentarioId]
      );

      let liked = false;
      if (existe.rowCount > 0) {
        await client.query(
          'DELETE FROM comunidad_comentario_likes WHERE user_id = $1 AND comentario_id = $2',
          [req.user.id, comentarioId]
        );
        await client.query('UPDATE comunidad_comentarios SET likes = GREATEST(0, likes - 1) WHERE id = $1', [comentarioId]);
      } else {
        await client.query(
          'INSERT INTO comunidad_comentario_likes (user_id, comentario_id) VALUES ($1, $2)',
          [req.user.id, comentarioId]
        );
        await client.query('UPDATE comunidad_comentarios SET likes = likes + 1 WHERE id = $1', [comentarioId]);
        liked = true;
        await crearNotificacion({
          userId: comentario.rows[0].user_id,
          actorId: req.user.id,
          type: 'community_comment_like',
          title: `${nombreActor(req.user)} indico que le gusta tu comentario`,
          body: comentario.rows[0].texto || '',
          targetUrl: `/comunidad?comunidad=${comentario.rows[0].comunidad_id}&publicacion=${comentario.rows[0].publicacion_id}`,
          entityType: 'community_comment',
          entityId: comentarioId,
          uniqueKey: `community-comment-like:${req.user.id}:${comentarioId}`,
        }, client);
      }

      if (!liked) {
        await eliminarNotificacion(`community-comment-like:${req.user.id}:${comentarioId}`, client);
      }

      const counts = await client.query('SELECT likes FROM comunidad_comentarios WHERE id = $1', [comentarioId]);
      await client.query('COMMIT');

      res.json({
        id: Number(comentarioId),
        liked,
        likes: Number(counts.rows[0]?.likes || 0),
        votos: Number(counts.rows[0]?.likes || 0),
      });
    } catch (error) {
      await client.query('ROLLBACK').catch(() => null);
      console.error('Error al alternar like de comentario de comunidad:', error);
      res.status(500).json({ error: 'No se pudo actualizar el me gusta.' });
    } finally {
      client.release();
    }
  },
};

module.exports = comunidadController;
