const pool = require('../Pool_DB');
const supabase = require('../services/supabaseClient');
const supabaseAuth = supabase.authClient || supabase;
const { subirImagenEvento, eliminarImagenEvento } = require('../services/storageService');
const {
  crearNotificacion,
  nombreActor,
  notificarSeguidores,
} = require('../services/notificationService');
const { asegurarEsquemaModeracion, registrarDenuncia } = require('../services/moderationService');

let esquemaEventosListo = null;

async function asegurarEsquemaEventos() {
  if (!esquemaEventosListo) {
    esquemaEventosListo = (async () => {
      await pool.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name text');
      await pool.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS artist_name text');
      await pool.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_img_url text');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS eventos (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          titulo text NOT NULL,
          descripcion text,
          genero text,
          lugar text,
          fecha timestamp with time zone NOT NULL,
          img_url text,
          img_path text,
          precio numeric(12, 2),
          link text,
          creador_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          latitud double precision,
          longitud double precision,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
        )
      `);
      await pool.query('ALTER TABLE eventos ADD COLUMN IF NOT EXISTS descripcion text');
      await pool.query('ALTER TABLE eventos ADD COLUMN IF NOT EXISTS img_path text');
      await pool.query('ALTER TABLE eventos ADD COLUMN IF NOT EXISTS precio numeric(12, 2)');
      await pool.query('ALTER TABLE eventos ADD COLUMN IF NOT EXISTS link text');
      await pool.query('ALTER TABLE eventos ADD COLUMN IF NOT EXISTS latitud double precision');
      await pool.query('ALTER TABLE eventos ADD COLUMN IF NOT EXISTS longitud double precision');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS event_organizers (
          event_id bigint NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          added_by uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
          CONSTRAINT event_organizers_pkey PRIMARY KEY (event_id, user_id)
        )
      `);
      await pool.query('CREATE INDEX IF NOT EXISTS event_organizers_user_id_idx ON event_organizers(user_id)');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS event_saves (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          event_id bigint NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT event_saves_pkey PRIMARY KEY (user_id, event_id)
        )
      `);
      await pool.query('CREATE INDEX IF NOT EXISTS idx_event_saves_event_id ON event_saves(event_id)');
    })().catch((error) => {
      esquemaEventosListo = null;
      throw error;
    });
  }

  return esquemaEventosListo;
}

async function obtenerViewerId(req) {
  const authorization = req.headers.authorization || '';
  const token = authorization.startsWith('Bearer ')
    ? authorization.slice('Bearer '.length)
    : '';

  if (!token) return null;

  const { data, error } = await supabaseAuth.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user.id;
}

async function buscarAccesoEvento(eventoId) {
  const result = await pool.query(
    'SELECT id FROM eventos WHERE id = $1',
    [eventoId]
  );
  return result.rows[0] || null;
}

async function obtenerGenerosPreferidos(viewerId) {
  if (!viewerId) return [];

  try {
    const result = await pool.query(
      `SELECT genero
       FROM user_genre_preferences
       WHERE user_id = $1
       ORDER BY peso DESC, created_at ASC`,
      [viewerId]
    );
    return result.rows.map((row) => String(row.genero || '').toLowerCase()).filter(Boolean);
  } catch (error) {
    if (error.code === '42P01' || error.code === '42703') return [];
    throw error;
  }
}

function mapearEvento(evento) {
  if (!evento) return evento;

  return {
    ...evento,
    img: evento.img_url || null,
    creador: evento.creador || null
  };
}

function mapearPreviewEvento(reel) {
  return {
    id: reel.id,
    backendId: reel.id,
    artista: reel.creador_nombre || reel.creador_email?.split('@')[0] || 'Artista SONDAR',
    usuario: reel.creador_nombre
      ? `@${String(reel.creador_nombre).replace(/^@/, '')}`
      : '@artista',
    tema: reel.titulo,
    album: reel.album,
    genero: reel.genero,
    descripcion: reel.descripcion || '',
    duracion: reel.duracion || '0:30',
    portada: reel.portada_url || '',
    audio: reel.audio_url || '',
    avatar: reel.creador_avatar || '',
    likes: Number(reel.likes || 0),
    comentarios: Number(reel.comentarios_total || 0),
    compartidos: Number(reel.compartidos || 0),
    guardados: Number(reel.guardados || 0),
    visitas: Number(reel.visitas || 0),
    colorAmbiente: reel.color_ambiente || '#8F5136',
    fragmentStart: Number(reel.fragment_start || 0),
    fragmentEnd: reel.fragment_end === null || reel.fragment_end === undefined
      ? null
      : Number(reel.fragment_end),
    liked: false,
    guardado: false,
    siguiendo: false,
    creadorId: reel.creador_id,
  };
}

async function obtenerPreviewsPorEvento(eventos, viewerId) {
  if (!Array.isArray(eventos) || eventos.length === 0) return new Map();

  const eventoIds = eventos.map((evento) => evento.id);
  const result = await pool.query(`
    WITH participantes AS (
      SELECT e.id AS evento_id, e.creador_id AS usuario_id
      FROM eventos e
      WHERE e.id = ANY($1::bigint[])

      UNION

      SELECT eo.event_id AS evento_id, eo.user_id AS usuario_id
      FROM event_organizers eo
      WHERE eo.event_id = ANY($1::bigint[])
    )
    SELECT
      participantes.evento_id,
      r.*,
      COALESCE(u.username, u.artist_name, u.full_name, u.email) AS creador_nombre,
      u.email AS creador_email,
      u.profile_img_url AS creador_avatar
    FROM participantes
    JOIN reels r ON r.creador_id = participantes.usuario_id
    LEFT JOIN users u ON u.id = r.creador_id
    WHERE $2::uuid IS NULL OR NOT EXISTS (
      SELECT 1 FROM user_blocks ub
      WHERE (ub.blocker_id = $2 AND ub.blocked_id = r.creador_id)
         OR (ub.blocker_id = r.creador_id AND ub.blocked_id = $2)
    )
    ORDER BY participantes.evento_id, r.created_at DESC, r.id DESC
  `, [eventoIds, viewerId]);

  const previewsPorEvento = new Map(eventoIds.map((id) => [String(id), []]));
  for (const reel of result.rows) {
    previewsPorEvento.get(String(reel.evento_id))?.push(mapearPreviewEvento(reel));
  }
  return previewsPorEvento;
}

async function asegurarUsuarioPublico(user) {
  const email = user.email || `${user.id}@sin-email.local`;
  const baseUsername =
    user.user_metadata?.username ||
    user.user_metadata?.name ||
    email.split('@')[0] ||
    'usuario';
  const username = `${baseUsername}`.trim().toLowerCase().replace(/^@+/, '').replace(/[^a-z0-9._-]/g, '').slice(0, 21) || 'usuario';
  const usernameSeguro = `${username}_${user.id.slice(0, 8)}`;

  await pool.query(
    `INSERT INTO users (id, email, username, user_type)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (id) DO UPDATE
     SET email = EXCLUDED.email
     RETURNING id`,
    [user.id, email, usernameSeguro, process.env.DEFAULT_USER_TYPE || 'musico']
  );
}

const eventoController = {
  listarEventos: async (req, res) => {
    try {
      await asegurarEsquemaModeracion();
      await asegurarEsquemaEventos();
      const viewerId = await obtenerViewerId(req);
      const generosPreferidos = await obtenerGenerosPreferidos(viewerId);
      const result = await pool.query(`
        SELECT
          e.*,
          e.img_url AS img,
          COALESCE(u.username, u.full_name, u.artist_name, 'Anonimo') AS creador,
          u.profile_img_url AS avatar,
          COALESCE(org.organizadores, '[]'::jsonb) AS organizadores
        FROM eventos e
        LEFT JOIN users u ON u.id = e.creador_id
        LEFT JOIN LATERAL (
          SELECT jsonb_agg(
            jsonb_build_object(
              'id', co.id,
              'username', co.username,
              'nombre', COALESCE(co.artist_name, co.full_name, co.username),
              'avatar', COALESCE(co.profile_img_url, '')
            )
            ORDER BY eo.created_at
          ) AS organizadores
          FROM event_organizers eo
          JOIN users co ON co.id = eo.user_id
          WHERE eo.event_id = e.id
        ) org ON true
        WHERE $1::uuid IS NULL OR NOT EXISTS (
          SELECT 1 FROM user_blocks ub
          WHERE (ub.blocker_id = $1 AND ub.blocked_id = e.creador_id)
             OR (ub.blocker_id = e.creador_id AND ub.blocked_id = $1)
        )
        ORDER BY
          CASE
            WHEN cardinality($2::text[]) > 0 AND lower(COALESCE(e.genero, '')) = ANY($2::text[]) THEN 0
            ELSE 1
          END,
          COALESCE(array_position($2::text[], lower(COALESCE(e.genero, ''))), 999),
          e.id DESC
      `, [viewerId, generosPreferidos]);

      const previewsPorEvento = await obtenerPreviewsPorEvento(result.rows, viewerId);
      const eventosConPreviews = result.rows.map((evento) => ({
        ...evento,
        previews: previewsPorEvento.get(String(evento.id)) || [],
      }));

      if (!viewerId || eventosConPreviews.length === 0) {
        return res.json(eventosConPreviews);
      }

      try {
        const guardados = await pool.query(
          'SELECT event_id FROM event_saves WHERE user_id = $1 AND event_id = ANY($2::bigint[])',
          [viewerId, eventosConPreviews.map((evento) => evento.id)]
        );
        const guardadoSet = new Set(guardados.rows.map((row) => String(row.event_id)));

        return res.json(eventosConPreviews.map((evento) => ({
          ...evento,
          guardado: guardadoSet.has(String(evento.id)),
        })));
      } catch (error) {
        if (error.code !== '42P01') throw error;
        return res.json(eventosConPreviews);
      }
    } catch (error) {
      console.error('Error al listar eventos:', error);
      res.status(500).json({ error: 'Error al obtener los eventos.' });
    }
  },

  denunciarEvento: async (req, res) => {
    const { id } = req.params;
    try {
      const result = await pool.query('SELECT id, creador_id FROM eventos WHERE id = $1', [id]);
      const evento = result.rows[0];
      if (!evento) return res.status(404).json({ error: 'Evento no encontrado.' });
      const resultado = await registrarDenuncia({
        reporterId: req.user.id,
        reportedUserId: evento.creador_id,
        contentType: 'evento',
        contentId: id,
        reason: req.body?.reason,
        details: req.body?.detail,
      });
      res.json(resultado);
    } catch (error) {
      console.error('Error al denunciar evento:', error);
      res.status(error.status || 500).json({ error: error.message || 'No se pudo denunciar el evento.' });
    }
  },

  crearEvento: async (req, res) => {
    const { titulo, descripcion, genero, ubicacion, fecha, precio, link, latitud, longitud, organizadores } = req.body;
    const creadorId = req.user.id;
    let imagenSubida = null;
    let dbClient = null;
    let transaccionActiva = false;

    const creadorNombre =
      req.user?.user_metadata?.name ||
      req.user?.user_metadata?.username ||
      req.user?.email?.split('@')[0] ||
      'Anonimo';


    if (!titulo || !genero || !ubicacion || !fecha || !latitud || !longitud) {
      return res.status(400).json({ error: 'Faltan datos obligatorios del evento.' });
    }

    if (String(descripcion || '').length > 1000) {
      return res.status(400).json({ error: 'La descripcion no puede superar los 1000 caracteres.' });
    }

    let organizadorIds = [];
    try {
      const recibidos = organizadores ? JSON.parse(organizadores) : [];
      if (!Array.isArray(recibidos)) throw new Error('Formato invalido');
      organizadorIds = [...new Set(recibidos
        .map((id) => String(id || '').trim())
        .filter((id) => id && id !== creadorId))];
    } catch {
      return res.status(400).json({ error: 'La lista de organizadores no es valida.' });
    }

    if (organizadorIds.length > 8) {
      return res.status(400).json({ error: 'Podes agregar hasta 8 coorganizadores.' });
    }

    const uuidValido = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    if (organizadorIds.some((id) => !uuidValido.test(id))) {
      return res.status(400).json({ error: 'Hay un organizador invalido.' });
    }

    const precioNormalizado = precio === '' || precio === undefined ? null : Number(precio);

    if (precioNormalizado !== null && (!Number.isFinite(precioNormalizado) || precioNormalizado < 0)) {
      return res.status(400).json({ error: 'El precio de entrada no es valido.' });
    }

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaEventos();

      if (organizadorIds.length > 0) {
        const usuariosValidos = await pool.query(
          'SELECT id FROM users WHERE id = ANY($1::uuid[])',
          [organizadorIds]
        );
        if (usuariosValidos.rowCount !== organizadorIds.length) {
          return res.status(400).json({ error: 'Uno de los coorganizadores ya no esta disponible.' });
        }
      }

      imagenSubida = await subirImagenEvento(req.file, req.user.id, req.accessToken);
      dbClient = await pool.connect();
      await dbClient.query('BEGIN');
      transaccionActiva = true;

      const query = `
        INSERT INTO eventos (titulo, descripcion, genero, lugar, fecha, img_url, img_path, precio, link, creador_id, latitud, longitud)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
        RETURNING *`;

      const values = [
        titulo,
        String(descripcion || '').trim(),
        genero,
        ubicacion,
        fecha,
        imagenSubida?.publicUrl || null,
        imagenSubida?.path || null,
        precioNormalizado,
        link || null,
        creadorId,
        latitud,
        longitud
      ];

      const result = await dbClient.query(query, values);

      if (organizadorIds.length > 0) {
        await dbClient.query(
          `INSERT INTO event_organizers (event_id, user_id, added_by)
           SELECT $1, unnest($2::uuid[]), $3`,
          [result.rows[0].id, organizadorIds, creadorId]
        );
      }

      const organizadoresResult = organizadorIds.length > 0
        ? await dbClient.query(
          `SELECT
             u.id,
             u.username,
             COALESCE(u.artist_name, u.full_name, u.username) AS nombre,
             COALESCE(u.profile_img_url, '') AS avatar
           FROM event_organizers eo
           JOIN users u ON u.id = eo.user_id
           WHERE eo.event_id = $1
           ORDER BY eo.created_at`,
          [result.rows[0].id]
        )
        : { rows: [] };
      await dbClient.query('COMMIT');
      transaccionActiva = false;

      const actorName = nombreActor(req.user);
      await notificarSeguidores({
        actorId: creadorId,
        type: 'new_event',
        title: `${actorName} creo un nuevo evento`,
        body: titulo,
        targetUrl: `/?evento=${result.rows[0].id}`,
        entityType: 'event',
        entityId: result.rows[0].id,
        uniquePrefix: `new-event:${result.rows[0].id}`,
      });

      for (const organizador of organizadoresResult.rows) {
        await crearNotificacion({
          userId: organizador.id,
          actorId: creadorId,
          type: 'event_coorganizer',
          title: `${actorName} te agrego como coorganizador`,
          body: titulo,
          targetUrl: `/?evento=${result.rows[0].id}`,
          entityType: 'event',
          entityId: result.rows[0].id,
          uniqueKey: `event-coorganizer:${result.rows[0].id}:${organizador.id}`,
        });
      }

      let previews = [];
      try {
        const previewsPorEvento = await obtenerPreviewsPorEvento([result.rows[0]], creadorId);
        previews = previewsPorEvento.get(String(result.rows[0].id)) || [];
      } catch (error) {
        console.error('No se pudieron adjuntar los previews al evento creado:', error);
      }

      res.status(201).json(mapearEvento({
        ...result.rows[0],
        creador: creadorNombre,
        organizadores: organizadoresResult.rows,
        previews,
      }));
    } catch (error) {
      if (dbClient && transaccionActiva) await dbClient.query('ROLLBACK').catch(() => {});
      if (imagenSubida?.path) {
        await eliminarImagenEvento(imagenSubida.path, req.accessToken);
      }

      console.error('Error al crear evento:', error);
      res.status(500).json({ error: error.message || 'Error al guardar el evento.' });
    } finally {
      dbClient?.release();
    }
  },

  eliminarEvento: async (req, res) => {
    const { id } = req.params;
    const creadorId = req.user.id;

    try {
      const result = await pool.query(
        'DELETE FROM eventos WHERE id = $1 AND creador_id = $2 RETURNING id, img_path',
        [id, creadorId]
      );

      if (result.rowCount === 0) {
        return res.status(404).json({ error: 'Evento no encontrado o sin permiso para eliminarlo.' });
      }

      await eliminarImagenEvento(result.rows[0].img_path, req.accessToken).catch((error) => {
        console.error('No se pudo eliminar la imagen del evento:', error);
      });

      res.json({ ok: true, id: result.rows[0].id });
    } catch (error) {
      console.error('Error al eliminar evento:', error);
      res.status(500).json({ error: 'No se pudo eliminar el evento.' });
    }
  },

  alternarGuardado: async (req, res) => {
    const { id } = req.params;

    try {
      await asegurarEsquemaEventos();
      await asegurarUsuarioPublico(req.user);

      const evento = await buscarAccesoEvento(id);
      if (!evento) {
        return res.status(404).json({ error: 'Evento no encontrado.' });
      }
      const existe = await pool.query(
        'SELECT 1 FROM event_saves WHERE user_id = $1 AND event_id = $2',
        [req.user.id, id]
      );

      if (existe.rowCount > 0) {
        await pool.query('DELETE FROM event_saves WHERE user_id = $1 AND event_id = $2', [req.user.id, id]);
        return res.json({ guardado: false });
      }

      await pool.query('INSERT INTO event_saves (user_id, event_id) VALUES ($1, $2)', [req.user.id, id]);
      res.json({ guardado: true });
    } catch (error) {
      console.error('Error al alternar guardado de evento:', error);
      res.status(500).json({ error: 'No se pudo actualizar el guardado del evento.' });
    }
  }
};

module.exports = eventoController;
