const pool = require('../Pool_DB');
const supabase = require('../services/supabaseClient');
const supabaseAuth = supabase.authClient || supabase;
const {
  subirPortadaReel,
  subirAudioReel,
  eliminarArchivoReel
} = require('../services/storageService');
const {
  crearNotificacion,
  eliminarNotificacion,
  nombreActor,
  notificarMenciones,
  notificarSeguidores,
} = require('../services/notificationService');
const { asegurarEsquemaModeracion, registrarDenuncia } = require('../services/moderationService');

let esquemaComentariosListo = null;
let esquemaCompartidosListo = null;
let esquemaVisitasListo = null;
let esquemaInteraccionesListo = null;

async function obtenerViewerId(req) {
  const authorization = req.headers.authorization || '';
  const token = authorization.startsWith('Bearer ')
    ? authorization.slice('Bearer '.length)
    : '';

  if (!token) return null;

  const { data, error } = await supabaseAuth.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user.id;
}

async function buscarAccesoReel(reelId, client = pool) {
  const result = await client.query(
    `SELECT
       r.id,
       r.creador_id,
       r.titulo
     FROM reels r
     WHERE r.id = $1`,
    [reelId]
  );
  return result.rows[0] || null;
}

async function buscarAccesoComentario(comentarioId, client = pool) {
  const result = await client.query(
    `SELECT
       rc.id,
       rc.user_id,
       rc.reel_id,
       rc.texto
     FROM reel_comments rc
     WHERE rc.id = $1`,
    [comentarioId]
  );
  return result.rows[0] || null;
}

async function asegurarUsuarioPublico(user) {
  const email = user.email || `${user.id}@sin-email.local`;
  const baseUsername =
    user.user_metadata?.username ||
    user.user_metadata?.name ||
    email.split('@')[0] ||
    'usuario';
  const username = `${baseUsername}`.trim().toLowerCase().replace(/^@+/, '').replace(/[^a-z0-9._-]/g, '').slice(0, 21) || 'usuario';
  const usernameSeguro = `${username}_${user.id.slice(0, 8)}`;

  await pool.query(
    `INSERT INTO users (id, email, username, user_type)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (id) DO UPDATE
     SET email = EXCLUDED.email
     RETURNING id`,
    [user.id, email, usernameSeguro, process.env.DEFAULT_USER_TYPE || 'musico']
  );
}

async function asegurarEsquemaComentarios() {
  if (!esquemaComentariosListo) {
    esquemaComentariosListo = (async () => {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS reel_comments (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          reel_id bigint NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          parent_id bigint REFERENCES reel_comments(id) ON DELETE CASCADE,
          texto text NOT NULL CHECK (length(trim(texto)) > 0),
          likes integer NOT NULL DEFAULT 0,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
        )
      `);
      await pool.query('ALTER TABLE reel_comments ADD COLUMN IF NOT EXISTS likes integer NOT NULL DEFAULT 0');
      await pool.query('ALTER TABLE reel_comments ADD COLUMN IF NOT EXISTS responde_a text');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS reel_comment_likes (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          comment_id bigint NOT NULL REFERENCES reel_comments(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT reel_comment_likes_pkey PRIMARY KEY (user_id, comment_id)
        )
      `);
      await pool.query(
        'CREATE INDEX IF NOT EXISTS idx_reel_comment_likes_comment_id ON reel_comment_likes(comment_id)'
      );
    })().catch((error) => {
      esquemaComentariosListo = null;
      throw error;
    });
  }

  return esquemaComentariosListo;
}

async function asegurarEsquemaInteracciones() {
  if (!esquemaInteraccionesListo) {
    esquemaInteraccionesListo = (async () => {
      await pool.query('ALTER TABLE reels ADD COLUMN IF NOT EXISTS likes integer NOT NULL DEFAULT 0');
      await pool.query('ALTER TABLE reels ADD COLUMN IF NOT EXISTS guardados integer NOT NULL DEFAULT 0');
      await pool.query('ALTER TABLE reels ADD COLUMN IF NOT EXISTS compartidos integer NOT NULL DEFAULT 0');
      await pool.query('ALTER TABLE reels ADD COLUMN IF NOT EXISTS visitas integer NOT NULL DEFAULT 0');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS reel_likes (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          reel_id bigint NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT reel_likes_pkey PRIMARY KEY (user_id, reel_id)
        )
      `);
      await pool.query(`
        CREATE TABLE IF NOT EXISTS reel_saves (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          reel_id bigint NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT reel_saves_pkey PRIMARY KEY (user_id, reel_id)
        )
      `);
      await pool.query(`
        CREATE TABLE IF NOT EXISTS reel_shares (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          reel_id bigint NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT reel_shares_pkey PRIMARY KEY (user_id, reel_id)
        )
      `);
      await pool.query('CREATE INDEX IF NOT EXISTS idx_reel_likes_reel_id ON reel_likes(reel_id)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_reel_saves_reel_id ON reel_saves(reel_id)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_reel_shares_reel_id ON reel_shares(reel_id)');
      await pool.query(`
        UPDATE reels r
        SET likes = (SELECT COUNT(*)::int FROM reel_likes rl WHERE rl.reel_id = r.id),
            guardados = (SELECT COUNT(*)::int FROM reel_saves rs WHERE rs.reel_id = r.id),
            compartidos = (SELECT COUNT(*)::int FROM reel_shares rsh WHERE rsh.reel_id = r.id)
      `);
    })().catch((error) => {
      esquemaInteraccionesListo = null;
      throw error;
    });
  }

  return esquemaInteraccionesListo;
}

async function asegurarEsquemaCompartidos() {
  if (!esquemaCompartidosListo) {
    esquemaCompartidosListo = (async () => {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS reel_shares (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          reel_id bigint NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
          created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
          CONSTRAINT reel_shares_pkey PRIMARY KEY (user_id, reel_id)
        )
      `);
      await pool.query('CREATE INDEX IF NOT EXISTS idx_reel_shares_reel_id ON reel_shares(reel_id)');
    })().catch((error) => {
      esquemaCompartidosListo = null;
      throw error;
    });
  }

  return esquemaCompartidosListo;
}

async function asegurarEsquemaVisitas() {
  if (!esquemaVisitasListo) {
    esquemaVisitasListo = (async () => {
      await pool.query('ALTER TABLE reels ADD COLUMN IF NOT EXISTS visitas integer NOT NULL DEFAULT 0');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS reel_views (
          user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          reel_id bigint NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
          created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
          CONSTRAINT reel_views_pkey PRIMARY KEY (user_id, reel_id)
        )
      `);
      await pool.query('CREATE INDEX IF NOT EXISTS idx_reel_views_reel_id ON reel_views(reel_id)');
      await pool.query(`
        UPDATE reels r
        SET visitas = (
          SELECT COUNT(*)::int FROM reel_views rv WHERE rv.reel_id = r.id
        )
      `);
    })().catch((error) => {
        esquemaVisitasListo = null;
        throw error;
      });
  }

  return esquemaVisitasListo;
}

function mapearReel(reel) {
  return {
    id: reel.id,
    artista: reel.creador_nombre || reel.creador_email?.split('@')[0] || 'Artista SONDAR',
    usuario: reel.creador_nombre ? `@${String(reel.creador_nombre).replace(/^@/, '')}` : '@artista',
    oyentes: '0',
    tema: reel.titulo,
    album: reel.album,
    genero: reel.genero,
    descripcion: reel.descripcion,
    duracion: reel.duracion || '0:30',
    progreso: 0,
    likes: Number(reel.likes || 0),
    comentarios: Number(reel.comentarios_total || reel.comentarios || 0),
    compartidos: Number(reel.compartidos || 0),
    guardados: Number(reel.guardados || 0),
    visitas: Number(reel.visitas || 0),
    colorA: '#ffae00',
    colorB: '#ff5e00',
    colorC: '#111111',
    portada: reel.portada_url,
    audio: reel.audio_url,
    avatar: reel.creador_avatar || reel.profile_img_url || '',
    liked: false,
    guardado: false,
    siguiendo: false,
    creadorId: reel.creador_id,
    backendId: reel.id,
  };
}

function tiempoRelativo(fecha) {
  const valor = new Date(fecha);
  if (Number.isNaN(valor.getTime())) return '';

  const segundos = Math.max(0, Math.floor((Date.now() - valor.getTime()) / 1000));
  if (segundos < 60) return 'ahora';
  const minutos = Math.floor(segundos / 60);
  if (minutos < 60) return `hace ${minutos} min`;
  const horas = Math.floor(minutos / 60);
  if (horas < 24) return `hace ${horas} h`;
  const dias = Math.floor(horas / 24);
  return `hace ${dias} d`;
}

function mapearComentario(row) {
  const username = row.username || row.email?.split('@')[0] || 'usuario';

  return {
    id: row.id,
    reelId: row.reel_id,
    userId: row.user_id,
    usuario: `@${String(username).replace(/^@/, '')}`,
    avatar: row.profile_img_url || '',
    tiempo: tiempoRelativo(row.created_at),
    texto: row.texto,
    likes: Number(row.likes || 0),
    liked: Boolean(row.liked),
    parentId: row.parent_id,
    respondeA: row.responde_a || '',
    respuestas: [],
  };
}

function anidarComentarios(rows) {
  const porId = new Map();
  const principales = [];

  rows.forEach((row) => {
    const comentario = mapearComentario(row);
    porId.set(String(comentario.id), comentario);
  });

  porId.forEach((comentario) => {
    if (comentario.parentId) {
      const padre = porId.get(String(comentario.parentId));
      if (padre) {
        padre.respuestas.push(comentario);
        return;
      }
    }

    principales.push(comentario);
  });

  return principales;
}

async function consultarSetInteraccion(query, params, campo) {
  try {
    const result = await pool.query(query, params);
    return new Set(result.rows.map((row) => String(row[campo])));
  } catch (error) {
    if (error.code === '42P01') {
      return new Set();
    }

    throw error;
  }
}

const reelController = {
  listarReels: async (req, res) => {
    try {
      await asegurarEsquemaInteracciones();
      await asegurarEsquemaVisitas();
      await asegurarEsquemaComentarios();
      await asegurarEsquemaModeracion();
      const viewerId = await obtenerViewerId(req);
      const result = await pool.query(`
        SELECT
          r.*,
          COALESCE(u.username, u.email) AS creador_nombre,
          u.email AS creador_email,
          u.profile_img_url AS creador_avatar,
          COALESCE((
            SELECT COUNT(*)::int
            FROM reel_comments rc
            WHERE rc.reel_id = r.id
          ), 0) AS comentarios_total
        FROM reels r
        LEFT JOIN users u ON u.id = r.creador_id
        WHERE $1::uuid IS NULL OR NOT EXISTS (
          SELECT 1 FROM user_blocks ub
          WHERE (ub.blocker_id = $1 AND ub.blocked_id = r.creador_id)
             OR (ub.blocker_id = r.creador_id AND ub.blocked_id = $1)
        )
        ORDER BY r.created_at DESC, r.id DESC
      `, [viewerId]);

      if (!viewerId || result.rows.length === 0) {
        return res.json(result.rows.map(mapearReel));
      }

      const reelIds = result.rows.map((reel) => reel.id);
      const creadorIds = [...new Set(result.rows.map((reel) => reel.creador_id).filter(Boolean))];
      const [likedSet, guardadoSet, siguiendoSet] = await Promise.all([
        consultarSetInteraccion(
          'SELECT reel_id FROM reel_likes WHERE user_id = $1 AND reel_id = ANY($2::bigint[])',
          [viewerId, reelIds],
          'reel_id'
        ),
        consultarSetInteraccion(
          'SELECT reel_id FROM reel_saves WHERE user_id = $1 AND reel_id = ANY($2::bigint[])',
          [viewerId, reelIds],
          'reel_id'
        ),
        creadorIds.length > 0
          ? consultarSetInteraccion(
              'SELECT following_id FROM follows WHERE follower_id = $1 AND following_id = ANY($2::uuid[])',
              [viewerId, creadorIds],
              'following_id'
            )
          : Promise.resolve(new Set()),
      ]);

      res.json(result.rows.map((reel) => ({
        ...mapearReel(reel),
        liked: likedSet.has(String(reel.id)),
        guardado: guardadoSet.has(String(reel.id)),
        siguiendo: siguiendoSet.has(String(reel.creador_id)),
      })));
    } catch (error) {
      console.error('Error al listar reels:', error);
      res.status(500).json({ error: 'Error al obtener los reels.' });
    }
  },

  registrarVisita: async (req, res) => {
    const { id } = req.params;
    const client = await pool.connect();

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaVisitas();
      await client.query('BEGIN');
      const reel = await buscarAccesoReel(id, client);
      if (!reel) {
        await client.query('ROLLBACK');
        return res.status(404).json({ error: 'Reel no encontrado.' });
      }
      const visita = await client.query(
        `INSERT INTO reel_views (user_id, reel_id)
         VALUES ($1, $2)
         ON CONFLICT (user_id, reel_id) DO NOTHING
         RETURNING reel_id`,
        [req.user.id, id]
      );
      const result = await client.query(
        `UPDATE reels
         SET visitas = (SELECT COUNT(*)::int FROM reel_views WHERE reel_id = $1)
         WHERE id = $1
         RETURNING visitas`,
        [id]
      );
      await client.query('COMMIT');
      res.json({
        visitas: Number(result.rows[0]?.visitas || 0),
        nuevaVisita: visita.rowCount > 0,
      });
    } catch (error) {
      await client.query('ROLLBACK').catch(() => null);
      console.error('Error al registrar visita de reel:', error);
      res.status(500).json({ error: 'No se pudo registrar la visita.' });
    } finally {
      client.release();
    }
  },

  denunciarReel: async (req, res) => {
    const { id } = req.params;
    try {
      const reel = await buscarAccesoReel(id);
      if (!reel) return res.status(404).json({ error: 'Reel no encontrado.' });
      const resultado = await registrarDenuncia({
        reporterId: req.user.id,
        reportedUserId: reel.creador_id,
        contentType: 'reel',
        contentId: id,
        reason: req.body?.reason,
        details: req.body?.detail,
      });
      res.json(resultado);
    } catch (error) {
      console.error('Error al denunciar reel:', error);
      res.status(error.status || 500).json({ error: error.message || 'No se pudo denunciar el reel.' });
    }
  },

  listarComentarios: async (req, res) => {
    const { id } = req.params;

    try {
      await asegurarEsquemaComentarios();
      const viewerId = await obtenerViewerId(req);
      const acceso = await buscarAccesoReel(id);
      if (!acceso) return res.status(404).json({ error: 'Reel no encontrado.' });
      const result = await pool.query(
        `SELECT
          rc.*,
          u.username,
          u.email,
          u.profile_img_url,
          EXISTS (
            SELECT 1
            FROM reel_comment_likes rcl
            WHERE rcl.comment_id = rc.id
              AND rcl.user_id = $2
          ) AS liked
        FROM reel_comments rc
        LEFT JOIN users u ON u.id = rc.user_id
        WHERE rc.reel_id = $1
        ORDER BY rc.created_at ASC, rc.id ASC`,
        [id, viewerId]
      );

      res.json(anidarComentarios(result.rows));
    } catch (error) {
      if (error.code === '42P01') {
        return res.json([]);
      }

      console.error('Error al listar comentarios:', error);
      res.status(500).json({ error: 'No se pudieron cargar los comentarios.' });
    }
  },

  crearComentario: async (req, res) => {
    const { id } = req.params;
    const { texto, parentId, respondeA } = req.body;
    const textoLimpio = texto?.trim();
    const respondeALimpio = respondeA?.trim() || null;

    if (!textoLimpio) {
      return res.status(400).json({ error: 'El comentario no puede estar vacio.' });
    }

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComentarios();
      const acceso = await buscarAccesoReel(id);
      if (!acceso) return res.status(404).json({ error: 'Reel no encontrado.' });

      const result = await pool.query(
        `INSERT INTO reel_comments (reel_id, user_id, parent_id, texto, responde_a)
         VALUES ($1, $2, $3, $4, $5)
         RETURNING *`,
        [id, req.user.id, parentId || null, textoLimpio, parentId ? respondeALimpio : null]
      );

      const usuarioResult = await pool.query(
        `SELECT u.username, u.email, u.profile_img_url
         FROM users u
         WHERE u.id = $1`,
        [req.user.id]
      );

      const destinoResult = await pool.query(
        `SELECT
           r.creador_id,
           r.titulo,
           padre.user_id AS parent_user_id
         FROM reels r
         LEFT JOIN reel_comments padre ON padre.id = $2
         WHERE r.id = $1`,
        [id, parentId || null]
      );
      const destino = destinoResult.rows[0];
      const usuarioRespondidoResult = parentId && respondeALimpio
        ? await pool.query(
          `SELECT id
           FROM users
           WHERE lower(username) = lower(regexp_replace($1, '^@', ''))
           LIMIT 1`,
          [respondeALimpio]
        )
        : { rows: [] };
      const usuarioRespondidoId = usuarioRespondidoResult.rows[0]?.id;
      const receptorId = parentId
        ? (usuarioRespondidoId || destino?.parent_user_id)
        : destino?.creador_id;
      const esRespuestaARespuesta = Boolean(
        parentId && usuarioRespondidoId && usuarioRespondidoId !== destino?.parent_user_id
      );
      const actorName = nombreActor(req.user);
      await crearNotificacion({
        userId: receptorId,
        actorId: req.user.id,
        type: parentId ? 'reel_reply' : 'reel_comment',
        title: parentId
          ? `${actorName} respondio tu ${esRespuestaARespuesta ? 'respuesta' : 'comentario'}`
          : `${actorName} comento tu reel`,
        body: textoLimpio,
        targetUrl: `/descubrir?lanzamiento=db-${id}&comentario=${result.rows[0].id}`,
        entityType: 'reel_comment',
        entityId: result.rows[0].id,
        uniqueKey: `reel-comment:${result.rows[0].id}:${receptorId}`,
      });
      await notificarMenciones({
        texto: textoLimpio,
        actorId: req.user.id,
        actorName,
        targetUrl: `/descubrir?lanzamiento=db-${id}&comentario=${result.rows[0].id}`,
        entityType: 'reel_comment',
        entityId: result.rows[0].id,
      });

      res.status(201).json(mapearComentario({
        ...result.rows[0],
        username: usuarioResult.rows[0]?.username,
        email: usuarioResult.rows[0]?.email || req.user.email,
        profile_img_url: usuarioResult.rows[0]?.profile_img_url,
      }));
    } catch (error) {
      console.error('Error al crear comentario:', error);
      res.status(500).json({ error: 'No se pudo guardar el comentario.' });
    }
  },

  crearReel: async (req, res) => {
    const { tema, album, genero, descripcion, duracion } = req.body;
    const portadaFile = req.files?.portada?.[0];
    const audioFile = req.files?.audio?.[0];
    let portadaSubida = null;
    let audioSubido = null;

    if (!tema || !album || !genero || !audioFile) {
      return res.status(400).json({ error: 'Faltan datos obligatorios del reel.' });
    }

    try {
      await asegurarUsuarioPublico(req.user);
      portadaSubida = await subirPortadaReel(portadaFile);
      audioSubido = await subirAudioReel(audioFile);

      const result = await pool.query(
        `INSERT INTO reels (
          titulo, album, genero, descripcion, duracion,
          portada_url, portada_path, audio_url, audio_path, creador_id
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
        RETURNING *`,
        [
          tema,
          album,
          genero,
          descripcion || 'Nuevo reel publicado en SONDAR.',
          duracion || '0:30',
          portadaSubida?.publicUrl || null,
          portadaSubida?.path || null,
          audioSubido.publicUrl,
          audioSubido.path,
          req.user.id
        ]
      );

      const usuarioResult = await pool.query(
        `SELECT u.profile_img_url
         FROM users u
         WHERE u.id = $1`,
        [req.user.id]
      );

      const actorName = nombreActor(req.user);
      await notificarSeguidores({
        actorId: req.user.id,
        type: 'new_reel',
        title: `${actorName} publico un nuevo reel`,
        body: result.rows[0].titulo,
        targetUrl: `/descubrir?lanzamiento=db-${result.rows[0].id}`,
        entityType: 'reel',
        entityId: result.rows[0].id,
        uniquePrefix: `new-reel:${result.rows[0].id}`,
      });
      await notificarMenciones({
        texto: descripcion,
        actorId: req.user.id,
        actorName,
        targetUrl: `/descubrir?lanzamiento=db-${result.rows[0].id}`,
        entityType: 'reel',
        entityId: result.rows[0].id,
      });

      res.status(201).json(mapearReel({
        ...result.rows[0],
        creador_nombre: req.user.user_metadata?.username || req.user.email?.split('@')[0],
        creador_email: req.user.email,
        creador_avatar: usuarioResult.rows[0]?.profile_img_url || '',
      }));
    } catch (error) {
      await eliminarArchivoReel(portadaSubida?.path).catch(() => null);
      await eliminarArchivoReel(audioSubido?.path).catch(() => null);
      console.error('Error al crear reel:', error);
      res.status(500).json({ error: error.message || 'No se pudo guardar el reel.' });
    }
  },

  eliminarReel: async (req, res) => {
    const { id } = req.params;

    try {
      const result = await pool.query(
        'DELETE FROM reels WHERE id = $1 AND creador_id = $2 RETURNING id, portada_path, audio_path',
        [id, req.user.id]
      );

      if (result.rowCount === 0) {
        return res.status(404).json({ error: 'Reel no encontrado o sin permiso para eliminarlo.' });
      }

      await eliminarArchivoReel(result.rows[0].portada_path).catch(() => null);
      await eliminarArchivoReel(result.rows[0].audio_path).catch(() => null);
      res.json({ ok: true, id: result.rows[0].id });
    } catch (error) {
      console.error('Error al eliminar reel:', error);
      res.status(500).json({ error: 'No se pudo eliminar el reel.' });
    }
  },

  eliminarComentario: async (req, res) => {
    const { comentarioId } = req.params;

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComentarios();

      const result = await pool.query(
        `DELETE FROM reel_comments
         WHERE id = $1 AND user_id = $2
         RETURNING id, reel_id, parent_id`,
        [comentarioId, req.user.id]
      );

      if (result.rowCount === 0) {
        return res.status(404).json({ error: 'Comentario no encontrado o sin permiso para eliminarlo.' });
      }

      res.json({
        ok: true,
        id: Number(result.rows[0].id),
        reelId: Number(result.rows[0].reel_id),
        parentId: result.rows[0].parent_id ? Number(result.rows[0].parent_id) : null,
      });
    } catch (error) {
      console.error('Error al eliminar comentario:', error);
      res.status(500).json({ error: 'No se pudo eliminar el comentario.' });
    }
  },

  alternarLike: async (req, res) => {
    const { id } = req.params;
    const client = await pool.connect();

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaInteracciones();
      await client.query('BEGIN');

      const reel = await buscarAccesoReel(id, client);
      if (!reel) {
        await client.query('ROLLBACK');
        return res.status(404).json({ error: 'Reel no encontrado.' });
      }

      const existe = await client.query(
        'SELECT 1 FROM reel_likes WHERE user_id = $1 AND reel_id = $2',
        [req.user.id, id]
      );

      let liked = false;
      if (existe.rowCount > 0) {
        await client.query('DELETE FROM reel_likes WHERE user_id = $1 AND reel_id = $2', [req.user.id, id]);
        await client.query('UPDATE reels SET likes = GREATEST(0, likes - 1) WHERE id = $1', [id]);
      } else {
        await client.query('INSERT INTO reel_likes (user_id, reel_id) VALUES ($1, $2)', [req.user.id, id]);
        await client.query('UPDATE reels SET likes = likes + 1 WHERE id = $1', [id]);
        liked = true;
        await crearNotificacion({
          userId: reel.creador_id,
          actorId: req.user.id,
          type: 'reel_like',
          title: `${nombreActor(req.user)} indico que le gusta tu reel`,
          body: reel.titulo || '',
          targetUrl: `/descubrir?lanzamiento=db-${id}`,
          entityType: 'reel',
          entityId: id,
          uniqueKey: `reel-like:${req.user.id}:${id}`,
        }, client);
      }

      if (!liked) {
        await eliminarNotificacion(`reel-like:${req.user.id}:${id}`, client);
      }

      const counts = await client.query('SELECT likes FROM reels WHERE id = $1', [id]);
      await client.query('COMMIT');

      res.json({
        liked,
        likes: Number(counts.rows[0]?.likes || 0),
      });
    } catch (error) {
      await client.query('ROLLBACK').catch(() => null);
      console.error('Error al alternar like de reel:', error);
      res.status(500).json({ error: 'No se pudo actualizar el favorito.' });
    } finally {
      client.release();
    }
  },

  alternarLikeComentario: async (req, res) => {
    const { comentarioId } = req.params;
    const client = await pool.connect();

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaComentarios();
      await client.query('BEGIN');

      const comentario = await buscarAccesoComentario(comentarioId, client);
      if (!comentario) {
        await client.query('ROLLBACK');
        return res.status(404).json({ error: 'Comentario no encontrado.' });
      }

      const existe = await client.query(
        'SELECT 1 FROM reel_comment_likes WHERE user_id = $1 AND comment_id = $2',
        [req.user.id, comentarioId]
      );

      let liked = false;
      if (existe.rowCount > 0) {
        await client.query(
          'DELETE FROM reel_comment_likes WHERE user_id = $1 AND comment_id = $2',
          [req.user.id, comentarioId]
        );
        await client.query(
          'UPDATE reel_comments SET likes = GREATEST(0, likes - 1) WHERE id = $1',
          [comentarioId]
        );
      } else {
        await client.query(
          'INSERT INTO reel_comment_likes (user_id, comment_id) VALUES ($1, $2)',
          [req.user.id, comentarioId]
        );
        await client.query(
          'UPDATE reel_comments SET likes = likes + 1 WHERE id = $1',
          [comentarioId]
        );
        liked = true;
        await crearNotificacion({
          userId: comentario.user_id,
          actorId: req.user.id,
          type: 'reel_comment_like',
          title: `${nombreActor(req.user)} indico que le gusta tu comentario`,
          body: comentario.texto || '',
          targetUrl: `/descubrir?lanzamiento=db-${comentario.reel_id}&comentario=${comentarioId}`,
          entityType: 'reel_comment',
          entityId: comentarioId,
          uniqueKey: `reel-comment-like:${req.user.id}:${comentarioId}`,
        }, client);
      }

      if (!liked) {
        await eliminarNotificacion(`reel-comment-like:${req.user.id}:${comentarioId}`, client);
      }

      const counts = await client.query('SELECT likes FROM reel_comments WHERE id = $1', [comentarioId]);
      await client.query('COMMIT');

      res.json({
        id: Number(comentarioId),
        liked,
        likes: Number(counts.rows[0]?.likes || 0),
      });
    } catch (error) {
      await client.query('ROLLBACK').catch(() => null);
      console.error('Error al alternar like de comentario:', error);
      res.status(500).json({ error: 'No se pudo actualizar el me gusta.' });
    } finally {
      client.release();
    }
  },

  registrarCompartido: async (req, res) => {
    const { id } = req.params;
    const client = await pool.connect();

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaInteracciones();
      await asegurarEsquemaCompartidos();
      await client.query('BEGIN');

      const reel = await buscarAccesoReel(id, client);
      if (!reel) {
        await client.query('ROLLBACK');
        return res.status(404).json({ error: 'Reel no encontrado.' });
      }

      const compartido = await client.query(
        `INSERT INTO reel_shares (user_id, reel_id)
         VALUES ($1, $2)
         ON CONFLICT (user_id, reel_id) DO NOTHING
         RETURNING reel_id`,
        [req.user.id, id]
      );

      const counts = await client.query(
        `UPDATE reels
         SET compartidos = (
           SELECT COUNT(*)::int
           FROM reel_shares
           WHERE reel_id = $1
         )
         WHERE id = $1
         RETURNING compartidos`,
        [id]
      );
      await client.query('COMMIT');

      res.json({
        compartido: true,
        nuevoCompartido: compartido.rowCount > 0,
        compartidos: Number(counts.rows[0]?.compartidos || 0),
      });
    } catch (error) {
      await client.query('ROLLBACK').catch(() => null);
      console.error('Error al registrar compartido:', error);
      res.status(500).json({ error: 'No se pudo registrar el compartido.' });
    } finally {
      client.release();
    }
  },

  alternarGuardado: async (req, res) => {
    const { id } = req.params;
    const client = await pool.connect();

    try {
      await asegurarUsuarioPublico(req.user);
      await asegurarEsquemaInteracciones();
      await client.query('BEGIN');

      const reel = await buscarAccesoReel(id, client);
      if (!reel) {
        await client.query('ROLLBACK');
        return res.status(404).json({ error: 'Reel no encontrado.' });
      }

      const existe = await client.query(
        'SELECT 1 FROM reel_saves WHERE user_id = $1 AND reel_id = $2',
        [req.user.id, id]
      );

      let guardado = false;
      if (existe.rowCount > 0) {
        await client.query('DELETE FROM reel_saves WHERE user_id = $1 AND reel_id = $2', [req.user.id, id]);
        await client.query('UPDATE reels SET guardados = GREATEST(0, guardados - 1) WHERE id = $1', [id]);
      } else {
        await client.query('INSERT INTO reel_saves (user_id, reel_id) VALUES ($1, $2)', [req.user.id, id]);
        await client.query('UPDATE reels SET guardados = guardados + 1 WHERE id = $1', [id]);
        guardado = true;
      }

      const counts = await client.query('SELECT guardados FROM reels WHERE id = $1', [id]);
      await client.query('COMMIT');

      res.json({
        guardado,
        guardados: Number(counts.rows[0]?.guardados || 0),
      });
    } catch (error) {
      await client.query('ROLLBACK').catch(() => null);
      console.error('Error al alternar guardado de reel:', error);
      res.status(500).json({ error: 'No se pudo actualizar el guardado.' });
    } finally {
      client.release();
    }
  }
};

module.exports = reelController;
