ALTER TABLE reels ADD COLUMN IF NOT EXISTS album text NOT NULL DEFAULT '';
ALTER TABLE reels ADD COLUMN IF NOT EXISTS descripcion text NOT NULL DEFAULT '';
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS titulo text NOT NULL DEFAULT 'Evento SONDAR';
