BEGIN;

CREATE TABLE IF NOT EXISTS public.notification_mutes (
  user_id uuid NOT NULL,
  muted_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, muted_user_id),
  CONSTRAINT notification_mutes_follow_fk
    FOREIGN KEY (user_id, muted_user_id)
    REFERENCES public.follows(follower_id, following_id)
    ON DELETE CASCADE,
  CONSTRAINT notification_mutes_no_self CHECK (user_id <> muted_user_id)
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  actor_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  type text NOT NULL,
  title text NOT NULL CHECK (length(title) <= 120),
  body text NOT NULL DEFAULT '' CHECK (length(body) <= 500),
  target_url text NOT NULL DEFAULT '',
  entity_type text,
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  unique_key text UNIQUE,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS notifications_user_created_idx
  ON public.notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_user_unread_idx
  ON public.notifications(user_id, created_at DESC)
  WHERE read_at IS NULL;
CREATE INDEX IF NOT EXISTS notification_mutes_muted_user_idx
  ON public.notification_mutes(muted_user_id);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_mutes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS notifications_select_own ON public.notifications;
CREATE POLICY notifications_select_own ON public.notifications
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS notifications_update_own ON public.notifications;
CREATE POLICY notifications_update_own ON public.notifications
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS notifications_delete_own ON public.notifications;
CREATE POLICY notifications_delete_own ON public.notifications
  FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS notification_mutes_select_own ON public.notification_mutes;
CREATE POLICY notification_mutes_select_own ON public.notification_mutes
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS notification_mutes_insert_own ON public.notification_mutes;
CREATE POLICY notification_mutes_insert_own ON public.notification_mutes
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS notification_mutes_delete_own ON public.notification_mutes;
CREATE POLICY notification_mutes_delete_own ON public.notification_mutes
  FOR DELETE USING (auth.uid() = user_id);

INSERT INTO public.notifications (
  user_id, actor_id, type, title, body, target_url, unique_key
)
SELECT
  u.id,
  NULL,
  'welcome',
  'Bienvenido a SONDAR',
  'Aca vas a ver seguidores, respuestas, menciones y actividad de tus publicaciones.',
  '/descubrir',
  concat('welcome:', u.id::text)
FROM public.users u
ON CONFLICT (unique_key) DO NOTHING;

COMMIT;
