-- Ejecutar en el SQL editor de Supabase.

CREATE TABLE IF NOT EXISTS reels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    album TEXT NOT NULL,
    genero TEXT NOT NULL,
    descripcion TEXT,
    duracion TEXT,
    portada_url TEXT,
    portada_path TEXT,
    audio_url TEXT NOT NULL,
    audio_path TEXT NOT NULL,
    likes INTEGER NOT NULL DEFAULT 0,
    compartidos INTEGER NOT NULL DEFAULT 0,
    guardados INTEGER NOT NULL DEFAULT 0,
    creador_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS reels_creador_id_idx ON reels (creador_id);
CREATE INDEX IF NOT EXISTS reels_created_at_idx ON reels (created_at DESC);

-- Crear tambien un bucket publico de Storage llamado: reels
-- Desde Supabase Dashboard: Storage -> New bucket -> name "reels" -> Public bucket.
