-- Ejecutar en Supabase SQL Editor.
-- Comunidades fijas por genero. No incluye "otros".

CREATE TABLE IF NOT EXISTS public.comunidades (
  id text PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  titulo text NOT NULL,
  genero text NOT NULL UNIQUE,
  descripcion text NOT NULL,
  portada_url text,
  activa boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.comunidad_publicaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comunidad_id text NOT NULL REFERENCES public.comunidades(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  tipo text NOT NULL DEFAULT 'reciente'
    CHECK (tipo IN ('destacado', 'reciente', 'popular', 'preguntas')),
  titulo text NOT NULL CHECK (length(trim(titulo)) > 0),
  texto text NOT NULL CHECK (length(trim(texto)) > 0),
  etiqueta text,
  likes integer NOT NULL DEFAULT 0,
  guardados integer NOT NULL DEFAULT 0,
  fijada boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.comunidad_publicacion_likes (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  publicacion_id bigint NOT NULL REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT comunidad_publicacion_likes_pkey PRIMARY KEY (user_id, publicacion_id)
);

CREATE TABLE IF NOT EXISTS public.comunidad_publicacion_guardados (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  publicacion_id bigint NOT NULL REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT comunidad_publicacion_guardados_pkey PRIMARY KEY (user_id, publicacion_id)
);

CREATE TABLE IF NOT EXISTS public.comunidad_comentarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id bigint NOT NULL REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  parent_id bigint REFERENCES public.comunidad_comentarios(id) ON DELETE CASCADE,
  texto text NOT NULL CHECK (length(trim(texto)) > 0),
  likes integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.comunidad_comentario_likes (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  comentario_id bigint NOT NULL REFERENCES public.comunidad_comentarios(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT comunidad_comentario_likes_pkey PRIMARY KEY (user_id, comentario_id)
);

CREATE INDEX IF NOT EXISTS idx_comunidad_publicaciones_comunidad
  ON public.comunidad_publicaciones(comunidad_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comunidad_publicaciones_user
  ON public.comunidad_publicaciones(user_id);
CREATE INDEX IF NOT EXISTS idx_comunidad_publicacion_likes_publicacion
  ON public.comunidad_publicacion_likes(publicacion_id);
CREATE INDEX IF NOT EXISTS idx_comunidad_publicacion_guardados_publicacion
  ON public.comunidad_publicacion_guardados(publicacion_id);
CREATE INDEX IF NOT EXISTS idx_comunidad_comentarios_publicacion
  ON public.comunidad_comentarios(publicacion_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_comunidad_comentarios_parent
  ON public.comunidad_comentarios(parent_id);
CREATE INDEX IF NOT EXISTS idx_comunidad_comentario_likes_comentario
  ON public.comunidad_comentario_likes(comentario_id);

INSERT INTO public.comunidades (id, nombre, titulo, genero, descripcion, portada_url)
VALUES
  ('pop', '@pop', 'Pop', 'pop', 'Charlas, lanzamientos, preguntas y recomendaciones para la escena pop de SONDAR.', 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=80'),
  ('rock', '@rock', 'Rock', 'rock', 'Guitarras, fechas, bandas nuevas, demos y conversaciones de la comunidad rock.', 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1400&q=80'),
  ('edm', '@edm', 'EDM', 'edm', 'Sets, drops, produccion, festivales y novedades de la comunidad EDM.', 'https://images.unsplash.com/photo-1571266028243-d220c9c3b8ef?auto=format&fit=crop&w=1400&q=80'),
  ('jazz', '@jazz', 'Jazz', 'jazz', 'Improvisacion, standards, jams, discos y encuentros para oyentes y musicos de jazz.', 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1400&q=80'),
  ('blues', '@blues', 'Blues', 'blues', 'Riffs, armonicas, zapadas, fechas y recomendaciones para quienes siguen el blues.', 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80'),
  ('cumbia', '@cumbia', 'Cumbia', 'cumbia', 'Bandas, bailes, estrenos, eventos y charla abierta para la comunidad cumbiera.', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=80'),
  ('trap', '@trap', 'Trap', 'trap', 'Beats, barras, productores, lanzamientos y debates de la escena trap.', 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1400&q=80'),
  ('metal', '@metal', 'Metal', 'metal', 'Riffs pesados, fechas, discos, bandas emergentes y comunidad metalera.', 'https://images.unsplash.com/photo-1508252592163-5d3c3c5599ab?auto=format&fit=crop&w=1400&q=80'),
  ('folklore', '@folklore', 'Folklore', 'folklore', 'Penas, canciones, instrumentos, festivales y relatos de la escena folklorica.', 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1400&q=80')
ON CONFLICT (id) DO UPDATE
SET nombre = EXCLUDED.nombre,
    titulo = EXCLUDED.titulo,
    genero = EXCLUDED.genero,
    descripcion = EXCLUDED.descripcion,
    portada_url = EXCLUDED.portada_url,
    activa = true;

ALTER TABLE public.comunidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_publicaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_publicacion_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_publicacion_guardados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_comentarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_comentario_likes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidades' AND policyname = 'comunidades_select_public'
  ) THEN
    CREATE POLICY comunidades_select_public ON public.comunidades
      FOR SELECT USING (activa = true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicaciones' AND policyname = 'comunidad_publicaciones_select_public'
  ) THEN
    CREATE POLICY comunidad_publicaciones_select_public ON public.comunidad_publicaciones
      FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicaciones' AND policyname = 'comunidad_publicaciones_insert_own'
  ) THEN
    CREATE POLICY comunidad_publicaciones_insert_own ON public.comunidad_publicaciones
      FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicaciones' AND policyname = 'comunidad_publicaciones_update_own'
  ) THEN
    CREATE POLICY comunidad_publicaciones_update_own ON public.comunidad_publicaciones
      FOR UPDATE USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicaciones' AND policyname = 'comunidad_publicaciones_delete_own'
  ) THEN
    CREATE POLICY comunidad_publicaciones_delete_own ON public.comunidad_publicaciones
      FOR DELETE USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicacion_likes' AND policyname = 'comunidad_publicacion_likes_select_public'
  ) THEN
    CREATE POLICY comunidad_publicacion_likes_select_public ON public.comunidad_publicacion_likes
      FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicacion_likes' AND policyname = 'comunidad_publicacion_likes_insert_own'
  ) THEN
    CREATE POLICY comunidad_publicacion_likes_insert_own ON public.comunidad_publicacion_likes
      FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicacion_likes' AND policyname = 'comunidad_publicacion_likes_delete_own'
  ) THEN
    CREATE POLICY comunidad_publicacion_likes_delete_own ON public.comunidad_publicacion_likes
      FOR DELETE USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicacion_guardados' AND policyname = 'comunidad_publicacion_guardados_select_own'
  ) THEN
    CREATE POLICY comunidad_publicacion_guardados_select_own ON public.comunidad_publicacion_guardados
      FOR SELECT USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicacion_guardados' AND policyname = 'comunidad_publicacion_guardados_insert_own'
  ) THEN
    CREATE POLICY comunidad_publicacion_guardados_insert_own ON public.comunidad_publicacion_guardados
      FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_publicacion_guardados' AND policyname = 'comunidad_publicacion_guardados_delete_own'
  ) THEN
    CREATE POLICY comunidad_publicacion_guardados_delete_own ON public.comunidad_publicacion_guardados
      FOR DELETE USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_comentarios' AND policyname = 'comunidad_comentarios_select_public'
  ) THEN
    CREATE POLICY comunidad_comentarios_select_public ON public.comunidad_comentarios
      FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_comentarios' AND policyname = 'comunidad_comentarios_insert_own'
  ) THEN
    CREATE POLICY comunidad_comentarios_insert_own ON public.comunidad_comentarios
      FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_comentarios' AND policyname = 'comunidad_comentarios_delete_own'
  ) THEN
    CREATE POLICY comunidad_comentarios_delete_own ON public.comunidad_comentarios
      FOR DELETE USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_comentario_likes' AND policyname = 'comunidad_comentario_likes_select_public'
  ) THEN
    CREATE POLICY comunidad_comentario_likes_select_public ON public.comunidad_comentario_likes
      FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_comentario_likes' AND policyname = 'comunidad_comentario_likes_insert_own'
  ) THEN
    CREATE POLICY comunidad_comentario_likes_insert_own ON public.comunidad_comentario_likes
      FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'comunidad_comentario_likes' AND policyname = 'comunidad_comentario_likes_delete_own'
  ) THEN
    CREATE POLICY comunidad_comentario_likes_delete_own ON public.comunidad_comentario_likes
      FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;
