-- SONDAR: esquema minimo funcional para una instalacion nueva de Supabase.
-- No ejecutar sobre una base con datos: este archivo define el estado final limpio.
-- Auth conserva credenciales/sesiones en auth.users; public.users conserva el perfil.

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Usuarios, autenticacion y configuracion unificada
-- -----------------------------------------------------------------------------

CREATE TABLE public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL UNIQUE,
  username text NOT NULL,
  user_type text NOT NULL DEFAULT 'musico'
    CHECK (user_type IN ('musico', 'organizador', 'admin')),
  display_name text CHECK (display_name IS NULL OR length(trim(display_name)) BETWEEN 1 AND 100),
  bio text NOT NULL DEFAULT '' CHECK (length(bio) <= 500),
  birth_date date CHECK (birth_date IS NULL OR birth_date >= DATE '1900-01-01'),
  profile_img_url text,
  profile_img_path text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT users_username_formato_check
    CHECK (username ~ '^[a-z0-9._-]{3,30}$')
);

CREATE UNIQUE INDEX users_username_lower_unique ON public.users (lower(username));

CREATE TABLE public.user_settings (
  user_id uuid PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  telefono text NOT NULL DEFAULT '' CHECK (length(telefono) <= 30),
  codigo_pais text NOT NULL DEFAULT '+54'
    CHECK (codigo_pais IN ('+54', '+55', '+56', '+598')),
  idioma text NOT NULL DEFAULT 'es' CHECK (idioma IN ('es', 'en', 'pt')),
  actividad_cuenta boolean NOT NULL DEFAULT true,
  notificar_interacciones boolean NOT NULL DEFAULT true,
  notificar_comentarios boolean NOT NULL DEFAULT true,
  notificar_seguidores boolean NOT NULL DEFAULT true,
  notificar_publicaciones boolean NOT NULL DEFAULT true,
  notificar_menciones boolean NOT NULL DEFAULT true,
  reducir_movimiento boolean NOT NULL DEFAULT false,
  mostrar_email boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.user_interests (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  genre text NOT NULL CHECK (genre IN ('pop', 'rock', 'trap', 'cumbia', 'edm', 'jazz', 'blues', 'metal', 'folklore')),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, genre)
);

CREATE INDEX user_interests_genre_idx ON public.user_interests (genre, user_id);

CREATE TABLE public.follows (
  follower_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  following_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (follower_id, following_id),
  CHECK (follower_id <> following_id)
);

CREATE INDEX follows_following_created_idx
  ON public.follows (following_id, created_at DESC);

CREATE TABLE public.notification_mutes (
  user_id uuid NOT NULL,
  muted_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, muted_user_id),
  FOREIGN KEY (user_id, muted_user_id)
    REFERENCES public.follows(follower_id, following_id) ON DELETE CASCADE,
  CHECK (user_id <> muted_user_id)
);

CREATE INDEX notification_mutes_muted_user_idx
  ON public.notification_mutes (muted_user_id);

CREATE TABLE public.user_blocks (
  blocker_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  blocked_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);

CREATE INDEX user_blocks_blocked_idx ON public.user_blocks (blocked_id);

-- -----------------------------------------------------------------------------
-- 2. Eventos
-- -----------------------------------------------------------------------------

CREATE TABLE public.generos (
  slug text PRIMARY KEY,
  nombre text NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  orden smallint NOT NULL DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CHECK (length(trim(slug)) > 0),
  CHECK (length(trim(nombre)) > 0)
);

INSERT INTO public.generos (slug, nombre, activo, orden) VALUES
  ('pop', 'Pop', true, 1),
  ('rock', 'Rock', true, 2),
  ('edm', 'Electronica', true, 3),
  ('jazz', 'Jazz', true, 4),
  ('blues', 'Blues', true, 5),
  ('cumbia', 'Cumbia', true, 6),
  ('trap', 'Urbano', true, 7),
  ('metal', 'Metal', true, 8),
  ('folklore', 'Folklore', true, 9),
  ('alternativo', 'Alternativo', true, 10),
  ('punk', 'Punk', true, 11),
  ('reggae', 'Reggae', true, 12),
  ('latina', 'Latina', true, 13),
  ('otros', 'Otros', true, 99);

CREATE TABLE public.eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genero text NOT NULL,
  lugar text NOT NULL,
  fecha timestamptz NOT NULL,
  img_url text,
  img_path text,
  precio numeric(12, 2) CHECK (precio IS NULL OR precio >= 0),
  link text,
  creador_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  latitud double precision NOT NULL CHECK (latitud BETWEEN -90 AND 90),
  longitud double precision NOT NULL CHECK (longitud BETWEEN -180 AND 180),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX eventos_creador_created_idx
  ON public.eventos (creador_id, created_at DESC);
CREATE INDEX eventos_fecha_idx ON public.eventos (fecha);

CREATE TABLE public.evento_generos (
  event_id bigint NOT NULL REFERENCES public.eventos(id) ON DELETE CASCADE,
  genero text NOT NULL REFERENCES public.generos(slug),
  posicion smallint NOT NULL CHECK (posicion BETWEEN 1 AND 3),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (event_id, genero),
  UNIQUE (event_id, posicion)
);

CREATE INDEX evento_generos_genero_event_idx
  ON public.evento_generos (genero, event_id);

CREATE TABLE public.event_organizers (
  event_id bigint NOT NULL REFERENCES public.eventos(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  added_by uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (event_id, user_id)
);

CREATE INDEX event_organizers_user_idx ON public.event_organizers (user_id);

CREATE TABLE public.event_saves (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  event_id bigint NOT NULL REFERENCES public.eventos(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, event_id)
);

CREATE INDEX event_saves_event_idx ON public.event_saves (event_id);

-- -----------------------------------------------------------------------------
-- 3. Reels. Las metricas se calculan desde las tablas de interaccion.
-- -----------------------------------------------------------------------------

CREATE TABLE public.reels (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo text NOT NULL CHECK (length(trim(titulo)) > 0),
  genero text NOT NULL,
  duracion text NOT NULL DEFAULT '0:30',
  portada_url text,
  portada_path text,
  audio_url text NOT NULL,
  audio_path text NOT NULL,
  color_principal text CONSTRAINT reels_color_principal_formato_check
    CHECK (color_principal IS NULL OR color_principal ~ '^#[0-9a-fA-F]{6}$'),
  creador_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX reels_created_idx ON public.reels (created_at DESC, id DESC);
CREATE INDEX reels_creador_created_idx
  ON public.reels (creador_id, created_at DESC);

CREATE TABLE public.reel_generos (
  reel_id bigint NOT NULL REFERENCES public.reels(id) ON DELETE CASCADE,
  genero text NOT NULL REFERENCES public.generos(slug),
  posicion smallint NOT NULL CHECK (posicion BETWEEN 1 AND 3),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (reel_id, genero),
  UNIQUE (reel_id, posicion)
);

CREATE INDEX reel_generos_genero_reel_idx
  ON public.reel_generos (genero, reel_id);

CREATE TABLE public.reel_views (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reel_id bigint NOT NULL REFERENCES public.reels(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, reel_id)
);

CREATE INDEX reel_views_reel_idx ON public.reel_views (reel_id);

CREATE TABLE public.reel_likes (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reel_id bigint NOT NULL REFERENCES public.reels(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, reel_id)
);

CREATE INDEX reel_likes_reel_idx ON public.reel_likes (reel_id);

CREATE TABLE public.reel_shares (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reel_id bigint NOT NULL REFERENCES public.reels(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, reel_id)
);

CREATE INDEX reel_shares_reel_idx ON public.reel_shares (reel_id);

CREATE TABLE public.reel_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reel_id bigint NOT NULL REFERENCES public.reels(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  parent_id bigint REFERENCES public.reel_comments(id) ON DELETE CASCADE,
  texto text NOT NULL CHECK (length(trim(texto)) > 0),
  responde_a text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX reel_comments_reel_created_idx
  ON public.reel_comments (reel_id, created_at, id);
CREATE INDEX reel_comments_parent_idx ON public.reel_comments (parent_id);
CREATE INDEX reel_comments_user_created_idx
  ON public.reel_comments (user_id, created_at DESC);

CREATE TABLE public.reel_comment_likes (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  comment_id bigint NOT NULL REFERENCES public.reel_comments(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, comment_id)
);

CREATE INDEX reel_comment_likes_comment_idx
  ON public.reel_comment_likes (comment_id);

-- -----------------------------------------------------------------------------
-- 4. Foros por genero y comunidad de cada perfil
-- -----------------------------------------------------------------------------

CREATE TABLE public.comunidades (
  id text PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  titulo text NOT NULL,
  genero text NOT NULL UNIQUE,
  descripcion text NOT NULL,
  portada_url text,
  activa boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.comunidad_miembros (
  comunidad_id text NOT NULL REFERENCES public.comunidades(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  nivel_notificaciones text NOT NULL DEFAULT 'todas'
    CHECK (nivel_notificaciones IN ('todas', 'relevantes', 'silenciadas')),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (comunidad_id, user_id)
);

CREATE INDEX comunidad_miembros_user_idx
  ON public.comunidad_miembros (user_id, created_at DESC);

CREATE TABLE public.comunidad_publicaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comunidad_id text NOT NULL REFERENCES public.comunidades(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  tipo text NOT NULL DEFAULT 'reciente'
    CHECK (tipo IN ('destacado', 'reciente', 'popular', 'preguntas')),
  titulo text NOT NULL CHECK (length(trim(titulo)) > 0),
  texto text NOT NULL CHECK (length(trim(texto)) > 0),
  etiqueta text,
  fijada boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX comunidad_publicaciones_comunidad_idx
  ON public.comunidad_publicaciones (comunidad_id, created_at DESC, id DESC);
CREATE INDEX comunidad_publicaciones_user_idx
  ON public.comunidad_publicaciones (user_id, created_at DESC);

CREATE TABLE public.comunidad_publicacion_likes (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  publicacion_id bigint NOT NULL REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, publicacion_id)
);

CREATE INDEX comunidad_publicacion_likes_publicacion_idx
  ON public.comunidad_publicacion_likes (publicacion_id);

CREATE TABLE public.comunidad_publicacion_guardados (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  publicacion_id bigint NOT NULL REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, publicacion_id)
);

CREATE INDEX comunidad_guardados_publicacion_idx
  ON public.comunidad_publicacion_guardados (publicacion_id);

CREATE TABLE public.comunidad_comentarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id bigint NOT NULL REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  parent_id bigint REFERENCES public.comunidad_comentarios(id) ON DELETE CASCADE,
  texto text NOT NULL CHECK (length(trim(texto)) > 0),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX comunidad_comentarios_publicacion_idx
  ON public.comunidad_comentarios (publicacion_id, created_at, id);
CREATE INDEX comunidad_comentarios_parent_idx
  ON public.comunidad_comentarios (parent_id);
CREATE INDEX comunidad_comentarios_user_idx
  ON public.comunidad_comentarios (user_id, created_at DESC);

CREATE TABLE public.comunidad_comentario_likes (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  comentario_id bigint NOT NULL REFERENCES public.comunidad_comentarios(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, comentario_id)
);

CREATE INDEX comunidad_comentario_likes_comentario_idx
  ON public.comunidad_comentario_likes (comentario_id);

CREATE TABLE public.perfil_comunidad_publicaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  origen text NOT NULL DEFAULT 'manual'
    CHECK (origen IN ('manual', 'reel', 'evento')),
  texto text NOT NULL CHECK (length(trim(texto)) BETWEEN 1 AND 1000),
  reel_id bigint REFERENCES public.reels(id) ON DELETE CASCADE,
  evento_id bigint REFERENCES public.eventos(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CHECK (num_nonnulls(reel_id, evento_id) <= 1),
  CHECK (
    origen = 'manual'
    OR (origen = 'reel' AND reel_id IS NOT NULL AND evento_id IS NULL)
    OR (origen = 'evento' AND evento_id IS NOT NULL AND reel_id IS NULL)
  )
);

CREATE TABLE public.perfil_comunidad_respuestas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id bigint NOT NULL
    REFERENCES public.perfil_comunidad_publicaciones(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  parent_id bigint REFERENCES public.perfil_comunidad_respuestas(id) ON DELETE CASCADE,
  texto text NOT NULL CHECK (length(trim(texto)) BETWEEN 1 AND 800),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX perfil_comunidad_publicaciones_user_idx
  ON public.perfil_comunidad_publicaciones (user_id, created_at DESC, id DESC);
CREATE UNIQUE INDEX perfil_comunidad_auto_reel_idx
  ON public.perfil_comunidad_publicaciones (reel_id) WHERE origen = 'reel';
CREATE UNIQUE INDEX perfil_comunidad_auto_evento_idx
  ON public.perfil_comunidad_publicaciones (evento_id) WHERE origen = 'evento';
CREATE INDEX perfil_comunidad_respuestas_publicacion_idx
  ON public.perfil_comunidad_respuestas (publicacion_id, created_at, id);
CREATE INDEX perfil_comunidad_respuestas_parent_idx
  ON public.perfil_comunidad_respuestas (parent_id);

CREATE OR REPLACE FUNCTION public.validar_padre_respuesta_perfil()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.parent_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.perfil_comunidad_respuestas padre
    WHERE padre.id = NEW.parent_id
      AND padre.publicacion_id = NEW.publicacion_id
  ) THEN
    RAISE EXCEPTION 'La respuesta citada no pertenece a esta publicacion.'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER perfil_comunidad_respuesta_padre_valido
BEFORE INSERT OR UPDATE OF parent_id, publicacion_id
ON public.perfil_comunidad_respuestas
FOR EACH ROW EXECUTE FUNCTION public.validar_padre_respuesta_perfil();

CREATE OR REPLACE FUNCTION public.crear_publicacion_automatica_perfil()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_TABLE_NAME = 'reels' THEN
    INSERT INTO public.perfil_comunidad_publicaciones (user_id, origen, texto, reel_id)
    VALUES (NEW.creador_id, 'reel', format('Publico una nueva preview: %s.', NEW.titulo), NEW.id)
    ON CONFLICT (reel_id) WHERE origen = 'reel' DO NOTHING;
  ELSIF TG_TABLE_NAME = 'eventos' THEN
    INSERT INTO public.perfil_comunidad_publicaciones (user_id, origen, texto, evento_id)
    VALUES (
      NEW.creador_id,
      'evento',
      format('Creo un nuevo evento en %s.', COALESCE(NULLIF(NEW.lugar, ''), 'un lugar a confirmar')),
      NEW.id
    )
    ON CONFLICT (evento_id) WHERE origen = 'evento' DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER perfil_comunidad_reel_creado
AFTER INSERT ON public.reels
FOR EACH ROW EXECUTE FUNCTION public.crear_publicacion_automatica_perfil();

CREATE TRIGGER perfil_comunidad_evento_creado
AFTER INSERT ON public.eventos
FOR EACH ROW EXECUTE FUNCTION public.crear_publicacion_automatica_perfil();

-- -----------------------------------------------------------------------------
-- 5. Notificaciones y denuncias
-- -----------------------------------------------------------------------------

CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  actor_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  type text NOT NULL,
  title text NOT NULL CHECK (length(title) <= 120),
  body text NOT NULL DEFAULT '' CHECK (length(body) <= 500),
  target_url text NOT NULL DEFAULT '',
  unique_key text UNIQUE,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX notifications_user_created_idx
  ON public.notifications (user_id, created_at DESC, id DESC);
CREATE INDEX notifications_user_unread_idx
  ON public.notifications (user_id, created_at DESC)
  WHERE read_at IS NULL;

CREATE TABLE public.content_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reported_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  content_type text NOT NULL
    CHECK (content_type IN ('reel', 'evento', 'perfil', 'community_post', 'community_comment', 'profile_post', 'profile_post_reply')),
  content_id text NOT NULL,
  reason text NOT NULL DEFAULT 'otro',
  details text NOT NULL DEFAULT '' CHECK (length(details) <= 500),
  status text NOT NULL DEFAULT 'pendiente'
    CHECK (status IN ('pendiente', 'revisado', 'descartado')),
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (reporter_id, content_type, content_id)
);

CREATE INDEX content_reports_status_idx
  ON public.content_reports (status, created_at DESC);

-- -----------------------------------------------------------------------------
-- 6. Sincronizacion auth.users -> public.users
-- -----------------------------------------------------------------------------

-- El backend crea public.users despues de crear la cuenta en Auth.
-- No se usa trigger AFTER INSERT porque puede bloquear /auth/v1/signup.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE OR REPLACE FUNCTION public.sync_auth_user_email()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.users
  SET email = COALESCE(NEW.email, NEW.id::text || '@sin-email.local'),
      updated_at = timezone('utc'::text, now())
  WHERE id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_email_updated ON auth.users;
CREATE TRIGGER on_auth_user_email_updated
  AFTER UPDATE OF email ON auth.users
  FOR EACH ROW
  WHEN (OLD.email IS DISTINCT FROM NEW.email)
  EXECUTE FUNCTION public.sync_auth_user_email();

INSERT INTO public.comunidades (id, nombre, titulo, genero, descripcion, portada_url)
VALUES
  ('pop', '@pop', 'Pop', 'pop', 'Charlas, lanzamientos, preguntas y recomendaciones para la escena pop de SONDAR.', 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=80'),
  ('rock', '@rock', 'Rock', 'rock', 'Guitarras, fechas, bandas nuevas, demos y conversaciones de la comunidad rock.', 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1400&q=80'),
  ('edm', '@edm', 'EDM', 'edm', 'Sets, drops, produccion, festivales y novedades de la comunidad EDM.', 'https://images.unsplash.com/photo-1571266028243-d220c9c3b8ef?auto=format&fit=crop&w=1400&q=80'),
  ('jazz', '@jazz', 'Jazz', 'jazz', 'Improvisacion, standards, jams, discos y encuentros para oyentes y musicos de jazz.', 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1400&q=80'),
  ('blues', '@blues', 'Blues', 'blues', 'Riffs, armonicas, zapadas, fechas y recomendaciones para quienes siguen el blues.', 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80'),
  ('cumbia', '@cumbia', 'Cumbia', 'cumbia', 'Bandas, bailes, estrenos, eventos y charla abierta para la comunidad cumbiera.', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=80'),
  ('trap', '@trap', 'Trap', 'trap', 'Beats, barras, productores, lanzamientos y debates de la escena trap.', 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1400&q=80'),
  ('metal', '@metal', 'Metal', 'metal', 'Riffs pesados, fechas, discos, bandas emergentes y comunidad metalera.', 'https://images.unsplash.com/photo-1508252592163-5d3c3c5599ab?auto=format&fit=crop&w=1400&q=80'),
  ('folklore', '@folklore', 'Folklore', 'folklore', 'Penas, canciones, instrumentos, festivales y relatos de la escena folklorica.', 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1400&q=80'),
  ('alternativo', '@alternativo', 'Alternativo', 'alternativo', 'Propuestas independientes, cruces de estilos, nuevos sonidos y conversaciones de la escena alternativa.', 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1400&q=80'),
  ('punk', '@punk', 'Punk', 'punk', 'Bandas, fechas, discos, autogestion y debates de la comunidad punk de SONDAR.', 'https://images.unsplash.com/photo-1508252592163-5d3c3c5599ab?auto=format&fit=crop&w=1400&q=80'),
  ('reggae', '@reggae', 'Reggae', 'reggae', 'Riddims, bandas, dub, cultura soundsystem, lanzamientos y encuentros de la escena reggae.', 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=80'),
  ('latina', '@latina', 'Latina', 'latina', 'Salsa, bachata, merengue, sonidos urbanos y novedades de la musica latina.', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=80');

-- -----------------------------------------------------------------------------
-- 7. RLS: el frontend consume datos por el backend; Supabase directo queda cerrado
--    salvo lecturas publicas de contenido y operaciones del propio usuario.
-- -----------------------------------------------------------------------------

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_mutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evento_generos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_organizers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_saves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_generos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_comment_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_miembros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_publicaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_publicacion_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_publicacion_guardados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_comentarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_comentario_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfil_comunidad_publicaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfil_comunidad_respuestas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_own ON public.users
  FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY users_update_own ON public.users
  FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE POLICY user_settings_own ON public.user_settings
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY user_interests_own ON public.user_interests
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY follows_read ON public.follows FOR SELECT TO authenticated USING (true);
CREATE POLICY follows_insert_own ON public.follows
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = follower_id);
CREATE POLICY follows_delete_own ON public.follows
  FOR DELETE TO authenticated USING (auth.uid() = follower_id);

CREATE POLICY notification_mutes_own ON public.notification_mutes
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY user_blocks_own ON public.user_blocks
  FOR ALL TO authenticated USING (auth.uid() = blocker_id) WITH CHECK (auth.uid() = blocker_id);

CREATE POLICY generos_public_read ON public.generos
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY eventos_public_read ON public.eventos FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY eventos_insert_own ON public.eventos
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = creador_id);
CREATE POLICY eventos_change_own ON public.eventos
  FOR UPDATE TO authenticated USING (auth.uid() = creador_id) WITH CHECK (auth.uid() = creador_id);
CREATE POLICY eventos_delete_own ON public.eventos
  FOR DELETE TO authenticated USING (auth.uid() = creador_id);

CREATE POLICY evento_generos_public_read ON public.evento_generos
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY evento_generos_owner_write ON public.evento_generos
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.eventos e WHERE e.id = event_id AND e.creador_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.eventos e WHERE e.id = event_id AND e.creador_id = auth.uid()));

CREATE POLICY event_organizers_public_read ON public.event_organizers
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY event_organizers_owner_write ON public.event_organizers
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.eventos e WHERE e.id = event_id AND e.creador_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.eventos e WHERE e.id = event_id AND e.creador_id = auth.uid()));
CREATE POLICY event_saves_own ON public.event_saves
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY reels_public_read ON public.reels FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY reels_insert_own ON public.reels
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = creador_id);
CREATE POLICY reels_change_own ON public.reels
  FOR UPDATE TO authenticated USING (auth.uid() = creador_id) WITH CHECK (auth.uid() = creador_id);
CREATE POLICY reels_delete_own ON public.reels
  FOR DELETE TO authenticated USING (auth.uid() = creador_id);

CREATE POLICY reel_generos_public_read ON public.reel_generos
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY reel_generos_owner_write ON public.reel_generos
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.reels r WHERE r.id = reel_id AND r.creador_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.reels r WHERE r.id = reel_id AND r.creador_id = auth.uid()));

CREATE POLICY reel_comments_public_read ON public.reel_comments
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY reel_comments_insert_own ON public.reel_comments
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY reel_comments_delete_own ON public.reel_comments
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY comunidades_public_read ON public.comunidades
  FOR SELECT TO anon, authenticated USING (activa);
CREATE POLICY comunidad_miembros_select_own ON public.comunidad_miembros
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY comunidad_miembros_own_write ON public.comunidad_miembros
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY comunidad_publicaciones_public_read ON public.comunidad_publicaciones
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY comunidad_publicaciones_insert_own ON public.comunidad_publicaciones
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY comunidad_publicaciones_change_own ON public.comunidad_publicaciones
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY comunidad_publicaciones_delete_own ON public.comunidad_publicaciones
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY comunidad_publicacion_likes_read ON public.comunidad_publicacion_likes
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY comunidad_publicacion_likes_own_write ON public.comunidad_publicacion_likes
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY comunidad_guardados_own ON public.comunidad_publicacion_guardados
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY comunidad_comentarios_public_read ON public.comunidad_comentarios
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY comunidad_comentarios_insert_own ON public.comunidad_comentarios
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY comunidad_comentarios_delete_own ON public.comunidad_comentarios
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY comunidad_comentario_likes_read ON public.comunidad_comentario_likes
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY comunidad_comentario_likes_own_write ON public.comunidad_comentario_likes
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY perfil_comunidad_publicaciones_read ON public.perfil_comunidad_publicaciones
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY perfil_comunidad_publicaciones_insert_own ON public.perfil_comunidad_publicaciones
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND origen = 'manual'
    AND (
      reel_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.reels r
        WHERE r.id = perfil_comunidad_publicaciones.reel_id
          AND r.creador_id = auth.uid()
      )
    )
    AND (
      evento_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.eventos e
        WHERE e.id = perfil_comunidad_publicaciones.evento_id
          AND e.creador_id = auth.uid()
      )
    )
  );
CREATE POLICY perfil_comunidad_publicaciones_update_own ON public.perfil_comunidad_publicaciones
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (
    auth.uid() = user_id
    AND origen = 'manual'
    AND (
      reel_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.reels r
        WHERE r.id = perfil_comunidad_publicaciones.reel_id
          AND r.creador_id = auth.uid()
      )
    )
    AND (
      evento_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.eventos e
        WHERE e.id = perfil_comunidad_publicaciones.evento_id
          AND e.creador_id = auth.uid()
      )
    )
  );
CREATE POLICY perfil_comunidad_publicaciones_delete_own ON public.perfil_comunidad_publicaciones
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY perfil_comunidad_respuestas_read ON public.perfil_comunidad_respuestas
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY perfil_comunidad_respuestas_insert_follower ON public.perfil_comunidad_respuestas
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM public.perfil_comunidad_publicaciones p
      WHERE p.id = perfil_comunidad_respuestas.publicacion_id
        AND (
          p.user_id = auth.uid()
          OR EXISTS (
            SELECT 1 FROM public.follows f
            WHERE f.follower_id = auth.uid()
              AND f.following_id = p.user_id
          )
        )
    )
  );
CREATE POLICY perfil_comunidad_respuestas_delete_own ON public.perfil_comunidad_respuestas
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY reel_views_own ON public.reel_views
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY reel_likes_read ON public.reel_likes FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY reel_likes_own_write ON public.reel_likes
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY reel_shares_own ON public.reel_shares
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY reel_comment_likes_read ON public.reel_comment_likes
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY reel_comment_likes_own_write ON public.reel_comment_likes
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY notifications_own ON public.notifications
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY content_reports_own ON public.content_reports
  FOR SELECT TO authenticated USING (auth.uid() = reporter_id);
CREATE POLICY content_reports_insert_own ON public.content_reports
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = reporter_id);

COMMIT;
