-- Ejecutar en Supabase SQL Editor sobre el schema public.
-- Alinea la base actual con el backend de eventos y reels.

ALTER TABLE eventos
ADD COLUMN IF NOT EXISTS precio NUMERIC(12, 2)
CHECK (precio IS NULL OR precio >= 0);

-- Compatibilidad con bases anteriores: titulo y descripcion pueden seguir
-- existiendo, pero ya no forman parte del contrato de creacion de eventos.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'eventos'
      AND column_name = 'titulo'
  ) THEN
    ALTER TABLE public.eventos
      ALTER COLUMN titulo DROP NOT NULL,
      ALTER COLUMN titulo DROP DEFAULT;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'eventos'
      AND column_name = 'descripcion'
  ) THEN
    ALTER TABLE public.eventos
      ALTER COLUMN descripcion DROP NOT NULL,
      ALTER COLUMN descripcion DROP DEFAULT;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS reels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    genero TEXT NOT NULL,
    duracion TEXT,
    portada_url TEXT,
    portada_path TEXT,
    audio_url TEXT NOT NULL,
    audio_path TEXT NOT NULL,
    color_principal TEXT CONSTRAINT reels_color_principal_formato_check
      CHECK (color_principal IS NULL OR color_principal ~ '^#[0-9a-fA-F]{6}$'),
    likes INTEGER NOT NULL DEFAULT 0,
    compartidos INTEGER NOT NULL DEFAULT 0,
    guardados INTEGER NOT NULL DEFAULT 0,
    visitas INTEGER NOT NULL DEFAULT 0,
    creador_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

ALTER TABLE reels
ADD COLUMN IF NOT EXISTS color_principal TEXT;

-- Los reels simplificados solo requieren titulo, genero y audio. Se conservan
-- las columnas antiguas si existen, pero dejan de bloquear nuevas altas.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'reels' AND column_name = 'album'
  ) THEN
    ALTER TABLE public.reels ALTER COLUMN album DROP NOT NULL;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'reels' AND column_name = 'descripcion'
  ) THEN
    ALTER TABLE public.reels ALTER COLUMN descripcion DROP NOT NULL;
  END IF;
END $$;

UPDATE reels
SET color_principal = NULL
WHERE color_principal IS NOT NULL
  AND color_principal !~ '^#[0-9a-fA-F]{6}$';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reels_color_principal_formato_check'
      AND conrelid = 'public.reels'::regclass
  ) THEN
    ALTER TABLE public.reels
      ADD CONSTRAINT reels_color_principal_formato_check
      CHECK (color_principal IS NULL OR color_principal ~ '^#[0-9a-fA-F]{6}$');
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS reels_creador_id_idx ON reels (creador_id);
CREATE INDEX IF NOT EXISTS reels_created_at_idx ON reels (created_at DESC);

CREATE TABLE IF NOT EXISTS reel_views (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reel_id BIGINT NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT reel_views_pkey PRIMARY KEY (user_id, reel_id)
);

CREATE INDEX IF NOT EXISTS idx_reel_views_reel_id ON reel_views (reel_id);

-- Storage requerido:
-- 1. Bucket publico llamado "eventos"
-- 2. Bucket publico llamado "reels"
