-- Ejecutar en Supabase SQL Editor sobre el schema public.
-- Alinea la base actual con el backend de eventos y reels.

CREATE TABLE IF NOT EXISTS generos (
    slug TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT true,
    orden SMALLINT NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

INSERT INTO generos (slug, nombre, activo, orden) VALUES
    ('pop', 'Pop', true, 1),
    ('rock', 'Rock', true, 2),
    ('edm', 'Electronica', true, 3),
    ('jazz', 'Jazz', true, 4),
    ('blues', 'Blues', true, 5),
    ('cumbia', 'Cumbia', true, 6),
    ('trap', 'Urbano', true, 7),
    ('metal', 'Metal', true, 8),
    ('folklore', 'Folklore', true, 9),
    ('alternativo', 'Alternativo', true, 10),
    ('punk', 'Punk', true, 11),
    ('reggae', 'Reggae', true, 12),
    ('latina', 'Latina', true, 13),
    ('otros', 'Otros', true, 14)
ON CONFLICT (slug) DO UPDATE
SET nombre = EXCLUDED.nombre,
    activo = EXCLUDED.activo,
    orden = EXCLUDED.orden;



ALTER TABLE eventos
ADD COLUMN IF NOT EXISTS precio NUMERIC(12, 2)
CHECK (precio IS NULL OR precio >= 0);

-- Compatibilidad con bases anteriores: titulo y descripcion pueden seguir
-- existiendo, pero ya no forman parte del contrato de creacion de eventos.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'eventos'
      AND column_name = 'titulo'
  ) THEN
    ALTER TABLE public.eventos
      ALTER COLUMN titulo DROP NOT NULL,
      ALTER COLUMN titulo DROP DEFAULT;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'eventos'
      AND column_name = 'descripcion'
  ) THEN
    ALTER TABLE public.eventos
      ALTER COLUMN descripcion DROP NOT NULL,
      ALTER COLUMN descripcion DROP DEFAULT;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS reels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    genero TEXT NOT NULL,
    duracion TEXT,
    portada_url TEXT,
    portada_path TEXT,
    audio_url TEXT NOT NULL,
    audio_path TEXT NOT NULL,
    color_principal TEXT CONSTRAINT reels_color_principal_formato_check
      CHECK (color_principal IS NULL OR color_principal ~ '^#[0-9a-fA-F]{6}$'),
    likes INTEGER NOT NULL DEFAULT 0,
    compartidos INTEGER NOT NULL DEFAULT 0,
    guardados INTEGER NOT NULL DEFAULT 0,
    visitas INTEGER NOT NULL DEFAULT 0,
    creador_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

ALTER TABLE reels
ADD COLUMN IF NOT EXISTS color_principal TEXT;

-- Los reels simplificados solo requieren titulo, genero y audio. Se conservan
-- las columnas antiguas si existen, pero dejan de bloquear nuevas altas.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'reels' AND column_name = 'album'
  ) THEN
    ALTER TABLE public.reels ALTER COLUMN album DROP NOT NULL;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'reels' AND column_name = 'descripcion'
  ) THEN
    ALTER TABLE public.reels ALTER COLUMN descripcion DROP NOT NULL;
  END IF;
END $$;

UPDATE reels
SET color_principal = NULL
WHERE color_principal IS NOT NULL
  AND color_principal !~ '^#[0-9a-fA-F]{6}$';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reels_color_principal_formato_check'
      AND conrelid = 'public.reels'::regclass
  ) THEN
    ALTER TABLE public.reels
      ADD CONSTRAINT reels_color_principal_formato_check
      CHECK (color_principal IS NULL OR color_principal ~ '^#[0-9a-fA-F]{6}$');
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS reels_creador_id_idx ON reels (creador_id);
CREATE INDEX IF NOT EXISTS reels_created_at_idx ON reels (created_at DESC);

INSERT INTO generos (slug, nombre, activo, orden)
SELECT DISTINCT lower(trim(genero)), initcap(lower(trim(genero))), false, 100
FROM reels
WHERE genero IS NOT NULL AND trim(genero) <> ''
ON CONFLICT (slug) DO NOTHING;

UPDATE reels SET genero = lower(trim(genero));

CREATE TABLE IF NOT EXISTS reel_generos (
    reel_id BIGINT NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
    genero TEXT NOT NULL REFERENCES generos(slug),
    posicion SMALLINT NOT NULL CHECK (posicion BETWEEN 1 AND 3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (reel_id, genero),
    UNIQUE (reel_id, posicion)
);

CREATE INDEX IF NOT EXISTS reel_generos_genero_reel_idx
    ON reel_generos (genero, reel_id);

INSERT INTO reel_generos (reel_id, genero, posicion)
SELECT id, lower(trim(genero)), 1 FROM reels
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS reel_views (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reel_id BIGINT NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT reel_views_pkey PRIMARY KEY (user_id, reel_id)
);

CREATE INDEX IF NOT EXISTS idx_reel_views_reel_id ON reel_views (reel_id);

-- Storage requerido:
-- 1. Bucket publico llamado "eventos"
-- 2. Bucket publico llamado "reels"
