-- Ejecutar en Supabase SQL Editor sobre el schema public.
-- Alinea la base actual con el backend de eventos y reels.

ALTER TABLE eventos
ADD COLUMN IF NOT EXISTS precio NUMERIC(12, 2)
CHECK (precio IS NULL OR precio >= 0);

CREATE TABLE IF NOT EXISTS reels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    album TEXT NOT NULL,
    genero TEXT NOT NULL,
    descripcion TEXT,
    duracion TEXT,
    portada_url TEXT,
    portada_path TEXT,
    audio_url TEXT NOT NULL,
    audio_path TEXT NOT NULL,
    likes INTEGER NOT NULL DEFAULT 0,
    compartidos INTEGER NOT NULL DEFAULT 0,
    guardados INTEGER NOT NULL DEFAULT 0,
    visitas INTEGER NOT NULL DEFAULT 0,
    creador_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS reels_creador_id_idx ON reels (creador_id);
CREATE INDEX IF NOT EXISTS reels_created_at_idx ON reels (created_at DESC);

CREATE TABLE IF NOT EXISTS reel_views (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reel_id BIGINT NOT NULL REFERENCES reels(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT reel_views_pkey PRIMARY KEY (user_id, reel_id)
);

CREATE INDEX IF NOT EXISTS idx_reel_views_reel_id ON reel_views (reel_id);

-- Storage requerido:
-- 1. Bucket publico llamado "eventos"
-- 2. Bucket publico llamado "reels"
