-- Esquema alineado con Supabase Auth y con el backend actual.
-- Ejecutar en el SQL editor de Supabase.

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    user_type TEXT NOT NULL CHECK (user_type IN ('musico', 'organizador', 'admin')),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    genero TEXT,
    lugar TEXT,
    fecha TIMESTAMPTZ NOT NULL,
    img_url TEXT,
    precio NUMERIC(12, 2),
    link TEXT,
    creador_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS event_organizers (
    event_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    added_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS event_organizers_user_id_idx
    ON event_organizers(user_id);
