-- Esquema alineado con Supabase Auth y con el backend actual.
-- Ejecutar en el SQL editor de Supabase.

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    user_type TEXT NOT NULL CHECK (user_type IN ('musico', 'organizador', 'admin')),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    genero TEXT,
    lugar TEXT,
    fecha TIMESTAMPTZ NOT NULL,
    img_url TEXT,
    link TEXT,
    creador_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);
