-- Esquema alineado con Supabase Auth y con el backend actual.
-- Ejecutar en el SQL editor de Supabase.

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL
      CHECK (username ~ '^[a-z0-9._-]{3,30}$'),
    user_type TEXT NOT NULL CHECK (user_type IN ('musico', 'organizador', 'admin')),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS generos (
    slug TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT true,
    orden SMALLINT NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

INSERT INTO generos (slug, nombre, activo, orden) VALUES
    ('pop', 'Pop', true, 1),
    ('rock', 'Rock', true, 2),
    ('edm', 'Electronica', true, 3),
    ('jazz', 'Jazz', true, 4),
    ('blues', 'Blues', true, 5),
    ('cumbia', 'Cumbia', true, 6),
    ('trap', 'Urbano', true, 7),
    ('metal', 'Metal', true, 8),
    ('folklore', 'Folklore', true, 9),
    ('alternativo', 'Alternativo', true, 10),
    ('punk', 'Punk', true, 11),
    ('reggae', 'Reggae', true, 12),
    ('latina', 'Latina', true, 13),
    ('otros', 'Otros', true, 99)
ON CONFLICT (slug) DO UPDATE
SET nombre = EXCLUDED.nombre, activo = EXCLUDED.activo, orden = EXCLUDED.orden;

CREATE TABLE IF NOT EXISTS eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genero TEXT NOT NULL,
    lugar TEXT,
    fecha TIMESTAMPTZ NOT NULL,
    img_url TEXT,
    precio NUMERIC(12, 2),
    link TEXT,
    creador_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS evento_generos (
    event_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
    genero TEXT NOT NULL REFERENCES generos(slug),
    posicion SMALLINT NOT NULL CHECK (posicion BETWEEN 1 AND 3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (event_id, genero),
    UNIQUE (event_id, posicion)
);

CREATE INDEX IF NOT EXISTS evento_generos_genero_event_idx
    ON evento_generos(genero, event_id);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_unique
    ON users (lower(username));

CREATE TABLE IF NOT EXISTS event_organizers (
    event_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    added_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS event_organizers_user_id_idx
    ON event_organizers(user_id);
