BEGIN;

-- La comunidad personal convive con los foros organizados por genero.

-- Guardados queda reservado exclusivamente para eventos.
DROP TABLE IF EXISTS public.reel_saves CASCADE;
ALTER TABLE public.reels DROP COLUMN IF EXISTS guardados;

ALTER TABLE public.content_reports
  DROP CONSTRAINT IF EXISTS content_reports_content_type_check;
ALTER TABLE public.content_reports
  ADD CONSTRAINT content_reports_content_type_check
  CHECK (content_type IN ('reel', 'evento', 'perfil', 'community_post', 'community_comment', 'profile_post', 'profile_post_reply'));

CREATE TABLE IF NOT EXISTS public.perfil_comunidad_publicaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  origen text NOT NULL DEFAULT 'manual'
    CHECK (origen IN ('manual', 'reel', 'evento')),
  texto text NOT NULL
    CHECK (length(trim(texto)) BETWEEN 1 AND 1000),
  reel_id bigint REFERENCES public.reels(id) ON DELETE CASCADE,
  evento_id bigint REFERENCES public.eventos(id) ON DELETE CASCADE,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT perfil_comunidad_un_adjunto_check
    CHECK (num_nonnulls(reel_id, evento_id) <= 1),
  CONSTRAINT perfil_comunidad_origen_adjunto_check
    CHECK (
      (origen = 'manual')
      OR (origen = 'reel' AND reel_id IS NOT NULL AND evento_id IS NULL)
      OR (origen = 'evento' AND evento_id IS NOT NULL AND reel_id IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.perfil_comunidad_respuestas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id bigint NOT NULL
    REFERENCES public.perfil_comunidad_publicaciones(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  parent_id bigint REFERENCES public.perfil_comunidad_respuestas(id) ON DELETE CASCADE,
  texto text NOT NULL
    CHECK (length(trim(texto)) BETWEEN 1 AND 800),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS perfil_comunidad_publicaciones_user_idx
  ON public.perfil_comunidad_publicaciones(user_id, created_at DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS perfil_comunidad_auto_reel_idx
  ON public.perfil_comunidad_publicaciones(reel_id)
  WHERE origen = 'reel';
CREATE UNIQUE INDEX IF NOT EXISTS perfil_comunidad_auto_evento_idx
  ON public.perfil_comunidad_publicaciones(evento_id)
  WHERE origen = 'evento';
CREATE INDEX IF NOT EXISTS perfil_comunidad_respuestas_publicacion_idx
  ON public.perfil_comunidad_respuestas(publicacion_id, created_at, id);
CREATE INDEX IF NOT EXISTS perfil_comunidad_respuestas_parent_idx
  ON public.perfil_comunidad_respuestas(parent_id);

CREATE OR REPLACE FUNCTION public.validar_padre_respuesta_perfil()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.parent_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.perfil_comunidad_respuestas padre
    WHERE padre.id = NEW.parent_id
      AND padre.publicacion_id = NEW.publicacion_id
  ) THEN
    RAISE EXCEPTION 'La respuesta citada no pertenece a esta publicacion.'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS perfil_comunidad_respuesta_padre_valido
  ON public.perfil_comunidad_respuestas;
CREATE TRIGGER perfil_comunidad_respuesta_padre_valido
BEFORE INSERT OR UPDATE OF parent_id, publicacion_id
ON public.perfil_comunidad_respuestas
FOR EACH ROW EXECUTE FUNCTION public.validar_padre_respuesta_perfil();

CREATE OR REPLACE FUNCTION public.crear_publicacion_automatica_perfil()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_TABLE_NAME = 'reels' THEN
    INSERT INTO public.perfil_comunidad_publicaciones (
      user_id, origen, texto, reel_id
    ) VALUES (
      NEW.creador_id,
      'reel',
      format('Publico una nueva preview: %s.', NEW.titulo),
      NEW.id
    )
    ON CONFLICT (reel_id) WHERE origen = 'reel' DO NOTHING;
  ELSIF TG_TABLE_NAME = 'eventos' THEN
    INSERT INTO public.perfil_comunidad_publicaciones (
      user_id, origen, texto, evento_id
    ) VALUES (
      NEW.creador_id,
      'evento',
      format('Creo un nuevo evento en %s.', COALESCE(NULLIF(NEW.lugar, ''), 'un lugar a confirmar')),
      NEW.id
    )
    ON CONFLICT (evento_id) WHERE origen = 'evento' DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS perfil_comunidad_reel_creado ON public.reels;
CREATE TRIGGER perfil_comunidad_reel_creado
AFTER INSERT ON public.reels
FOR EACH ROW EXECUTE FUNCTION public.crear_publicacion_automatica_perfil();

DROP TRIGGER IF EXISTS perfil_comunidad_evento_creado ON public.eventos;
CREATE TRIGGER perfil_comunidad_evento_creado
AFTER INSERT ON public.eventos
FOR EACH ROW EXECUTE FUNCTION public.crear_publicacion_automatica_perfil();

-- Completa la comunidad con el contenido que ya existia antes de la migracion.
INSERT INTO public.perfil_comunidad_publicaciones (user_id, origen, texto, reel_id, created_at)
SELECT
  r.creador_id,
  'reel',
  format('Publico una nueva preview: %s.', r.titulo),
  r.id,
  r.created_at
FROM public.reels r
WHERE r.creador_id IS NOT NULL
ON CONFLICT (reel_id) WHERE origen = 'reel' DO NOTHING;

INSERT INTO public.perfil_comunidad_publicaciones (user_id, origen, texto, evento_id, created_at)
SELECT
  e.creador_id,
  'evento',
  format('Creo un nuevo evento en %s.', COALESCE(NULLIF(e.lugar, ''), 'un lugar a confirmar')),
  e.id,
  COALESCE(e.created_at, timezone('utc'::text, now()))
FROM public.eventos e
WHERE e.creador_id IS NOT NULL
ON CONFLICT (evento_id) WHERE origen = 'evento' DO NOTHING;

ALTER TABLE public.perfil_comunidad_publicaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfil_comunidad_respuestas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS perfil_comunidad_publicaciones_read ON public.perfil_comunidad_publicaciones;
DROP POLICY IF EXISTS perfil_comunidad_publicaciones_insert_own ON public.perfil_comunidad_publicaciones;
DROP POLICY IF EXISTS perfil_comunidad_publicaciones_update_own ON public.perfil_comunidad_publicaciones;
DROP POLICY IF EXISTS perfil_comunidad_publicaciones_delete_own ON public.perfil_comunidad_publicaciones;
DROP POLICY IF EXISTS perfil_comunidad_respuestas_read ON public.perfil_comunidad_respuestas;
DROP POLICY IF EXISTS perfil_comunidad_respuestas_insert_follower ON public.perfil_comunidad_respuestas;
DROP POLICY IF EXISTS perfil_comunidad_respuestas_delete_own ON public.perfil_comunidad_respuestas;

CREATE POLICY perfil_comunidad_publicaciones_read
  ON public.perfil_comunidad_publicaciones
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY perfil_comunidad_publicaciones_insert_own
  ON public.perfil_comunidad_publicaciones
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND origen = 'manual'
    AND (
      reel_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.reels r
        WHERE r.id = perfil_comunidad_publicaciones.reel_id
          AND r.creador_id = auth.uid()
      )
    )
    AND (
      evento_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.eventos e
        WHERE e.id = perfil_comunidad_publicaciones.evento_id
          AND e.creador_id = auth.uid()
      )
    )
  );

CREATE POLICY perfil_comunidad_publicaciones_update_own
  ON public.perfil_comunidad_publicaciones
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (
    auth.uid() = user_id
    AND origen = 'manual'
    AND (
      reel_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.reels r
        WHERE r.id = perfil_comunidad_publicaciones.reel_id
          AND r.creador_id = auth.uid()
      )
    )
    AND (
      evento_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.eventos e
        WHERE e.id = perfil_comunidad_publicaciones.evento_id
          AND e.creador_id = auth.uid()
      )
    )
  );

CREATE POLICY perfil_comunidad_publicaciones_delete_own
  ON public.perfil_comunidad_publicaciones
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY perfil_comunidad_respuestas_read
  ON public.perfil_comunidad_respuestas
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY perfil_comunidad_respuestas_insert_follower
  ON public.perfil_comunidad_respuestas
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1
      FROM public.perfil_comunidad_publicaciones p
      WHERE p.id = perfil_comunidad_respuestas.publicacion_id
        AND (
          p.user_id = auth.uid()
          OR EXISTS (
            SELECT 1 FROM public.follows f
            WHERE f.follower_id = auth.uid()
              AND f.following_id = p.user_id
          )
        )
    )
  );

CREATE POLICY perfil_comunidad_respuestas_delete_own
  ON public.perfil_comunidad_respuestas
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

GRANT SELECT ON public.perfil_comunidad_publicaciones TO anon, authenticated;
GRANT SELECT ON public.perfil_comunidad_respuestas TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.perfil_comunidad_publicaciones TO authenticated;
GRANT INSERT, DELETE ON public.perfil_comunidad_respuestas TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

COMMIT;
