-- SONDAR beta: mensajeria, ubicacion PostGIS y aprendizaje del feed.
-- Migracion aditiva e idempotente. Ejecutar despues de activar PostGIS en `gis`.

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('sondar:sistemas-beta:v1'));

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_extension e
    JOIN pg_namespace n ON n.oid = e.extnamespace
    WHERE e.extname = 'postgis' AND n.nspname = 'gis'
  ) THEN
    RAISE EXCEPTION 'PostGIS debe estar instalado en el esquema gis antes de ejecutar esta migracion';
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- 1. Ubicacion de eventos indexada espacialmente
-- ---------------------------------------------------------------------------

ALTER TABLE public.eventos
  ADD COLUMN IF NOT EXISTS ubicacion_geog gis.geography(Point, 4326);

CREATE OR REPLACE FUNCTION public.sincronizar_ubicacion_evento()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF NEW.latitud IS NULL OR NEW.longitud IS NULL THEN
    NEW.ubicacion_geog := NULL;
  ELSE
    NEW.ubicacion_geog := gis.ST_SetSRID(
      gis.ST_MakePoint(NEW.longitud, NEW.latitud),
      4326
    )::gis.geography;
  END IF;
  RETURN NEW;
END;
$$;

UPDATE public.eventos
SET ubicacion_geog = gis.ST_SetSRID(
  gis.ST_MakePoint(longitud, latitud),
  4326
)::gis.geography
WHERE latitud IS NOT NULL
  AND longitud IS NOT NULL
  AND ubicacion_geog IS NULL;

DROP TRIGGER IF EXISTS eventos_sincronizar_ubicacion ON public.eventos;
CREATE TRIGGER eventos_sincronizar_ubicacion
BEFORE INSERT OR UPDATE OF latitud, longitud
ON public.eventos
FOR EACH ROW
EXECUTE FUNCTION public.sincronizar_ubicacion_evento();

CREATE INDEX IF NOT EXISTS eventos_ubicacion_geog_gist_idx
  ON public.eventos USING gist (ubicacion_geog);

-- ---------------------------------------------------------------------------
-- 2. Mensajeria directa
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL DEFAULT 'direct' CHECK (kind IN ('direct')),
  direct_key text NOT NULL UNIQUE,
  created_by uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  last_message_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS conversations_last_message_idx
  ON public.conversations (last_message_at DESC, id);

CREATE TABLE IF NOT EXISTS public.conversation_members (
  conversation_id uuid NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  joined_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  last_read_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  muted boolean NOT NULL DEFAULT false,
  archived_at timestamptz,
  PRIMARY KEY (conversation_id, user_id)
);

CREATE INDEX IF NOT EXISTS conversation_members_user_idx
  ON public.conversation_members (user_id, conversation_id);

CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id uuid NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  body text NOT NULL,
  reply_to_id bigint REFERENCES public.messages(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  edited_at timestamptz,
  deleted_at timestamptz,
  CONSTRAINT messages_body_length_check CHECK (
    deleted_at IS NOT NULL OR length(trim(body)) BETWEEN 1 AND 2000
  )
);

CREATE INDEX IF NOT EXISTS messages_conversation_cursor_idx
  ON public.messages (conversation_id, id DESC);
CREATE INDEX IF NOT EXISTS messages_sender_rate_idx
  ON public.messages (sender_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.is_conversation_member(
  conversation_uuid uuid,
  member_uuid uuid DEFAULT auth.uid()
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.conversation_members cm
    WHERE cm.conversation_id = conversation_uuid
      AND cm.user_id = member_uuid
  );
$$;

REVOKE ALL ON FUNCTION public.is_conversation_member(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_conversation_member(uuid, uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.actualizar_conversacion_por_mensaje()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.conversations
  SET last_message_at = NEW.created_at,
      updated_at = timezone('utc'::text, now())
  WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS messages_actualizar_conversacion ON public.messages;
CREATE TRIGGER messages_actualizar_conversacion
AFTER INSERT ON public.messages
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_conversacion_por_mensaje();

-- Broadcast desde la base: los clientes no dependen de escuchar toda la tabla.
CREATE OR REPLACE FUNCTION public.broadcast_message_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  conversation_uuid uuid;
BEGIN
  conversation_uuid := COALESCE(NEW.conversation_id, OLD.conversation_id);
  PERFORM realtime.broadcast_changes(
    'conversation:' || conversation_uuid::text,
    TG_OP,
    TG_OP,
    TG_TABLE_NAME,
    TG_TABLE_SCHEMA,
    NEW,
    OLD
  );
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS messages_broadcast_change ON public.messages;
CREATE TRIGGER messages_broadcast_change
AFTER INSERT OR UPDATE OR DELETE ON public.messages
FOR EACH ROW
EXECUTE FUNCTION public.broadcast_message_change();

CREATE OR REPLACE FUNCTION public.broadcast_conversation_read_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF OLD.last_read_at IS DISTINCT FROM NEW.last_read_at THEN
    PERFORM realtime.send(
      jsonb_build_object(
        'user_id', NEW.user_id,
        'last_read_at', NEW.last_read_at
      ),
      'read',
      'conversation:' || NEW.conversation_id::text,
      true
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS conversation_members_broadcast_read ON public.conversation_members;
CREATE TRIGGER conversation_members_broadcast_read
AFTER UPDATE OF last_read_at ON public.conversation_members
FOR EACH ROW
EXECUTE FUNCTION public.broadcast_conversation_read_change();

-- ---------------------------------------------------------------------------
-- 3. Sesiones de escucha y afinidad aprendida
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.reel_playback_sessions (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reel_id bigint NOT NULL REFERENCES public.reels(id) ON DELETE CASCADE,
  listened_ms integer NOT NULL DEFAULT 0 CHECK (listened_ms BETWEEN 0 AND 3600000),
  duration_ms integer CHECK (duration_ms IS NULL OR duration_ms BETWEEN 1 AND 3600000),
  completion_ratio numeric(5, 4) NOT NULL DEFAULT 0
    CHECK (completion_ratio BETWEEN 0 AND 1),
  completed boolean NOT NULL DEFAULT false,
  skipped boolean NOT NULL DEFAULT false,
  replay_count smallint NOT NULL DEFAULT 0 CHECK (replay_count BETWEEN 0 AND 100),
  started_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (id, user_id)
);

CREATE INDEX IF NOT EXISTS reel_playback_user_recent_idx
  ON public.reel_playback_sessions (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS reel_playback_reel_idx
  ON public.reel_playback_sessions (reel_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.user_genre_affinity (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  genre text NOT NULL,
  behavioral_score numeric(10, 3) NOT NULL DEFAULT 0,
  listening_sessions integer NOT NULL DEFAULT 0,
  last_interaction_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, genre)
);

CREATE INDEX IF NOT EXISTS user_genre_affinity_score_idx
  ON public.user_genre_affinity (user_id, behavioral_score DESC);

CREATE OR REPLACE FUNCTION public.playback_signal_score(
  listened integer,
  ratio numeric,
  was_completed boolean,
  was_skipped boolean,
  replays smallint
)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = ''
AS $$
  SELECT LEAST(16::numeric, GREATEST(0, COALESCE(listened, 0))::numeric / 3000)
       + LEAST(14::numeric, GREATEST(0, COALESCE(ratio, 0)) * 14)
       + CASE WHEN COALESCE(was_completed, false) THEN 5 ELSE 0 END
       + LEAST(8::numeric, GREATEST(0, COALESCE(replays, 0))::numeric * 4)
       - CASE
           WHEN COALESCE(was_skipped, false) AND COALESCE(listened, 0) < 5000 THEN 9
           WHEN COALESCE(was_skipped, false) THEN 3
           ELSE 0
         END;
$$;

CREATE OR REPLACE FUNCTION public.actualizar_afinidad_desde_escucha()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  genre_value text;
  delta numeric := 0;
  session_delta integer := 0;
BEGIN
  SELECT lower(r.genero) INTO genre_value
  FROM public.reels r
  WHERE r.id = COALESCE(NEW.reel_id, OLD.reel_id);

  IF genre_value IS NULL OR genre_value = '' THEN
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    delta := public.playback_signal_score(
      NEW.listened_ms, NEW.completion_ratio, NEW.completed, NEW.skipped, NEW.replay_count
    );
    session_delta := 1;
  ELSIF TG_OP = 'UPDATE' THEN
    delta := public.playback_signal_score(
      NEW.listened_ms, NEW.completion_ratio, NEW.completed, NEW.skipped, NEW.replay_count
    ) - public.playback_signal_score(
      OLD.listened_ms, OLD.completion_ratio, OLD.completed, OLD.skipped, OLD.replay_count
    );
  ELSE
    delta := -public.playback_signal_score(
      OLD.listened_ms, OLD.completion_ratio, OLD.completed, OLD.skipped, OLD.replay_count
    );
    session_delta := -1;
  END IF;

  INSERT INTO public.user_genre_affinity (
    user_id, genre, behavioral_score, listening_sessions, last_interaction_at
  ) VALUES (
    COALESCE(NEW.user_id, OLD.user_id),
    genre_value,
    GREATEST(-50::numeric, LEAST(250::numeric, delta)),
    GREATEST(0, session_delta),
    timezone('utc'::text, now())
  )
  ON CONFLICT (user_id, genre) DO UPDATE
  SET behavioral_score = GREATEST(
        -50::numeric,
        LEAST(250::numeric, public.user_genre_affinity.behavioral_score + delta)
      ),
      listening_sessions = GREATEST(
        0,
        public.user_genre_affinity.listening_sessions + session_delta
      ),
      last_interaction_at = timezone('utc'::text, now());

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reel_playback_actualizar_afinidad ON public.reel_playback_sessions;
CREATE TRIGGER reel_playback_actualizar_afinidad
AFTER INSERT OR UPDATE OR DELETE ON public.reel_playback_sessions
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_afinidad_desde_escucha();

-- ---------------------------------------------------------------------------
-- 4. RLS. El backend sigue siendo la autoridad de escritura; estas politicas
--    tambien autorizan los canales privados de Realtime.
-- ---------------------------------------------------------------------------

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_playback_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_genre_affinity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS conversations_member_read ON public.conversations;
CREATE POLICY conversations_member_read ON public.conversations
FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1
  WHERE public.is_conversation_member(conversations.id, (SELECT auth.uid()))
));

DROP POLICY IF EXISTS conversation_members_member_read ON public.conversation_members;
CREATE POLICY conversation_members_member_read ON public.conversation_members
FOR SELECT TO authenticated
USING (public.is_conversation_member(
  conversation_members.conversation_id,
  (SELECT auth.uid())
));

DROP POLICY IF EXISTS messages_member_read ON public.messages;
CREATE POLICY messages_member_read ON public.messages
FOR SELECT TO authenticated
USING (public.is_conversation_member(messages.conversation_id, (SELECT auth.uid())));

DROP POLICY IF EXISTS messages_member_insert ON public.messages;
CREATE POLICY messages_member_insert ON public.messages
FOR INSERT TO authenticated
WITH CHECK (
  sender_id = (SELECT auth.uid())
  AND public.is_conversation_member(messages.conversation_id, (SELECT auth.uid()))
);

DROP POLICY IF EXISTS messages_sender_change ON public.messages;
CREATE POLICY messages_sender_change ON public.messages
FOR UPDATE TO authenticated
USING (sender_id = (SELECT auth.uid()))
WITH CHECK (
  sender_id = (SELECT auth.uid())
  AND public.is_conversation_member(messages.conversation_id, (SELECT auth.uid()))
);

DROP POLICY IF EXISTS reel_playback_own ON public.reel_playback_sessions;
CREATE POLICY reel_playback_own ON public.reel_playback_sessions
FOR ALL TO authenticated
USING (user_id = (SELECT auth.uid()))
WITH CHECK (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS user_genre_affinity_own_read ON public.user_genre_affinity;
CREATE POLICY user_genre_affinity_own_read ON public.user_genre_affinity
FOR SELECT TO authenticated
USING (user_id = (SELECT auth.uid()));

GRANT SELECT ON public.conversations, public.conversation_members, public.messages,
  public.reel_playback_sessions, public.user_genre_affinity TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.conversations, public.conversation_members,
  public.messages, public.reel_playback_sessions, public.user_genre_affinity FROM authenticated;

DROP POLICY IF EXISTS sondar_conversation_realtime_read ON realtime.messages;
CREATE POLICY sondar_conversation_realtime_read ON realtime.messages
FOR SELECT TO authenticated
USING (
  extension IN ('broadcast', 'presence')
  AND EXISTS (
    SELECT 1
    FROM public.conversation_members cm
    WHERE cm.user_id = (SELECT auth.uid())
      AND 'conversation:' || cm.conversation_id::text = realtime.topic()
  )
);

DROP POLICY IF EXISTS sondar_conversation_realtime_send ON realtime.messages;
CREATE POLICY sondar_conversation_realtime_send ON realtime.messages
FOR INSERT TO authenticated
WITH CHECK (
  extension IN ('broadcast', 'presence')
  AND EXISTS (
    SELECT 1
    FROM public.conversation_members cm
    WHERE cm.user_id = (SELECT auth.uid())
      AND 'conversation:' || cm.conversation_id::text = realtime.topic()
  )
);

COMMIT;
