SET local check_function_bodies = off;

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "service_role";

CREATE SCHEMA "gis";

CREATE EXTENSION "postgis" SCHEMA "gis";

CREATE TABLE "public"."comunidad_comentario_guardados" (
  "user_id"       uuid                     NOT NULL,
  "comentario_id" bigint                   NOT NULL,
  "created_at"    timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "comunidad_comentario_guardados_pkey" PRIMARY KEY (user_id, comentario_id)
);

CREATE TABLE "public"."comunidad_comentario_likes" (
  "user_id"       uuid                     NOT NULL,
  "comentario_id" bigint                   NOT NULL,
  "created_at"    timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "comunidad_comentario_likes_pkey" PRIMARY KEY (user_id, comentario_id)
);

ALTER TABLE "public"."comunidad_comentario_likes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."comunidad_comentarios" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "publicacion_id" bigint                   NOT NULL,
  "user_id"        uuid                     NOT NULL,
  "parent_id"      bigint,
  "texto"          text                     NOT NULL,
  "created_at"     timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "likes"          integer                  NOT NULL DEFAULT 0,
  "responde_a"     text,
  CONSTRAINT "comunidad_comentarios_pkey" PRIMARY KEY (id),
  CONSTRAINT "comunidad_comentarios_texto_check" CHECK ((length(TRIM(BOTH FROM texto)) > 0))
);

ALTER TABLE "public"."comunidad_comentarios"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."comunidad_miembros" (
  "comunidad_id"         text                     NOT NULL,
  "user_id"              uuid                     NOT NULL,
  "nivel_notificaciones" text                     NOT NULL DEFAULT 'todas'::text,
  "created_at"           timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "comunidad_miembros_nivel_notificaciones_check" CHECK ((nivel_notificaciones = ANY (ARRAY['todas'::text, 'relevantes'::text, 'silenciadas'::text]))),
  CONSTRAINT "comunidad_miembros_pkey" PRIMARY KEY (comunidad_id, user_id)
);

ALTER TABLE "public"."comunidad_miembros"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."comunidad_publicacion_guardados" (
  "user_id"        uuid                     NOT NULL,
  "publicacion_id" bigint                   NOT NULL,
  "created_at"     timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "comunidad_publicacion_guardados_pkey" PRIMARY KEY (user_id, publicacion_id)
);

ALTER TABLE "public"."comunidad_publicacion_guardados"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."comunidad_publicacion_likes" (
  "user_id"        uuid                     NOT NULL,
  "publicacion_id" bigint                   NOT NULL,
  "created_at"     timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "comunidad_publicacion_likes_pkey" PRIMARY KEY (user_id, publicacion_id)
);

ALTER TABLE "public"."comunidad_publicacion_likes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."comunidad_publicaciones" (
  "id"                 bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "comunidad_id"       text                     NOT NULL,
  "user_id"            uuid                     NOT NULL,
  "tipo"               text                     NOT NULL DEFAULT 'reciente'::text,
  "titulo"             text                     NOT NULL,
  "texto"              text                     NOT NULL,
  "etiqueta"           text,
  "fijada"             boolean                  NOT NULL DEFAULT false,
  "created_at"         timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "evento_asociado_id" text,
  "reel_asociado_id"   text,
  "likes"              integer                  NOT NULL DEFAULT 0,
  "guardados"          integer                  NOT NULL DEFAULT 0,
  "updated_at"         timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "adjuntos"           jsonb                    NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT "comunidad_publicaciones_pkey" PRIMARY KEY (id),
  CONSTRAINT "comunidad_publicaciones_texto_check" CHECK ((length(TRIM(BOTH FROM texto)) > 0)),
  CONSTRAINT "comunidad_publicaciones_tipo_check" CHECK ((tipo = ANY (ARRAY['destacado'::text, 'reciente'::text, 'popular'::text, 'preguntas'::text]))),
  CONSTRAINT "comunidad_publicaciones_titulo_check" CHECK ((length(TRIM(BOTH FROM titulo)) > 0))
);

ALTER TABLE "public"."comunidad_publicaciones"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."comunidades" (
  "id"          text                     NOT NULL,
  "nombre"      text                     NOT NULL,
  "titulo"      text                     NOT NULL,
  "genero"      text                     NOT NULL,
  "descripcion" text                     NOT NULL,
  "portada_url" text,
  "activa"      boolean                  NOT NULL DEFAULT true,
  "created_at"  timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "comunidades_genero_key" UNIQUE (genero),
  CONSTRAINT "comunidades_nombre_key" UNIQUE (nombre),
  CONSTRAINT "comunidades_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."comunidades"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."content_reports" (
  "id"               bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reporter_id"      uuid                     NOT NULL,
  "reported_user_id" uuid,
  "content_type"     text                     NOT NULL,
  "content_id"       text                     NOT NULL,
  "reason"           text                     NOT NULL DEFAULT 'contenido_inapropiado'::text,
  "status"           text                     NOT NULL DEFAULT 'pendiente'::text,
  "created_at"       timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "details"          text                     NOT NULL DEFAULT ''::text,
  CONSTRAINT "content_reports_content_type_check"
    CHECK
    ((content_type = ANY (ARRAY['reel'::text, 'evento'::text, 'perfil'::text, 'community_post'::text, 'community_comment'::text, 'profile_post'::text,
    'profile_post_reply'::text]))),
  CONSTRAINT "content_reports_pkey" PRIMARY KEY (id),
  CONSTRAINT "content_reports_unique" UNIQUE (reporter_id, content_type, content_id)
);

ALTER TABLE "public"."content_reports"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."conversation_members" (
  "conversation_id"   uuid                     NOT NULL,
  "user_id"           uuid                     NOT NULL,
  "joined_at"         timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "last_read_at"      timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "muted"             boolean                  NOT NULL DEFAULT false,
  "archived_at"       timestamp with time zone,
  "last_delivered_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "conversation_members_pkey" PRIMARY KEY (conversation_id, user_id)
);

ALTER TABLE "public"."conversation_members"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."conversations" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "kind"            text                     NOT NULL DEFAULT 'direct'::text,
  "direct_key"      text                     NOT NULL,
  "created_by"      uuid,
  "created_at"      timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "last_message_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "conversations_direct_key_key" UNIQUE (direct_key),
  CONSTRAINT "conversations_kind_check" CHECK ((kind = 'direct'::text)),
  CONSTRAINT "conversations_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."conversations"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."event_organizers" (
  "event_id"   bigint                   NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "added_by"   uuid                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "event_organizers_pkey" PRIMARY KEY (event_id, user_id)
);

ALTER TABLE "public"."event_organizers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."event_saves" (
  "user_id"    uuid                     NOT NULL,
  "event_id"   bigint                   NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "event_saves_pkey" PRIMARY KEY (user_id, event_id)
);

ALTER TABLE "public"."event_saves"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."evento_generos" (
  "event_id"   bigint                   NOT NULL,
  "genero"     text                     NOT NULL,
  "posicion"   smallint                 NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "evento_generos_event_id_posicion_key" UNIQUE (event_id, posicion),
  CONSTRAINT "evento_generos_pkey" PRIMARY KEY (event_id, genero),
  CONSTRAINT "evento_generos_posicion_check" CHECK (((posicion >= 1) AND (posicion <= 3)))
);

ALTER TABLE "public"."evento_generos"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."eventos" (
  "id"             bigint                    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "genero"         text                      NOT NULL,
  "lugar"          text,
  "fecha"          timestamp with time zone  NOT NULL,
  "img_url"        text,
  "link"           text,
  "creador_id"     uuid                      NOT NULL,
  "latitud"        double precision,
  "longitud"       double precision,
  "created_at"     timestamp with time zone  DEFAULT timezone('utc'::text, now()),
  "precio"         numeric(12,2),
  "img_path"       text,
  "ubicacion_geog" gis.geography(Point,4326),
  "descripcion"    text,
  "titulo"         text                      NOT NULL DEFAULT 'Evento SONDAR'::text,
  CONSTRAINT "eventos_pkey" PRIMARY KEY (id),
  CONSTRAINT "eventos_precio_check" CHECK (((precio IS NULL) OR (precio >= (0)::numeric)))
);

ALTER TABLE "public"."eventos"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."follows" (
  "follower_id"  uuid                     NOT NULL,
  "following_id" uuid                     NOT NULL,
  "created_at"   timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "follows_no_self" CHECK ((follower_id <> following_id)),
  CONSTRAINT "follows_pkey" PRIMARY KEY (follower_id, following_id)
);

ALTER TABLE "public"."follows"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."generos" (
  "slug"       text                     NOT NULL,
  "nombre"     text                     NOT NULL,
  "activo"     boolean                  NOT NULL DEFAULT true,
  "orden"      smallint                 NOT NULL DEFAULT 100,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "generos_nombre_check" CHECK ((length(TRIM(BOTH FROM nombre)) > 0)),
  CONSTRAINT "generos_pkey" PRIMARY KEY (slug),
  CONSTRAINT "generos_slug_check" CHECK ((length(TRIM(BOTH FROM slug)) > 0))
);

ALTER TABLE "public"."generos"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."messages" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "conversation_id" uuid                     NOT NULL,
  "sender_id"       uuid,
  "body"            text                     NOT NULL,
  "reply_to_id"     bigint,
  "created_at"      timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "edited_at"       timestamp with time zone,
  "deleted_at"      timestamp with time zone,
  CONSTRAINT "messages_body_length_check" CHECK (((deleted_at IS NOT NULL) OR ((length(TRIM(BOTH FROM body)) >= 1) AND (length(TRIM(BOTH FROM body)) <= 2000)))),
  CONSTRAINT "messages_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."messages"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."notification_mutes" (
  "user_id"       uuid                     NOT NULL,
  "muted_user_id" uuid                     NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "notification_mutes_no_self" CHECK ((user_id <> muted_user_id)),
  CONSTRAINT "notification_mutes_pkey" PRIMARY KEY (user_id, muted_user_id)
);

ALTER TABLE "public"."notification_mutes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."notifications" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"     uuid                     NOT NULL,
  "actor_id"    uuid,
  "type"        text                     NOT NULL,
  "title"       text                     NOT NULL,
  "body"        text                     NOT NULL DEFAULT ''::text,
  "target_url"  text                     NOT NULL DEFAULT ''::text,
  "unique_key"  text,
  "read_at"     timestamp with time zone,
  "created_at"  timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "entity_type" text,
  "entity_id"   text,
  "metadata"    jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "notifications_body_check" CHECK ((length(body) <= 500)),
  CONSTRAINT "notifications_pkey" PRIMARY KEY (id),
  CONSTRAINT "notifications_title_check" CHECK ((length(title) <= 120)),
  CONSTRAINT "notifications_unique_key_key" UNIQUE (unique_key)
);

ALTER TABLE "public"."notifications"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."perfil_comunidad_publicaciones" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "origen"     text                     NOT NULL DEFAULT 'manual'::text,
  "texto"      text                     NOT NULL,
  "reel_id"    bigint,
  "evento_id"  bigint,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "updated_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "perfil_comunidad_origen_adjunto_check" CHECK (((origen = 'manual'::text) OR ((origen = 'reel'::text) AND (reel_id IS
    NOT NULL) AND (evento_id IS NULL)) OR ((origen = 'evento'::text) AND (evento_id IS NOT NULL) AND (reel_id IS NULL)))),
  CONSTRAINT "perfil_comunidad_publicaciones_origen_check" CHECK ((origen = ANY (ARRAY['manual'::text, 'reel'::text, 'evento'::text]))),
  CONSTRAINT "perfil_comunidad_publicaciones_pkey" PRIMARY KEY (id),
  CONSTRAINT "perfil_comunidad_publicaciones_texto_check" CHECK (((length(TRIM(BOTH FROM texto)) >= 1) AND (length(TRIM(BOTH FROM texto)) <= 1000))),
  CONSTRAINT "perfil_comunidad_un_adjunto_check" CHECK ((num_nonnulls(reel_id, evento_id) <= 1))
);

ALTER TABLE "public"."perfil_comunidad_publicaciones"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."perfil_comunidad_respuestas" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "publicacion_id" bigint                   NOT NULL,
  "user_id"        uuid                     NOT NULL,
  "parent_id"      bigint,
  "texto"          text                     NOT NULL,
  "created_at"     timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "perfil_comunidad_respuestas_pkey" PRIMARY KEY (id),
  CONSTRAINT "perfil_comunidad_respuestas_texto_check" CHECK (((length(TRIM(BOTH FROM texto)) >= 1) AND (length(TRIM(BOTH FROM texto)) <= 800)))
);

ALTER TABLE "public"."perfil_comunidad_respuestas"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profile_community_comments" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "post_id"    bigint                   NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "texto"      text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "profile_community_comments_pkey" PRIMARY KEY (id),
  CONSTRAINT "profile_community_comments_texto_check" CHECK ((length(TRIM(BOTH FROM texto)) > 0))
);

CREATE TABLE "public"."profile_community_posts" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"         uuid                     NOT NULL,
  "texto"           text                     NOT NULL DEFAULT ''::text,
  "attachment_type" text,
  "reel_id"         bigint,
  "event_id"        bigint,
  "created_at"      timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "profile_community_posts_attachment_type_check" CHECK ((attachment_type = ANY (ARRAY['reel'::text, 'evento'::text]))),
  CONSTRAINT "profile_community_posts_attachment"
    CHECK ((((attachment_type IS NULL) AND (reel_id IS NULL) AND (event_id IS NULL)) OR ((attachment_type = 'reel'::text) AND (reel_id IS
    NOT NULL) AND (event_id IS NULL)) OR ((attachment_type = 'evento'::text) AND (event_id IS NOT NULL) AND (reel_id IS NULL)))),
  CONSTRAINT "profile_community_posts_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."reel_comment_likes" (
  "user_id"    uuid                     NOT NULL,
  "comment_id" bigint                   NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "reel_comment_likes_pkey" PRIMARY KEY (user_id, comment_id)
);

ALTER TABLE "public"."reel_comment_likes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reel_comments" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "reel_id"    bigint                   NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "parent_id"  bigint,
  "texto"      text                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "responde_a" text,
  "likes"      integer                  NOT NULL DEFAULT 0,
  CONSTRAINT "reel_comments_pkey" PRIMARY KEY (id),
  CONSTRAINT "reel_comments_texto_check" CHECK ((length(TRIM(BOTH FROM texto)) > 0))
);

ALTER TABLE "public"."reel_comments"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reel_generos" (
  "reel_id"    bigint                   NOT NULL,
  "genero"     text                     NOT NULL,
  "posicion"   smallint                 NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "reel_generos_pkey" PRIMARY KEY (reel_id, genero),
  CONSTRAINT "reel_generos_posicion_check" CHECK (((posicion >= 1) AND (posicion <= 3))),
  CONSTRAINT "reel_generos_reel_id_posicion_key" UNIQUE (reel_id, posicion)
);

ALTER TABLE "public"."reel_generos"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reel_likes" (
  "user_id"    uuid                     NOT NULL,
  "reel_id"    bigint                   NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "reel_likes_pkey" PRIMARY KEY (user_id, reel_id)
);

ALTER TABLE "public"."reel_likes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reel_playback_sessions" (
  "id"               uuid                     NOT NULL,
  "user_id"          uuid                     NOT NULL,
  "reel_id"          bigint                   NOT NULL,
  "listened_ms"      integer                  NOT NULL DEFAULT 0,
  "duration_ms"      integer,
  "completion_ratio" numeric(5,4)             NOT NULL DEFAULT 0,
  "completed"        boolean                  NOT NULL DEFAULT false,
  "skipped"          boolean                  NOT NULL DEFAULT false,
  "replay_count"     smallint                 NOT NULL DEFAULT 0,
  "started_at"       timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "updated_at"       timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "reel_playback_sessions_completion_ratio_check" CHECK (((completion_ratio >= (0)::numeric) AND (completion_ratio <= (1)::numeric))),
  CONSTRAINT "reel_playback_sessions_duration_ms_check" CHECK (((duration_ms IS NULL) OR ((duration_ms >= 1) AND (duration_ms <= 3600000)))),
  CONSTRAINT "reel_playback_sessions_listened_ms_check" CHECK (((listened_ms >= 0) AND (listened_ms <= 3600000))),
  CONSTRAINT "reel_playback_sessions_pkey" PRIMARY KEY (id),
  CONSTRAINT "reel_playback_sessions_replay_count_check" CHECK (((replay_count >= 0) AND (replay_count <= 100)))
);

ALTER TABLE "public"."reel_playback_sessions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reel_saves" (
  "user_id"    uuid                     NOT NULL,
  "reel_id"    bigint                   NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "reel_saves_pkey" PRIMARY KEY (user_id, reel_id)
);

ALTER TABLE "public"."reel_saves"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reel_shares" (
  "user_id"    uuid                     NOT NULL,
  "reel_id"    bigint                   NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "reel_shares_pkey" PRIMARY KEY (user_id, reel_id)
);

ALTER TABLE "public"."reel_shares"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reel_views" (
  "user_id"    uuid                     NOT NULL,
  "reel_id"    bigint                   NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "reel_views_pkey" PRIMARY KEY (user_id, reel_id)
);

ALTER TABLE "public"."reel_views"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reels" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "titulo"          text                     NOT NULL,
  "genero"          text                     NOT NULL,
  "duracion"        text,
  "portada_url"     text,
  "portada_path"    text,
  "audio_url"       text                     NOT NULL,
  "audio_path"      text                     NOT NULL,
  "creador_id"      uuid                     NOT NULL,
  "created_at"      timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "color_principal" text,
  "likes"           integer                  NOT NULL DEFAULT 0,
  "guardados"       integer                  NOT NULL DEFAULT 0,
  "compartidos"     integer                  NOT NULL DEFAULT 0,
  "visitas"         integer                  NOT NULL DEFAULT 0,
  "color_ambiente"  text                     NOT NULL DEFAULT '#8F5136'::text,
  "fragment_start"  numeric(8,2)             NOT NULL DEFAULT 0,
  "fragment_end"    numeric(8,2),
  "album"           text                     NOT NULL DEFAULT ''::text,
  "descripcion"     text                     NOT NULL DEFAULT ''::text,
  CONSTRAINT "reels_color_principal_formato_check" CHECK (((color_principal IS NULL) OR (color_principal ~ '^#[0-9a-fA-F]{6}$'::text))),
  CONSTRAINT "reels_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."reels"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_blocks" (
  "blocker_id" uuid                     NOT NULL,
  "blocked_id" uuid                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "user_blocks_different_users" CHECK ((blocker_id <> blocked_id)),
  CONSTRAINT "user_blocks_pkey" PRIMARY KEY (blocker_id, blocked_id)
);

ALTER TABLE "public"."user_blocks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_genre_affinity" (
  "user_id"             uuid                     NOT NULL,
  "genre"               text                     NOT NULL,
  "behavioral_score"    numeric(10,3)            NOT NULL DEFAULT 0,
  "listening_sessions"  integer                  NOT NULL DEFAULT 0,
  "last_interaction_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "user_genre_affinity_pkey" PRIMARY KEY (user_id, genre)
);

ALTER TABLE "public"."user_genre_affinity"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_genre_preferences" (
  "user_id"    uuid                     NOT NULL,
  "genero"     text                     NOT NULL,
  "peso"       integer                  NOT NULL DEFAULT 1,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "updated_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "user_genre_preferences_genero_valido"
    CHECK
    ((genero = ANY (ARRAY['pop'::text, 'rock'::text, 'edm'::text, 'jazz'::text, 'blues'::text, 'cumbia'::text, 'trap'::text, 'metal'::text, 'folklore'::text, 'otros'::text]))),
  CONSTRAINT "user_genre_preferences_pkey" PRIMARY KEY (user_id, genero)
);

CREATE TABLE "public"."user_interests" (
  "user_id"    uuid                     NOT NULL,
  "genre"      text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "user_interests_genre_check"
    CHECK
    ((genre = ANY (ARRAY['pop'::text, 'rock'::text, 'trap'::text, 'cumbia'::text, 'edm'::text, 'jazz'::text, 'blues'::text, 'metal'::text, 'folklore'::text, 'otros'::text]))),
  CONSTRAINT "user_interests_pkey" PRIMARY KEY (user_id, genre)
);

ALTER TABLE "public"."user_interests"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_settings" (
  "user_id"                 uuid                     NOT NULL,
  "telefono"                text                     NOT NULL DEFAULT ''::text,
  "idioma"                  text                     NOT NULL DEFAULT 'es'::text,
  "actividad_cuenta"        boolean                  NOT NULL DEFAULT true,
  "mostrar_email"           boolean                  NOT NULL DEFAULT false,
  "updated_at"              timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "codigo_pais"             text                     NOT NULL DEFAULT '+54'::text,
  "notificar_interacciones" boolean                  NOT NULL DEFAULT true,
  "notificar_comentarios"   boolean                  NOT NULL DEFAULT true,
  "notificar_seguidores"    boolean                  NOT NULL DEFAULT true,
  "notificar_publicaciones" boolean                  NOT NULL DEFAULT true,
  "notificar_menciones"     boolean                  NOT NULL DEFAULT true,
  "reducir_movimiento"      boolean                  NOT NULL DEFAULT false,
  "notificar_mensajes"      boolean                  NOT NULL DEFAULT true,
  "created_at"              timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "user_settings_codigo_pais_check" CHECK ((codigo_pais = ANY (ARRAY['+54'::text, '+55'::text, '+56'::text, '+598'::text]))),
  CONSTRAINT "user_settings_idioma_check" CHECK ((idioma = ANY (ARRAY['es'::text, 'en'::text, 'pt'::text]))),
  CONSTRAINT "user_settings_pkey" PRIMARY KEY (user_id),
  CONSTRAINT "user_settings_telefono_check" CHECK ((length(telefono) <= 30))
);

ALTER TABLE "public"."user_settings"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."users" (
  "id"                   uuid                     NOT NULL,
  "email"                text                     NOT NULL,
  "username"             text                     NOT NULL,
  "created_at"           timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "profile_img_url"      text,
  "bio"                  text                     NOT NULL DEFAULT ''::text,
  "updated_at"           timestamp with time zone,
  "profile_img_path"     text,
  "display_name"         text,
  "birth_date"           date,
  "user_type"            text                     NOT NULL DEFAULT 'musico'::text,
  "full_name"            text,
  "artist_name"          text,
  "artist_bio"           text,
  "banner_url"           text,
  "instagram_url"        text,
  "verified"             boolean                  DEFAULT false,
  "onboarding_completed" boolean                  NOT NULL DEFAULT false,
  CONSTRAINT "users_birth_date_min_check" CHECK (((birth_date IS NULL) OR (birth_date >= '1900-01-01'::date))),
  CONSTRAINT "users_email_key" UNIQUE (email),
  CONSTRAINT "users_pkey" PRIMARY KEY (id),
  CONSTRAINT "users_user_type_check" CHECK ((user_type = ANY (ARRAY['musico'::text, 'organizador'::text, 'admin'::text]))),
  CONSTRAINT "users_username_formato_check" CHECK ((username ~ '^[a-z0-9._-]{3,30}$'::text)),
  CONSTRAINT "users_username_key" UNIQUE (username)
);

ALTER TABLE "public"."users"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.actualizar_afinidad_desde_escucha()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
DECLARE
  genre_value text;
  delta numeric := 0;
  session_delta integer := 0;
BEGIN
  SELECT lower(r.genero) INTO genre_value
  FROM public.reels r
  WHERE r.id = COALESCE(NEW.reel_id, OLD.reel_id);

  IF genre_value IS NULL OR genre_value = '' THEN
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    delta := public.playback_signal_score(
      NEW.listened_ms, NEW.completion_ratio, NEW.completed, NEW.skipped, NEW.replay_count
    );
    session_delta := 1;
  ELSIF TG_OP = 'UPDATE' THEN
    delta := public.playback_signal_score(
      NEW.listened_ms, NEW.completion_ratio, NEW.completed, NEW.skipped, NEW.replay_count
    ) - public.playback_signal_score(
      OLD.listened_ms, OLD.completion_ratio, OLD.completed, OLD.skipped, OLD.replay_count
    );
  ELSE
    delta := -public.playback_signal_score(
      OLD.listened_ms, OLD.completion_ratio, OLD.completed, OLD.skipped, OLD.replay_count
    );
    session_delta := -1;
  END IF;

  INSERT INTO public.user_genre_affinity (
    user_id, genre, behavioral_score, listening_sessions, last_interaction_at
  ) VALUES (
    COALESCE(NEW.user_id, OLD.user_id),
    genre_value,
    GREATEST(-50::numeric, LEAST(250::numeric, delta)),
    GREATEST(0, session_delta),
    timezone('utc'::text, now())
  )
  ON CONFLICT (user_id, genre) DO UPDATE
  SET behavioral_score = GREATEST(
        -50::numeric,
        LEAST(250::numeric, public.user_genre_affinity.behavioral_score + delta)
      ),
      listening_sessions = GREATEST(
        0,
        public.user_genre_affinity.listening_sessions + session_delta
      ),
      last_interaction_at = timezone('utc'::text, now());

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."actualizar_afinidad_desde_escucha"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.actualizar_conversacion_por_mensaje()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
BEGIN
  UPDATE public.conversations
  SET last_message_at = NEW.created_at,
      updated_at = timezone('utc'::text, now())
  WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."actualizar_conversacion_por_mensaje"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.broadcast_conversation_read_change()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
BEGIN
  IF OLD.last_delivered_at IS DISTINCT FROM NEW.last_delivered_at THEN
    PERFORM realtime.send(
      jsonb_build_object(
        'user_id', NEW.user_id,
        'last_delivered_at', NEW.last_delivered_at
      ),
      'delivered',
      'conversation:' || NEW.conversation_id::text,
      true
    );
  END IF;

  IF OLD.last_read_at IS DISTINCT FROM NEW.last_read_at THEN
    PERFORM realtime.send(
      jsonb_build_object(
        'user_id', NEW.user_id,
        'last_read_at', NEW.last_read_at
      ),
      'read',
      'conversation:' || NEW.conversation_id::text,
      true
    );
  END IF;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."broadcast_conversation_read_change"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.broadcast_message_change()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
DECLARE
  conversation_uuid uuid;
BEGIN
  conversation_uuid := COALESCE(NEW.conversation_id, OLD.conversation_id);
  PERFORM realtime.broadcast_changes(
    'conversation:' || conversation_uuid::text,
    TG_OP,
    TG_OP,
    TG_TABLE_NAME,
    TG_TABLE_SCHEMA,
    NEW,
    OLD
  );
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."broadcast_message_change"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.crear_publicacion_automatica_perfil()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
BEGIN
  IF TG_TABLE_NAME = 'reels' THEN
    INSERT INTO public.perfil_comunidad_publicaciones (
      user_id, origen, texto, reel_id
    ) VALUES (
      NEW.creador_id,
      'reel',
      format('Publico una nueva preview: %s.', NEW.titulo),
      NEW.id
    )
    ON CONFLICT (reel_id) WHERE origen = 'reel' DO NOTHING;
  ELSIF TG_TABLE_NAME = 'eventos' THEN
    INSERT INTO public.perfil_comunidad_publicaciones (
      user_id, origen, texto, evento_id
    ) VALUES (
      NEW.creador_id,
      'evento',
      format('Creo un nuevo evento en %s.', COALESCE(NULLIF(NEW.lugar, ''), 'un lugar a confirmar')),
      NEW.id
    )
    ON CONFLICT (evento_id) WHERE origen = 'evento' DO NOTHING;
  END IF;

  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."crear_publicacion_automatica_perfil"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.is_conversation_member (
  conversation_uuid uuid,
  member_uuid       uuid DEFAULT auth.uid()
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.conversation_members cm
    WHERE cm.conversation_id = conversation_uuid
      AND cm.user_id = member_uuid
  );
$function$;

REVOKE ALL ON FUNCTION "public"."is_conversation_member"(uuid, uuid) FROM PUBLIC, "anon", "service_role";

CREATE OR REPLACE FUNCTION public.playback_signal_score (
  listened      integer,
  ratio         numeric,
  was_completed boolean,
  was_skipped   boolean,
  replays       smallint
)
  RETURNS numeric
  LANGUAGE sql
  IMMUTABLE
  PARALLEL SAFE
  SET search_path TO ''
  AS $function$
  SELECT LEAST(16::numeric, GREATEST(0, COALESCE(listened, 0))::numeric / 3000)
       + LEAST(14::numeric, GREATEST(0, COALESCE(ratio, 0)) * 14)
       + CASE WHEN COALESCE(was_completed, false) THEN 5 ELSE 0 END
       + LEAST(8::numeric, GREATEST(0, COALESCE(replays, 0))::numeric * 4)
       - CASE
           WHEN COALESCE(was_skipped, false) AND COALESCE(listened, 0) < 5000 THEN 9
           WHEN COALESCE(was_skipped, false) THEN 3
           ELSE 0
         END;
$function$;

REVOKE ALL ON FUNCTION "public"."playback_signal_score"(integer, numeric, boolean, boolean, smallint) FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.sincronizar_ubicacion_evento()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path TO ''
  AS $function$
BEGIN
  IF NEW.latitud IS NULL OR NEW.longitud IS NULL THEN
    NEW.ubicacion_geog := NULL;
  ELSE
    NEW.ubicacion_geog := gis.ST_SetSRID(
      gis.ST_MakePoint(NEW.longitud, NEW.latitud),
      4326
    )::gis.geography;
  END IF;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."sincronizar_ubicacion_evento"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.sync_auth_user_email()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
BEGIN
  UPDATE public.users
  SET email = COALESCE(NEW.email, NEW.id::text || '@sin-email.local'),
      updated_at = timezone('utc'::text, now())
  WHERE id = NEW.id;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."sync_auth_user_email"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.validar_padre_respuesta_perfil()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
BEGIN
  IF NEW.parent_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.perfil_comunidad_respuestas padre
    WHERE padre.id = NEW.parent_id
      AND padre.publicacion_id = NEW.publicacion_id
  ) THEN
    RAISE EXCEPTION 'La respuesta citada no pertenece a esta publicacion.'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."validar_padre_respuesta_perfil"() FROM "anon", "authenticated", "service_role";

ALTER TABLE "public"."comunidad_comentario_guardados"
  ADD CONSTRAINT "comunidad_comentario_guardados_comentario_id_fkey" FOREIGN KEY (comentario_id) REFERENCES public.comunidad_comentarios(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_comentario_likes"
  ADD CONSTRAINT "comunidad_comentario_likes_comentario_id_fkey" FOREIGN KEY (comentario_id) REFERENCES public.comunidad_comentarios(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_comentarios"
  ADD CONSTRAINT "comunidad_comentarios_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.comunidad_comentarios(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_comentarios"
  ADD CONSTRAINT "comunidad_comentarios_publicacion_id_fkey" FOREIGN KEY (publicacion_id) REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_publicacion_guardados"
  ADD CONSTRAINT "comunidad_publicacion_guardados_publicacion_id_fkey" FOREIGN KEY (publicacion_id) REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_publicacion_likes"
  ADD CONSTRAINT "comunidad_publicacion_likes_publicacion_id_fkey" FOREIGN KEY (publicacion_id) REFERENCES public.comunidad_publicaciones(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_miembros"
  ADD CONSTRAINT "comunidad_miembros_comunidad_id_fkey" FOREIGN KEY (comunidad_id) REFERENCES public.comunidades(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_publicaciones"
  ADD CONSTRAINT "comunidad_publicaciones_comunidad_id_fkey" FOREIGN KEY (comunidad_id) REFERENCES public.comunidades(id) ON DELETE CASCADE;

ALTER TABLE "public"."conversation_members"
  ADD CONSTRAINT "conversation_members_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;

ALTER TABLE "public"."event_organizers"
  ADD CONSTRAINT "event_organizers_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.eventos(id) ON DELETE CASCADE;

ALTER TABLE "public"."event_saves"
  ADD CONSTRAINT "event_saves_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.eventos(id) ON DELETE CASCADE;

ALTER TABLE "public"."evento_generos"
  ADD CONSTRAINT "evento_generos_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.eventos(id) ON DELETE CASCADE;

ALTER TABLE "public"."follows"
  ADD CONSTRAINT "follows_no_self_follow_chk" CHECK ((follower_id <> following_id)) NOT VALID;

ALTER TABLE "public"."evento_generos"
  ADD CONSTRAINT "evento_generos_genero_fkey" FOREIGN KEY (genero) REFERENCES public.generos(slug);

ALTER TABLE "public"."messages"
  ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;

ALTER TABLE "public"."messages"
  ADD CONSTRAINT "messages_reply_to_id_fkey" FOREIGN KEY (reply_to_id) REFERENCES public.messages(id) ON DELETE SET NULL;

ALTER TABLE "public"."notification_mutes"
  ADD CONSTRAINT "notification_mutes_follow_fk" FOREIGN KEY (user_id, muted_user_id) REFERENCES public.follows(follower_id, following_id) ON DELETE CASCADE;

ALTER TABLE "public"."perfil_comunidad_publicaciones"
  ADD CONSTRAINT "perfil_comunidad_publicaciones_evento_id_fkey" FOREIGN KEY (evento_id) REFERENCES public.eventos(id) ON DELETE CASCADE;

ALTER TABLE "public"."perfil_comunidad_respuestas"
  ADD CONSTRAINT "perfil_comunidad_respuestas_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.perfil_comunidad_respuestas(id) ON DELETE CASCADE;

ALTER TABLE "public"."perfil_comunidad_respuestas"
  ADD CONSTRAINT "perfil_comunidad_respuestas_publicacion_id_fkey" FOREIGN KEY (publicacion_id) REFERENCES public.perfil_comunidad_publicaciones(id) ON DELETE CASCADE;

ALTER TABLE "public"."profile_community_posts"
  ADD CONSTRAINT "profile_community_posts_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.eventos(id) ON DELETE CASCADE;

ALTER TABLE "public"."profile_community_comments"
  ADD CONSTRAINT "profile_community_comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.profile_community_posts(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_comment_likes"
  ADD CONSTRAINT "reel_comment_likes_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.reel_comments(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_comments"
  ADD CONSTRAINT "reel_comments_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.reel_comments(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_generos"
  ADD CONSTRAINT "reel_generos_genero_fkey" FOREIGN KEY (genero) REFERENCES public.generos(slug);

ALTER TABLE "public"."perfil_comunidad_publicaciones"
  ADD CONSTRAINT "perfil_comunidad_publicaciones_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."profile_community_posts"
  ADD CONSTRAINT "profile_community_posts_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_comments"
  ADD CONSTRAINT "reel_comments_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_generos"
  ADD CONSTRAINT "reel_generos_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_likes"
  ADD CONSTRAINT "reel_likes_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_playback_sessions"
  ADD CONSTRAINT "reel_playback_sessions_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_saves"
  ADD CONSTRAINT "reel_saves_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_shares"
  ADD CONSTRAINT "reel_shares_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_views"
  ADD CONSTRAINT "reel_views_reel_id_fkey" FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_blocks"
  ADD CONSTRAINT "user_blocks_no_self_block_chk" CHECK ((blocker_id <> blocked_id)) NOT VALID;

ALTER TABLE "public"."users"
  ADD CONSTRAINT "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_comentario_guardados"
  ADD CONSTRAINT "comunidad_comentario_guardados_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_comentario_likes"
  ADD CONSTRAINT "comunidad_comentario_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_comentarios"
  ADD CONSTRAINT "comunidad_comentarios_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_miembros"
  ADD CONSTRAINT "comunidad_miembros_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_publicacion_guardados"
  ADD CONSTRAINT "comunidad_publicacion_guardados_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_publicacion_likes"
  ADD CONSTRAINT "comunidad_publicacion_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."comunidad_publicaciones"
  ADD CONSTRAINT "comunidad_publicaciones_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."content_reports"
  ADD CONSTRAINT "content_reports_reported_user_id_fkey" FOREIGN KEY (reported_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE "public"."content_reports"
  ADD CONSTRAINT "content_reports_reporter_id_fkey" FOREIGN KEY (reporter_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."conversations"
  ADD CONSTRAINT "conversations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE "public"."event_organizers"
  ADD CONSTRAINT "event_organizers_added_by_fkey" FOREIGN KEY (added_by) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."event_organizers"
  ADD CONSTRAINT "event_organizers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."event_saves"
  ADD CONSTRAINT "event_saves_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."eventos"
  ADD CONSTRAINT "eventos_creador_id_fkey" FOREIGN KEY (creador_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."follows"
  ADD CONSTRAINT "follows_follower_id_fkey" FOREIGN KEY (follower_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."follows"
  ADD CONSTRAINT "follows_following_id_fkey" FOREIGN KEY (following_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."messages"
  ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE "public"."notifications"
  ADD CONSTRAINT "notifications_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE "public"."notifications"
  ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."perfil_comunidad_publicaciones"
  ADD CONSTRAINT "perfil_comunidad_publicaciones_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."perfil_comunidad_respuestas"
  ADD CONSTRAINT "perfil_comunidad_respuestas_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."profile_community_comments"
  ADD CONSTRAINT "profile_community_comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."profile_community_posts"
  ADD CONSTRAINT "profile_community_posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_comment_likes"
  ADD CONSTRAINT "reel_comment_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_comments"
  ADD CONSTRAINT "reel_comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_likes"
  ADD CONSTRAINT "reel_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_playback_sessions"
  ADD CONSTRAINT "reel_playback_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_saves"
  ADD CONSTRAINT "reel_saves_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_shares"
  ADD CONSTRAINT "reel_shares_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reel_views"
  ADD CONSTRAINT "reel_views_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."reels"
  ADD CONSTRAINT "reels_creador_id_fkey" FOREIGN KEY (creador_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_blocks"
  ADD CONSTRAINT "user_blocks_blocked_id_fkey" FOREIGN KEY (blocked_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_blocks"
  ADD CONSTRAINT "user_blocks_blocker_id_fkey" FOREIGN KEY (blocker_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_genre_affinity"
  ADD CONSTRAINT "user_genre_affinity_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_genre_preferences"
  ADD CONSTRAINT "user_genre_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_interests"
  ADD CONSTRAINT "user_interests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_settings"
  ADD CONSTRAINT "user_settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

CREATE INDEX conversation_members_user_id_idx ON public.conversation_members USING btree (user_id);

CREATE INDEX conversation_members_user_idx ON public.conversation_members USING btree (user_id, conversation_id);

CREATE INDEX conversations_last_message_idx ON public.conversations USING btree (last_message_at DESC, id);

CREATE INDEX conversations_updated_idx ON public.conversations USING btree (updated_at DESC);

CREATE INDEX event_organizers_user_id_idx ON public.event_organizers USING btree (user_id);

CREATE INDEX evento_generos_genero_event_idx ON public.evento_generos USING btree (genero, event_id);

CREATE INDEX eventos_creador_id_idx ON public.eventos USING btree (creador_id);

CREATE INDEX eventos_ubicacion_geog_gist_idx ON public.eventos USING gist (ubicacion_geog);

CREATE INDEX idx_comunidad_comentario_guardados_comentario ON public.comunidad_comentario_guardados USING btree (comentario_id);

CREATE INDEX idx_comunidad_comentario_likes_comentario ON public.comunidad_comentario_likes USING btree (comentario_id);

CREATE INDEX idx_comunidad_comentarios_parent ON public.comunidad_comentarios USING btree (parent_id);

CREATE INDEX idx_comunidad_comentarios_publicacion ON public.comunidad_comentarios USING btree (publicacion_id, created_at);

CREATE INDEX idx_comunidad_miembros_user ON public.comunidad_miembros USING btree (user_id, created_at DESC);

CREATE INDEX idx_comunidad_publicacion_guardados_publicacion ON public.comunidad_publicacion_guardados USING btree (publicacion_id);

CREATE INDEX idx_comunidad_publicacion_likes_publicacion ON public.comunidad_publicacion_likes USING btree (publicacion_id);

CREATE INDEX idx_comunidad_publicaciones_comunidad ON public.comunidad_publicaciones USING btree (comunidad_id, created_at DESC);

CREATE INDEX idx_comunidad_publicaciones_user ON public.comunidad_publicaciones USING btree (user_id);

CREATE INDEX idx_content_reports_status ON public.content_reports USING btree (status, created_at DESC);

CREATE INDEX idx_event_saves_event_id ON public.event_saves USING btree (event_id);

CREATE INDEX idx_eventos_fecha ON public.eventos USING btree (fecha);

CREATE INDEX idx_follows_following_id ON public.follows USING btree (following_id);

CREATE INDEX idx_reel_comment_likes_comment_id ON public.reel_comment_likes USING btree (comment_id);

CREATE INDEX idx_reel_comments_parent_id ON public.reel_comments USING btree (parent_id);

CREATE INDEX idx_reel_comments_reel_id ON public.reel_comments USING btree (reel_id);

CREATE INDEX idx_reel_likes_reel_id ON public.reel_likes USING btree (reel_id);

CREATE INDEX idx_reel_saves_reel_id ON public.reel_saves USING btree (reel_id);

CREATE INDEX idx_reel_shares_reel_id ON public.reel_shares USING btree (reel_id);

CREATE INDEX idx_reel_views_reel_id ON public.reel_views USING btree (reel_id);

CREATE INDEX idx_user_blocks_blocked_id ON public.user_blocks USING btree (blocked_id);

CREATE INDEX idx_user_genre_preferences_genero ON public.user_genre_preferences USING btree (genero);

CREATE INDEX messages_conversation_created_idx ON public.messages USING btree (conversation_id, created_at, id);

CREATE INDEX messages_conversation_cursor_idx ON public.messages USING btree (conversation_id, id DESC);

CREATE INDEX messages_sender_id_idx ON public.messages USING btree (sender_id);

CREATE INDEX messages_sender_rate_idx ON public.messages USING btree (sender_id, created_at DESC);

CREATE INDEX notification_mutes_muted_user_idx ON public.notification_mutes USING btree (muted_user_id);

CREATE INDEX notifications_user_created_idx ON public.notifications USING btree (user_id, created_at DESC);

CREATE INDEX notifications_user_unread_idx ON public.notifications USING btree (user_id, created_at DESC)
  WHERE (read_at IS NULL);

CREATE UNIQUE INDEX perfil_comunidad_auto_evento_idx ON public.perfil_comunidad_publicaciones USING btree (evento_id)
  WHERE (origen = 'evento'::text);

CREATE UNIQUE INDEX perfil_comunidad_auto_reel_idx ON public.perfil_comunidad_publicaciones USING btree (reel_id)
  WHERE (origen = 'reel'::text);

CREATE INDEX perfil_comunidad_publicaciones_user_idx ON public.perfil_comunidad_publicaciones USING btree (user_id, created_at DESC, id DESC);

CREATE INDEX perfil_comunidad_respuestas_parent_idx ON public.perfil_comunidad_respuestas USING btree (parent_id);

CREATE INDEX perfil_comunidad_respuestas_publicacion_idx ON public.perfil_comunidad_respuestas USING btree (publicacion_id, created_at, id);

CREATE INDEX profile_community_comments_post_date_idx ON public.profile_community_comments USING btree (post_id, created_at);

CREATE UNIQUE INDEX profile_community_posts_event_unique ON public.profile_community_posts USING btree (event_id)
  WHERE (event_id IS NOT NULL);

CREATE UNIQUE INDEX profile_community_posts_reel_unique ON public.profile_community_posts USING btree (reel_id)
  WHERE (reel_id IS NOT NULL);

CREATE INDEX profile_community_posts_user_date_idx ON public.profile_community_posts USING btree (user_id, created_at DESC);

CREATE INDEX reel_generos_genero_reel_idx ON public.reel_generos USING btree (genero, reel_id);

CREATE INDEX reel_playback_reel_idx ON public.reel_playback_sessions USING btree (reel_id, updated_at DESC);

CREATE INDEX reel_playback_user_recent_idx ON public.reel_playback_sessions USING btree (user_id, updated_at DESC);

CREATE INDEX reels_creador_id_idx ON public.reels USING btree (creador_id);

CREATE INDEX reels_created_at_idx ON public.reels USING btree (created_at DESC);

CREATE INDEX user_genre_affinity_score_idx ON public.user_genre_affinity USING btree (user_id, behavioral_score DESC);

CREATE INDEX user_interests_genre_idx ON public.user_interests USING btree (genre, user_id);

CREATE UNIQUE INDEX users_username_lower_unique ON public.users USING btree (lower(username));

CREATE TRIGGER on_auth_user_email_updated
  AFTER UPDATE OF email ON auth.users
  FOR EACH ROW
  WHEN (((old.email)::text IS DISTINCT FROM (new.email)::text))
  EXECUTE FUNCTION public.sync_auth_user_email();

CREATE TRIGGER conversation_members_broadcast_read
  AFTER UPDATE OF last_read_at, last_delivered_at ON public.conversation_members
  FOR EACH ROW
  EXECUTE FUNCTION public.broadcast_conversation_read_change();

CREATE TRIGGER eventos_sincronizar_ubicacion
  BEFORE INSERT OR UPDATE OF latitud, longitud ON public.eventos
  FOR EACH ROW
  EXECUTE FUNCTION public.sincronizar_ubicacion_evento();

CREATE TRIGGER perfil_comunidad_evento_creado
  AFTER INSERT ON public.eventos
  FOR EACH ROW
  EXECUTE FUNCTION public.crear_publicacion_automatica_perfil();

CREATE TRIGGER messages_actualizar_conversacion
  AFTER INSERT ON public.messages
  FOR EACH ROW
  EXECUTE FUNCTION public.actualizar_conversacion_por_mensaje();

CREATE TRIGGER messages_broadcast_change
  AFTER INSERT OR DELETE OR UPDATE ON public.messages
  FOR EACH ROW
  EXECUTE FUNCTION public.broadcast_message_change();

CREATE TRIGGER perfil_comunidad_respuesta_padre_valido
  BEFORE INSERT OR UPDATE OF parent_id, publicacion_id ON public.perfil_comunidad_respuestas
  FOR EACH ROW
  EXECUTE FUNCTION public.validar_padre_respuesta_perfil();

CREATE TRIGGER reel_playback_actualizar_afinidad
  AFTER INSERT OR DELETE OR UPDATE ON public.reel_playback_sessions
  FOR EACH ROW
  EXECUTE FUNCTION public.actualizar_afinidad_desde_escucha();

CREATE TRIGGER perfil_comunidad_reel_creado
  AFTER INSERT ON public.reels
  FOR EACH ROW
  EXECUTE FUNCTION public.crear_publicacion_automatica_perfil();

CREATE POLICY "comunidad_comentario_likes_delete_own" ON "public"."comunidad_comentario_likes"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidad_comentario_likes_insert_own" ON "public"."comunidad_comentario_likes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "comunidad_comentario_likes_select_public" ON "public"."comunidad_comentario_likes"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "comunidad_comentarios_delete_own" ON "public"."comunidad_comentarios"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidad_comentarios_insert_own" ON "public"."comunidad_comentarios"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "comunidad_comentarios_select_public" ON "public"."comunidad_comentarios"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "comunidad_miembros_delete_own" ON "public"."comunidad_miembros"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidad_miembros_insert_own" ON "public"."comunidad_miembros"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "comunidad_miembros_own_write" ON "public"."comunidad_miembros"
  FOR ALL
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "comunidad_miembros_select_own" ON "public"."comunidad_miembros"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidad_publicacion_guardados_delete_own" ON "public"."comunidad_publicacion_guardados"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidad_publicacion_guardados_insert_own" ON "public"."comunidad_publicacion_guardados"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "comunidad_publicacion_guardados_select_own" ON "public"."comunidad_publicacion_guardados"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidad_publicacion_likes_delete_own" ON "public"."comunidad_publicacion_likes"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidad_publicacion_likes_insert_own" ON "public"."comunidad_publicacion_likes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "comunidad_publicacion_likes_select_public" ON "public"."comunidad_publicacion_likes"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "comunidad_publicaciones_delete_own" ON "public"."comunidad_publicaciones"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidad_publicaciones_insert_own" ON "public"."comunidad_publicaciones"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "comunidad_publicaciones_select_public" ON "public"."comunidad_publicaciones"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "comunidad_publicaciones_update_own" ON "public"."comunidad_publicaciones"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "comunidades_select_public" ON "public"."comunidades"
  FOR SELECT
  TO PUBLIC
  USING ((activa = true));

CREATE POLICY "conversation_members_member_read" ON "public"."conversation_members"
  FOR SELECT
  TO "authenticated"
  USING (public.is_conversation_member(conversation_id, ( SELECT auth.uid() AS uid)));

CREATE POLICY "conversations_member_read" ON "public"."conversations"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
  WHERE public.is_conversation_member(conversations.id, ( SELECT auth.uid() AS uid)))));

CREATE POLICY "event_saves_delete_own" ON "public"."event_saves"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "event_saves_insert_own" ON "public"."event_saves"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "event_saves_select_own" ON "public"."event_saves"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "evento_generos_owner_write" ON "public"."evento_generos"
  FOR ALL
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.eventos e
  WHERE ((e.id = evento_generos.event_id) AND (e.creador_id = auth.uid())))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.eventos e
  WHERE ((e.id = evento_generos.event_id) AND (e.creador_id = auth.uid())))));

CREATE POLICY "evento_generos_public_read" ON "public"."evento_generos"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "Cualquiera puede leer eventos" ON "public"."eventos"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Solo creadores pueden insertar sus eventos" ON "public"."eventos"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = creador_id));

CREATE POLICY "Solo creadores pueden modificar sus eventos" ON "public"."eventos"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = creador_id));

CREATE POLICY "follows_delete_own" ON "public"."follows"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = follower_id));

CREATE POLICY "follows_insert_own" ON "public"."follows"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = follower_id));

CREATE POLICY "follows_select_authenticated" ON "public"."follows"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() IS NOT NULL));

CREATE POLICY "generos_public_read" ON "public"."generos"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "messages_member_insert" ON "public"."messages"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((sender_id = ( SELECT auth.uid() AS uid)) AND public.is_conversation_member(conversation_id, ( SELECT auth.uid() AS uid))));

CREATE POLICY "messages_member_read" ON "public"."messages"
  FOR SELECT
  TO "authenticated"
  USING (public.is_conversation_member(conversation_id, ( SELECT auth.uid() AS uid)));

CREATE POLICY "messages_sender_change" ON "public"."messages"
  FOR UPDATE
  TO "authenticated"
  USING ((sender_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK (((sender_id = ( SELECT auth.uid() AS uid)) AND public.is_conversation_member(conversation_id, ( SELECT auth.uid() AS uid))));

CREATE POLICY "notification_mutes_delete_own" ON "public"."notification_mutes"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "notification_mutes_insert_own" ON "public"."notification_mutes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "notification_mutes_select_own" ON "public"."notification_mutes"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "notifications_delete_own" ON "public"."notifications"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "notifications_select_own" ON "public"."notifications"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "notifications_update_own" ON "public"."notifications"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "perfil_comunidad_publicaciones_delete_own" ON "public"."perfil_comunidad_publicaciones"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "perfil_comunidad_publicaciones_insert_own" ON "public"."perfil_comunidad_publicaciones"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((auth.uid() = user_id) AND (origen = 'manual'::text) AND ((reel_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.reels r
  WHERE ((r.id = perfil_comunidad_publicaciones.reel_id) AND (r.creador_id = auth.uid()))))) AND ((evento_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.eventos e
  WHERE ((e.id = perfil_comunidad_publicaciones.evento_id) AND (e.creador_id = auth.uid())))))));

CREATE POLICY "perfil_comunidad_publicaciones_read" ON "public"."perfil_comunidad_publicaciones"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "perfil_comunidad_publicaciones_update_own" ON "public"."perfil_comunidad_publicaciones"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK (((auth.uid() = user_id) AND (origen = 'manual'::text) AND ((reel_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.reels r
  WHERE ((r.id = perfil_comunidad_publicaciones.reel_id) AND (r.creador_id = auth.uid()))))) AND ((evento_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.eventos e
  WHERE ((e.id = perfil_comunidad_publicaciones.evento_id) AND (e.creador_id = auth.uid())))))));

CREATE POLICY "perfil_comunidad_respuestas_delete_own" ON "public"."perfil_comunidad_respuestas"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "perfil_comunidad_respuestas_insert_follower" ON "public"."perfil_comunidad_respuestas"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM public.perfil_comunidad_publicaciones p
  WHERE ((p.id = perfil_comunidad_respuestas.publicacion_id) AND ((p.user_id = auth.uid()) OR (EXISTS ( SELECT 1
           FROM public.follows f
          WHERE ((f.follower_id = auth.uid()) AND (f.following_id = p.user_id))))))))));

CREATE POLICY "perfil_comunidad_respuestas_read" ON "public"."perfil_comunidad_respuestas"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "reel_comment_likes_delete_own" ON "public"."reel_comment_likes"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "reel_comment_likes_insert_own" ON "public"."reel_comment_likes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "reel_comment_likes_select_public" ON "public"."reel_comment_likes"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "reel_comments_delete_own" ON "public"."reel_comments"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "reel_comments_insert_own" ON "public"."reel_comments"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "reel_comments_select_public" ON "public"."reel_comments"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "reel_generos_owner_write" ON "public"."reel_generos"
  FOR ALL
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.reels r
  WHERE ((r.id = reel_generos.reel_id) AND (r.creador_id = auth.uid())))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.reels r
  WHERE ((r.id = reel_generos.reel_id) AND (r.creador_id = auth.uid())))));

CREATE POLICY "reel_generos_public_read" ON "public"."reel_generos"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "reel_likes_delete_own" ON "public"."reel_likes"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "reel_likes_insert_own" ON "public"."reel_likes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "reel_likes_select_public" ON "public"."reel_likes"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "reel_playback_own" ON "public"."reel_playback_sessions"
  FOR ALL
  TO "authenticated"
  USING ((user_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "reel_saves_delete_own" ON "public"."reel_saves"
  FOR DELETE
  TO "authenticated"
  USING ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "reel_saves_insert_own" ON "public"."reel_saves"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "reel_saves_select_own" ON "public"."reel_saves"
  FOR SELECT
  TO "authenticated"
  USING ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "reel_shares_insert_own" ON "public"."reel_shares"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "reel_shares_select_own" ON "public"."reel_shares"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Anyone can read reels" ON "public"."reels"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can create own reels" ON "public"."reels"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = creador_id));

CREATE POLICY "Users can delete own reels" ON "public"."reels"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = creador_id));

CREATE POLICY "Users can update own reels" ON "public"."reels"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = creador_id))
  WITH CHECK ((auth.uid() = creador_id));

CREATE POLICY "user_genre_affinity_own_read" ON "public"."user_genre_affinity"
  FOR SELECT
  TO "authenticated"
  USING ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "user_interests_own" ON "public"."user_interests"
  FOR ALL
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "user_settings_delete_own" ON "public"."user_settings"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "user_settings_insert_own" ON "public"."user_settings"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "user_settings_select_own" ON "public"."user_settings"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "user_settings_update_own" ON "public"."user_settings"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Usuarios pueden ver su propio perfil" ON "public"."users"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = id));

CREATE POLICY "sondar_conversation_realtime_read" ON "realtime"."messages"
  FOR SELECT
  TO "authenticated"
  USING (((EXTENSION = ANY (ARRAY['broadcast'::text, 'presence'::text])) AND (EXISTS ( SELECT 1
   FROM public.conversation_members cm
  WHERE ((cm.user_id = ( SELECT auth.uid() AS uid)) AND (('conversation:'::text || (cm.conversation_id)::text) = realtime.topic()))))));

CREATE POLICY "sondar_conversation_realtime_send" ON "realtime"."messages"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((extension = ANY (ARRAY['broadcast'::text, 'presence'::text])) AND (EXISTS ( SELECT 1
   FROM public.conversation_members cm
  WHERE ((cm.user_id = ( SELECT auth.uid() AS uid)) AND (('conversation:'::text || (cm.conversation_id)::text) = realtime.topic()))))));

CREATE POLICY "sondar_eventos_delete_own" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING (((bucket_id = 'eventos'::text) AND (owner_id = (auth.uid())::text)));

CREATE POLICY "sondar_eventos_insert_own" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'eventos'::text) AND ((storage.foldername(name))[2] = (auth.uid())::text)));

CREATE POLICY "sondar_eventos_select_own" ON "storage"."objects"
  FOR SELECT
  TO "authenticated"
  USING (((bucket_id = 'eventos'::text) AND (owner_id = (auth.uid())::text)));

CREATE POLICY "sondar_perfiles_delete_own" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING (((bucket_id = 'perfiles'::text) AND (owner_id = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "sondar_perfiles_insert_own" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'perfiles'::text) AND ((storage.foldername(name))[2] = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "sondar_perfiles_select_own" ON "storage"."objects"
  FOR SELECT
  TO "authenticated"
  USING (((bucket_id = 'perfiles'::text) AND (owner_id = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "sondar_reels_delete_own" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING (((bucket_id = 'reels'::text) AND (owner_id = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "sondar_reels_insert_own" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'reels'::text) AND ((storage.foldername(name))[3] = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "sondar_reels_select_own" ON "storage"."objects"
  FOR SELECT
  TO "authenticated"
  USING (((bucket_id = 'reels'::text) AND (owner_id = ( SELECT (auth.uid())::text AS uid))));

COMMENT ON COLUMN "public"."comunidad_miembros"."nivel_notificaciones" IS 'Nivel elegido por el miembro: todas, relevantes o silenciadas.';

COMMENT ON EXTENSION "postgis" IS 'PostGIS geometry and geography spatial types and functions';

GRANT EXECUTE ON FUNCTION "public"."actualizar_afinidad_desde_escucha"() TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."actualizar_conversacion_por_mensaje"() TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."broadcast_conversation_read_change"() TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."broadcast_message_change"() TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."crear_publicacion_automatica_perfil"() TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."is_conversation_member"(uuid, uuid) TO "authenticated", "postgres";

GRANT EXECUTE ON FUNCTION "public"."playback_signal_score"(integer, numeric, boolean, boolean, smallint) TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."sincronizar_ubicacion_evento"() TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."sync_auth_user_email"() TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."validar_padre_respuesta_perfil"() TO PUBLIC, "postgres";

GRANT CREATE, USAGE ON SCHEMA "gis" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidad_comentario_guardados" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentario_guardados" TO "anon";

REVOKE ALL ON TABLE "public"."comunidad_comentario_guardados" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentario_guardados" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comunidad_comentario_guardados" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidad_comentario_guardados" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentario_guardados" TO "service_role";

REVOKE ALL ON TABLE "public"."comunidad_comentario_likes" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentario_likes" TO "anon";

REVOKE ALL ON TABLE "public"."comunidad_comentario_likes" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentario_likes" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comunidad_comentario_likes" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidad_comentario_likes" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentario_likes" TO "service_role";

REVOKE ALL ON TABLE "public"."comunidad_comentarios" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentarios" TO "anon";

REVOKE ALL ON TABLE "public"."comunidad_comentarios" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentarios" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comunidad_comentarios" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidad_comentarios" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_comentarios" TO "service_role";

REVOKE ALL ON TABLE "public"."comunidad_miembros" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_miembros" TO "anon";

REVOKE ALL ON TABLE "public"."comunidad_miembros" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_miembros" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comunidad_miembros" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidad_miembros" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_miembros" TO "service_role";

REVOKE ALL ON TABLE "public"."comunidad_publicacion_guardados" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicacion_guardados" TO "anon";

REVOKE ALL ON TABLE "public"."comunidad_publicacion_guardados" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicacion_guardados" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comunidad_publicacion_guardados" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidad_publicacion_guardados" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicacion_guardados" TO "service_role";

REVOKE ALL ON TABLE "public"."comunidad_publicacion_likes" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicacion_likes" TO "anon";

REVOKE ALL ON TABLE "public"."comunidad_publicacion_likes" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicacion_likes" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comunidad_publicacion_likes" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidad_publicacion_likes" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicacion_likes" TO "service_role";

REVOKE ALL ON TABLE "public"."comunidad_publicaciones" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicaciones" TO "anon";

REVOKE ALL ON TABLE "public"."comunidad_publicaciones" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicaciones" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comunidad_publicaciones" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidad_publicaciones" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidad_publicaciones" TO "service_role";

REVOKE ALL ON TABLE "public"."comunidades" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidades" TO "anon";

REVOKE ALL ON TABLE "public"."comunidades" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidades" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comunidades" TO "postgres";

REVOKE ALL ON TABLE "public"."comunidades" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."comunidades" TO "service_role";

REVOKE ALL ON TABLE "public"."content_reports" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."content_reports" TO "anon";

REVOKE ALL ON TABLE "public"."content_reports" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."content_reports" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."content_reports" TO "postgres";

REVOKE ALL ON TABLE "public"."content_reports" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."content_reports" TO "service_role";

REVOKE ALL ON TABLE "public"."conversation_members" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."conversation_members" TO "anon";

REVOKE ALL ON TABLE "public"."conversation_members" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."conversation_members" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversation_members" TO "postgres";

REVOKE ALL ON TABLE "public"."conversation_members" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."conversation_members" TO "service_role";

REVOKE ALL ON TABLE "public"."conversations" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."conversations" TO "anon";

REVOKE ALL ON TABLE "public"."conversations" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."conversations" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversations" TO "postgres";

REVOKE ALL ON TABLE "public"."conversations" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."conversations" TO "service_role";

REVOKE ALL ON TABLE "public"."event_organizers" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."event_organizers" TO "anon";

REVOKE ALL ON TABLE "public"."event_organizers" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."event_organizers" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."event_organizers" TO "postgres";

REVOKE ALL ON TABLE "public"."event_organizers" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."event_organizers" TO "service_role";

REVOKE ALL ON TABLE "public"."event_saves" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."event_saves" TO "anon";

REVOKE ALL ON TABLE "public"."event_saves" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."event_saves" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."event_saves" TO "postgres";

REVOKE ALL ON TABLE "public"."event_saves" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."event_saves" TO "service_role";

REVOKE ALL ON TABLE "public"."evento_generos" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."evento_generos" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."evento_generos" TO "authenticated", "postgres";

REVOKE ALL ON TABLE "public"."evento_generos" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."evento_generos" TO "service_role";

REVOKE ALL ON TABLE "public"."eventos" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."eventos" TO "anon";

REVOKE ALL ON TABLE "public"."eventos" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."eventos" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."eventos" TO "postgres";

REVOKE ALL ON TABLE "public"."eventos" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."eventos" TO "service_role";

REVOKE ALL ON TABLE "public"."follows" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."follows" TO "anon";

REVOKE ALL ON TABLE "public"."follows" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."follows" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."follows" TO "postgres";

REVOKE ALL ON TABLE "public"."follows" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."follows" TO "service_role";

REVOKE ALL ON TABLE "public"."generos" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."generos" TO "anon";

REVOKE ALL ON TABLE "public"."generos" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."generos" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."generos" TO "postgres";

REVOKE ALL ON TABLE "public"."generos" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."generos" TO "service_role";

REVOKE ALL ON TABLE "public"."messages" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."messages" TO "anon";

REVOKE ALL ON TABLE "public"."messages" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."messages" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."messages" TO "postgres";

REVOKE ALL ON TABLE "public"."messages" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."messages" TO "service_role";

REVOKE ALL ON TABLE "public"."notification_mutes" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notification_mutes" TO "anon";

REVOKE ALL ON TABLE "public"."notification_mutes" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notification_mutes" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notification_mutes" TO "postgres";

REVOKE ALL ON TABLE "public"."notification_mutes" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notification_mutes" TO "service_role";

REVOKE ALL ON TABLE "public"."notifications" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notifications" TO "anon";

REVOKE ALL ON TABLE "public"."notifications" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notifications" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notifications" TO "postgres";

REVOKE ALL ON TABLE "public"."notifications" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notifications" TO "service_role";

REVOKE ALL ON TABLE "public"."perfil_comunidad_publicaciones" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."perfil_comunidad_publicaciones" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."perfil_comunidad_publicaciones" TO "authenticated", "postgres";

REVOKE ALL ON TABLE "public"."perfil_comunidad_publicaciones" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."perfil_comunidad_publicaciones" TO "service_role";

REVOKE ALL ON TABLE "public"."perfil_comunidad_respuestas" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."perfil_comunidad_respuestas" TO "anon";

REVOKE ALL ON TABLE "public"."perfil_comunidad_respuestas" FROM "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."perfil_comunidad_respuestas" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."perfil_comunidad_respuestas" TO "postgres";

REVOKE ALL ON TABLE "public"."perfil_comunidad_respuestas" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."perfil_comunidad_respuestas" TO "service_role";

REVOKE ALL ON TABLE "public"."profile_community_comments" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."profile_community_comments" TO "anon";

REVOKE ALL ON TABLE "public"."profile_community_comments" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."profile_community_comments" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profile_community_comments" TO "postgres";

REVOKE ALL ON TABLE "public"."profile_community_comments" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."profile_community_comments" TO "service_role";

REVOKE ALL ON TABLE "public"."profile_community_posts" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."profile_community_posts" TO "anon";

REVOKE ALL ON TABLE "public"."profile_community_posts" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."profile_community_posts" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profile_community_posts" TO "postgres";

REVOKE ALL ON TABLE "public"."profile_community_posts" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."profile_community_posts" TO "service_role";

REVOKE ALL ON TABLE "public"."reel_comment_likes" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_comment_likes" TO "anon";

REVOKE ALL ON TABLE "public"."reel_comment_likes" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_comment_likes" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reel_comment_likes" TO "postgres";

REVOKE ALL ON TABLE "public"."reel_comment_likes" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_comment_likes" TO "service_role";

REVOKE ALL ON TABLE "public"."reel_comments" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_comments" TO "anon";

REVOKE ALL ON TABLE "public"."reel_comments" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_comments" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reel_comments" TO "postgres";

REVOKE ALL ON TABLE "public"."reel_comments" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_comments" TO "service_role";

REVOKE ALL ON TABLE "public"."reel_generos" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."reel_generos" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reel_generos" TO "authenticated", "postgres";

REVOKE ALL ON TABLE "public"."reel_generos" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_generos" TO "service_role";

REVOKE ALL ON TABLE "public"."reel_likes" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_likes" TO "anon";

REVOKE ALL ON TABLE "public"."reel_likes" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_likes" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reel_likes" TO "postgres";

REVOKE ALL ON TABLE "public"."reel_likes" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_likes" TO "service_role";

REVOKE ALL ON TABLE "public"."reel_playback_sessions" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_playback_sessions" TO "anon";

REVOKE ALL ON TABLE "public"."reel_playback_sessions" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."reel_playback_sessions" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reel_playback_sessions" TO "postgres";

REVOKE ALL ON TABLE "public"."reel_playback_sessions" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_playback_sessions" TO "service_role";

REVOKE ALL ON TABLE "public"."reel_saves" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_saves" TO "anon";

REVOKE ALL ON TABLE "public"."reel_saves" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_saves" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reel_saves" TO "postgres";

REVOKE ALL ON TABLE "public"."reel_saves" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_saves" TO "service_role";

REVOKE ALL ON TABLE "public"."reel_shares" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_shares" TO "anon";

REVOKE ALL ON TABLE "public"."reel_shares" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_shares" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reel_shares" TO "postgres";

REVOKE ALL ON TABLE "public"."reel_shares" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_shares" TO "service_role";

REVOKE ALL ON TABLE "public"."reel_views" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_views" TO "anon";

REVOKE ALL ON TABLE "public"."reel_views" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_views" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reel_views" TO "postgres";

REVOKE ALL ON TABLE "public"."reel_views" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reel_views" TO "service_role";

REVOKE ALL ON TABLE "public"."reels" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reels" TO "anon";

REVOKE ALL ON TABLE "public"."reels" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reels" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reels" TO "postgres";

REVOKE ALL ON TABLE "public"."reels" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reels" TO "service_role";

REVOKE ALL ON TABLE "public"."user_blocks" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_blocks" TO "anon";

REVOKE ALL ON TABLE "public"."user_blocks" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_blocks" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_blocks" TO "postgres";

REVOKE ALL ON TABLE "public"."user_blocks" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_blocks" TO "service_role";

REVOKE ALL ON TABLE "public"."user_genre_affinity" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_genre_affinity" TO "anon";

REVOKE ALL ON TABLE "public"."user_genre_affinity" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."user_genre_affinity" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_genre_affinity" TO "postgres";

REVOKE ALL ON TABLE "public"."user_genre_affinity" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_genre_affinity" TO "service_role";

REVOKE ALL ON TABLE "public"."user_genre_preferences" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_genre_preferences" TO "anon";

REVOKE ALL ON TABLE "public"."user_genre_preferences" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_genre_preferences" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_genre_preferences" TO "postgres";

REVOKE ALL ON TABLE "public"."user_genre_preferences" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_genre_preferences" TO "service_role";

REVOKE ALL ON TABLE "public"."user_interests" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_interests" TO "anon";

REVOKE ALL ON TABLE "public"."user_interests" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_interests" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_interests" TO "postgres";

REVOKE ALL ON TABLE "public"."user_interests" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_interests" TO "service_role";

REVOKE ALL ON TABLE "public"."user_settings" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_settings" TO "anon";

REVOKE ALL ON TABLE "public"."user_settings" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_settings" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_settings" TO "postgres";

REVOKE ALL ON TABLE "public"."user_settings" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_settings" TO "service_role";

REVOKE ALL ON TABLE "public"."users" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."users" TO "anon";

REVOKE ALL ON TABLE "public"."users" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."users" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "postgres";

REVOKE ALL ON TABLE "public"."users" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."users" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "service_role";

