-- Optimización integral SONDAR.
-- Aplicar primero en staging. El proceso web ya no ejecuta DDL en runtime.
BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

-- Configuración y normalización de identidad (antes se ejecutaba en cada arranque).
ALTER TABLE public.user_settings
  ADD COLUMN IF NOT EXISTS notificar_interacciones boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notificar_comentarios boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notificar_seguidores boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notificar_publicaciones boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notificar_menciones boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS reducir_movimiento boolean NOT NULL DEFAULT false;

WITH preparados AS (
  SELECT id,
         created_at,
         left(regexp_replace(regexp_replace(lower(username), '^@+', ''), '[^a-z0-9._-]', '', 'g'), 30) AS candidato
  FROM public.users
), clasificados AS (
  SELECT id,
         candidato,
         row_number() OVER (PARTITION BY candidato ORDER BY created_at, id) AS posicion
  FROM preparados
)
UPDATE public.users u
SET username = 'u_' || left(md5(u.id::text), 28)
FROM clasificados c
WHERE c.id = u.id
  AND (length(c.candidato) < 3 OR c.posicion > 1);

UPDATE public.users
SET username = left(
  regexp_replace(regexp_replace(lower(username), '^@+', ''), '[^a-z0-9._-]', '', 'g'),
  30
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_unique
  ON public.users (lower(username));

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'users_username_formato_check'
      AND conrelid = 'public.users'::regclass
  ) THEN
    ALTER TABLE public.users
      ADD CONSTRAINT users_username_formato_check
      CHECK (username ~ '^[a-z0-9._-]{3,30}$') NOT VALID;
  END IF;
END $$;

-- Tablas que antes se creaban desde controladores/servicios.
ALTER TABLE public.reel_comments
  ADD COLUMN IF NOT EXISTS responde_a text;

CREATE TABLE IF NOT EXISTS public.reel_comment_likes (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  comment_id bigint NOT NULL REFERENCES public.reel_comments(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE IF NOT EXISTS public.reel_shares (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reel_id bigint NOT NULL REFERENCES public.reels(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, reel_id)
);

CREATE TABLE IF NOT EXISTS public.reel_views (
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reel_id bigint NOT NULL REFERENCES public.reels(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, reel_id)
);

CREATE TABLE IF NOT EXISTS public.user_blocks (
  blocker_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  blocked_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (blocker_id, blocked_id),
  CONSTRAINT user_blocks_different_users CHECK (blocker_id <> blocked_id)
);

CREATE TABLE IF NOT EXISTS public.content_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reported_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  content_type text NOT NULL,
  content_id text NOT NULL,
  reason text NOT NULL DEFAULT 'contenido_inapropiado',
  details text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pendiente',
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT content_reports_unique UNIQUE (reporter_id, content_type, content_id)
);

ALTER TABLE public.content_reports
  ADD COLUMN IF NOT EXISTS details text NOT NULL DEFAULT '';

DELETE FROM public.content_reports anterior
USING public.content_reports posterior
WHERE anterior.reporter_id = posterior.reporter_id
  AND anterior.content_type = posterior.content_type
  AND anterior.content_id = posterior.content_id
  AND anterior.id > posterior.id;

CREATE UNIQUE INDEX IF NOT EXISTS content_reports_unique
  ON public.content_reports (reporter_id, content_type, content_id);

CREATE TABLE IF NOT EXISTS public.comunidad_miembros (
  comunidad_id text NOT NULL REFERENCES public.comunidades(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (comunidad_id, user_id)
);

ALTER TABLE public.comunidad_publicaciones
  ADD COLUMN IF NOT EXISTS evento_asociado_id text,
  ADD COLUMN IF NOT EXISTS reel_asociado_id text;

-- Las asociaciones antiguas eran texto sin integridad referencial. Se conservan
-- solo los identificadores numericos validos y se tipan como las PK de destino.
UPDATE public.comunidad_publicaciones
SET evento_asociado_id = NULL
WHERE evento_asociado_id IS NOT NULL AND evento_asociado_id::text !~ '^\d+$';
UPDATE public.comunidad_publicaciones
SET reel_asociado_id = NULL
WHERE reel_asociado_id IS NOT NULL AND reel_asociado_id::text !~ '^\d+$';

ALTER TABLE public.comunidad_publicaciones
  ALTER COLUMN evento_asociado_id TYPE bigint USING NULLIF(evento_asociado_id::text, '')::bigint,
  ALTER COLUMN reel_asociado_id TYPE bigint USING NULLIF(reel_asociado_id::text, '')::bigint;

INSERT INTO public.comunidades (id, nombre, titulo, genero, descripcion, portada_url, activa)
VALUES
  ('pop', '@pop', 'Pop', 'pop', 'Charlas, lanzamientos, preguntas y recomendaciones para la escena pop de SONDAR.', 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=80', true),
  ('rock', '@rock', 'Rock', 'rock', 'Guitarras, fechas, bandas nuevas, demos y conversaciones de la comunidad rock.', 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1400&q=80', true),
  ('edm', '@edm', 'EDM', 'edm', 'Sets, drops, produccion, festivales y novedades de la comunidad EDM.', 'https://images.unsplash.com/photo-1571266028243-d220c9c3b8ef?auto=format&fit=crop&w=1400&q=80', true),
  ('jazz', '@jazz', 'Jazz', 'jazz', 'Improvisacion, standards, jams, discos y encuentros para oyentes y musicos de jazz.', 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1400&q=80', true),
  ('blues', '@blues', 'Blues', 'blues', 'Riffs, armonicas, zapadas, fechas y recomendaciones para quienes siguen el blues.', 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80', true),
  ('cumbia', '@cumbia', 'Cumbia', 'cumbia', 'Bandas, bailes, estrenos, eventos y charla abierta para la comunidad cumbiera.', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=80', true),
  ('trap', '@trap', 'Trap', 'trap', 'Beats, barras, productores, lanzamientos y debates de la escena trap.', 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1400&q=80', true),
  ('metal', '@metal', 'Metal', 'metal', 'Riffs pesados, fechas, discos, bandas emergentes y comunidad metalera.', 'https://images.unsplash.com/photo-1508252592163-5d3c3c5599ab?auto=format&fit=crop&w=1400&q=80', true),
  ('folklore', '@folklore', 'Folklore', 'folklore', 'Penas, canciones, instrumentos, festivales y relatos de la escena folklorica.', 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1400&q=80', true)
ON CONFLICT (id) DO UPDATE
SET nombre = EXCLUDED.nombre,
    titulo = EXCLUDED.titulo,
    genero = EXCLUDED.genero,
    descripcion = EXCLUDED.descripcion,
    portada_url = EXCLUDED.portada_url,
    activa = EXCLUDED.activa;

-- Índices ajustados a filtros, joins, conteos y orden real de los controladores.
CREATE INDEX IF NOT EXISTS eventos_fecha_id_idx
  ON public.eventos (fecha ASC, id DESC);
CREATE INDEX IF NOT EXISTS eventos_genero_fecha_idx
  ON public.eventos (lower(genero), fecha ASC, id DESC);
CREATE INDEX IF NOT EXISTS eventos_creador_fecha_idx
  ON public.eventos (creador_id, fecha DESC, id DESC);
CREATE INDEX IF NOT EXISTS event_organizers_user_event_idx
  ON public.event_organizers (user_id, event_id);
CREATE INDEX IF NOT EXISTS event_saves_event_user_idx
  ON public.event_saves (event_id, user_id);

CREATE INDEX IF NOT EXISTS reels_created_id_idx
  ON public.reels (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS reels_genero_created_idx
  ON public.reels (lower(genero), created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS reels_creador_created_idx
  ON public.reels (creador_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS reel_views_reel_idx ON public.reel_views (reel_id);
CREATE INDEX IF NOT EXISTS reel_likes_reel_idx ON public.reel_likes (reel_id);
CREATE INDEX IF NOT EXISTS reel_saves_reel_idx ON public.reel_saves (reel_id);
CREATE INDEX IF NOT EXISTS reel_shares_reel_idx ON public.reel_shares (reel_id);
CREATE INDEX IF NOT EXISTS reel_comments_reel_created_idx
  ON public.reel_comments (reel_id, created_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS reel_comment_likes_comment_idx
  ON public.reel_comment_likes (comment_id);

CREATE INDEX IF NOT EXISTS comunidad_miembros_user_created_idx
  ON public.comunidad_miembros (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS comunidad_publicaciones_foro_created_idx
  ON public.comunidad_publicaciones (comunidad_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS comunidad_publicaciones_user_created_idx
  ON public.comunidad_publicaciones (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS comunidad_publicaciones_evento_idx
  ON public.comunidad_publicaciones (evento_asociado_id) WHERE evento_asociado_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS comunidad_publicaciones_reel_idx
  ON public.comunidad_publicaciones (reel_asociado_id) WHERE reel_asociado_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS comunidad_publicacion_likes_post_idx
  ON public.comunidad_publicacion_likes (publicacion_id);
CREATE INDEX IF NOT EXISTS comunidad_publicacion_guardados_post_idx
  ON public.comunidad_publicacion_guardados (publicacion_id);
CREATE INDEX IF NOT EXISTS comunidad_comentarios_post_created_idx
  ON public.comunidad_comentarios (publicacion_id, created_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS comunidad_comentarios_parent_idx
  ON public.comunidad_comentarios (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS comunidad_comentario_likes_comment_idx
  ON public.comunidad_comentario_likes (comentario_id);

CREATE INDEX IF NOT EXISTS follows_following_follower_idx
  ON public.follows (following_id, follower_id);
CREATE INDEX IF NOT EXISTS user_blocks_blocked_blocker_idx
  ON public.user_blocks (blocked_id, blocker_id);
CREATE INDEX IF NOT EXISTS content_reports_status_created_idx
  ON public.content_reports (status, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS notifications_user_unread_created_idx
  ON public.notifications (user_id, created_at DESC, id DESC)
  WHERE read_at IS NULL;

-- Reglas de integridad para nuevas escrituras; NOT VALID evita bloquear la migración por legado.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'eventos_coordenadas_validas') THEN
    ALTER TABLE public.eventos ADD CONSTRAINT eventos_coordenadas_validas
      CHECK (latitud BETWEEN -90 AND 90 AND longitud BETWEEN -180 AND 180) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'eventos_link_seguro') THEN
    ALTER TABLE public.eventos ADD CONSTRAINT eventos_link_seguro
      CHECK (link IS NULL OR link ~* '^https?://') NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comunidad_publicaciones_longitud') THEN
    ALTER TABLE public.comunidad_publicaciones ADD CONSTRAINT comunidad_publicaciones_longitud
      CHECK (
        length(titulo) BETWEEN 1 AND 300
        AND length(texto) BETWEEN 1 AND 10000
        AND (etiqueta IS NULL OR length(etiqueta) <= 40)
      ) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comunidad_comentarios_longitud') THEN
    ALTER TABLE public.comunidad_comentarios ADD CONSTRAINT comunidad_comentarios_longitud
      CHECK (length(texto) BETWEEN 1 AND 4000) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reel_comments_longitud') THEN
    ALTER TABLE public.reel_comments ADD CONSTRAINT reel_comments_longitud
      CHECK (length(texto) BETWEEN 1 AND 2000) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reels_contenido_longitud') THEN
    ALTER TABLE public.reels ADD CONSTRAINT reels_contenido_longitud
      CHECK (
        length(titulo) BETWEEN 1 AND 50
        AND length(album) BETWEEN 1 AND 60
        AND length(descripcion) <= 180
      ) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comunidad_publicaciones_evento_fk') THEN
    ALTER TABLE public.comunidad_publicaciones ADD CONSTRAINT comunidad_publicaciones_evento_fk
      FOREIGN KEY (evento_asociado_id) REFERENCES public.eventos(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comunidad_publicaciones_reel_fk') THEN
    ALTER TABLE public.comunidad_publicaciones ADD CONSTRAINT comunidad_publicaciones_reel_fk
      FOREIGN KEY (reel_asociado_id) REFERENCES public.reels(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'eventos_genero_catalogo') THEN
    ALTER TABLE public.eventos ADD CONSTRAINT eventos_genero_catalogo
      CHECK (lower(genero) IN ('pop', 'rock', 'edm', 'jazz', 'blues', 'cumbia', 'trap', 'metal', 'folklore', 'otros')) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reels_genero_catalogo') THEN
    ALTER TABLE public.reels ADD CONSTRAINT reels_genero_catalogo
      CHECK (lower(genero) IN ('pop', 'rock', 'edm', 'jazz', 'blues', 'cumbia', 'trap', 'metal', 'folklore', 'otros')) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'content_reports_contenido_valido') THEN
    ALTER TABLE public.content_reports ADD CONSTRAINT content_reports_contenido_valido
      CHECK (
        content_type IN ('reel', 'evento', 'perfil')
        AND length(content_id) BETWEEN 1 AND 200
        AND length(reason) BETWEEN 1 AND 100
        AND length(details) <= 500
        AND status IN ('pendiente', 'revisado', 'descartado')
      ) NOT VALID;
  END IF;
END $$;

ALTER TABLE public.reel_comment_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reel_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunidad_miembros ENABLE ROW LEVEL SECURITY;

-- El frontend usa Supabase solamente para Auth. Todo DML de negocio atraviesa
-- el backend, sus validadores, limites y transacciones. Service role y el rol
-- dedicado del backend no se ven afectados por esta revocacion.
REVOKE INSERT, UPDATE, DELETE ON TABLE
  public.users,
  public.user_settings,
  public.user_interests,
  public.follows,
  public.notification_mutes,
  public.user_blocks,
  public.eventos,
  public.event_organizers,
  public.event_saves,
  public.reels,
  public.reel_views,
  public.reel_likes,
  public.reel_saves,
  public.reel_shares,
  public.reel_comments,
  public.reel_comment_likes,
  public.comunidades,
  public.comunidad_miembros,
  public.comunidad_publicaciones,
  public.comunidad_publicacion_likes,
  public.comunidad_publicacion_guardados,
  public.comunidad_comentarios,
  public.comunidad_comentario_likes,
  public.notifications,
  public.content_reports
FROM anon, authenticated;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'comunidad_miembros' AND policyname = 'comunidad_miembros_select_own') THEN
    CREATE POLICY comunidad_miembros_select_own ON public.comunidad_miembros
      FOR SELECT TO authenticated USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'comunidad_miembros' AND policyname = 'comunidad_miembros_insert_own') THEN
    CREATE POLICY comunidad_miembros_insert_own ON public.comunidad_miembros
      FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'comunidad_miembros' AND policyname = 'comunidad_miembros_delete_own') THEN
    CREATE POLICY comunidad_miembros_delete_own ON public.comunidad_miembros
      FOR DELETE TO authenticated USING (auth.uid() = user_id);
  END IF;
END $$;

COMMIT;
